//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NBSActionMetric, NBSLaunchMetric, NSRecursiveLock, _priv_NBSEventTreeNode;

@interface _priv_NBSEventTree : NSObject
{
    NSRecursiveLock *reLock;
    _Bool _abnormal;
    _Bool _interrupt;
    _priv_NBSEventTreeNode *_root;
    NBSLaunchMetric *_appStartsMetric;
    NBSActionMetric *_actionMetric;
    unsigned long long _lifeRef;
    double _startTime;
    double _lastNodeTime;
}

@property(nonatomic) _Bool interrupt; // @synthesize interrupt=_interrupt;
@property double lastNodeTime; // @synthesize lastNodeTime=_lastNodeTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(nonatomic) _Bool abnormal; // @synthesize abnormal=_abnormal;
@property unsigned long long lifeRef; // @synthesize lifeRef=_lifeRef;
@property(retain, nonatomic) NBSActionMetric *actionMetric; // @synthesize actionMetric=_actionMetric;
@property(retain, nonatomic) NBSLaunchMetric *appStartsMetric; // @synthesize appStartsMetric=_appStartsMetric;
@property(retain, nonatomic) _priv_NBSEventTreeNode *root; // @synthesize root=_root;
- (void).cxx_destruct;
- (void)dealloc;
- (id)cutTree:(id)arg1;
- (void)fireTimer;
- (void)updateTreeState;
- (void)forceTimeout;
- (void)fixTree:(id)arg1;
- (void)insertNode:(id)arg1 parent:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithRootNode:(id)arg1;
- (id)init;

@end

