//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser10ZKBaseCell.h"

@class NSLayoutConstraint, UILabel, _TtC16JRJInvestAdviser24JRJStrategyPositionModel;

@interface _TtC16JRJInvestAdviser25JRJPositionTableViewCell3 : _TtC16JRJInvestAdviser10ZKBaseCell
{
    // Error parsing type: , name: stockNameLabel
    // Error parsing type: , name: stockCodeLabel
    // Error parsing type: , name: sell1UIlabel
    // Error parsing type: , name: sell2UIlabel
    // Error parsing type: , name: costPriceLabel
    // Error parsing type: , name: newPriceLabel
    // Error parsing type: , name: profitLabel
    // Error parsing type: , name: newPriceLayout
    // Error parsing type: , name: profitLayout
    // Error parsing type: , name: positionLayout
    // Error parsing type: , name: positionLayout2
    // Error parsing type: , name: model
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateViewForModel;
- (void)awakeFromNib;
@property(nonatomic, retain) _TtC16JRJInvestAdviser24JRJStrategyPositionModel *model; // @synthesize model;
@property(nonatomic, retain) NSLayoutConstraint *positionLayout2; // @synthesize positionLayout2;
@property(nonatomic, retain) NSLayoutConstraint *positionLayout; // @synthesize positionLayout;
@property(nonatomic, retain) NSLayoutConstraint *profitLayout; // @synthesize profitLayout;
@property(nonatomic, retain) NSLayoutConstraint *newPriceLayout; // @synthesize newPriceLayout;
@property(nonatomic, retain) UILabel *profitLabel; // @synthesize profitLabel;
@property(nonatomic, retain) UILabel *newPriceLabel; // @synthesize newPriceLabel;
@property(nonatomic, retain) UILabel *costPriceLabel; // @synthesize costPriceLabel;
@property(nonatomic, retain) UILabel *sell2UIlabel; // @synthesize sell2UIlabel;
@property(nonatomic, retain) UILabel *sell1UIlabel; // @synthesize sell1UIlabel;
@property(nonatomic, retain) UILabel *stockCodeLabel; // @synthesize stockCodeLabel;
@property(nonatomic, retain) UILabel *stockNameLabel; // @synthesize stockNameLabel;

@end

