//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class InvesterAdviserModel, _TtC16JRJInvestAdviser17IAHeaderImageView;

@interface _TtC16JRJInvestAdviser12IAColumnCell : UICollectionViewCell
{
    // Error parsing type: , name: view
    // Error parsing type: , name: adviserModel
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, retain) InvesterAdviserModel *adviserModel; // @synthesize adviserModel;
@property(nonatomic, retain) _TtC16JRJInvestAdviser17IAHeaderImageView *view; // @synthesize view;

@end

