//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser28JRJStandardizeViewController.h"

@interface _TtC16JRJInvestAdviser23JRJNavigationStyleTwoVC : _TtC16JRJInvestAdviser28JRJStandardizeViewController
{
    // Error parsing type: , name: titleColors
    // Error parsing type: , name: backImages
    // Error parsing type: , name: barStyles
    // Error parsing type: , name: max_yOffset
    // Error parsing type: , name: change_yOffset
    // Error parsing type: , name: translucent_alpha
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: jrj_navigationBar
    // Error parsing type: , name: jrj_navigationItem
    // Error parsing type: , name: jrj_backBtn
    // Error parsing type: , name: isShouldHandle
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithTableViewStyle:(long long)arg1;
- (void)yOffsetHandleWithYOffset:(double)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setTitleView;
- (void)setNavigationBarStyle;
- (void)createTitleLabel;
- (void)noNetLeftBtn;
- (id)createLeftBtnWithImage:(id)arg1;
- (void)setLeftBtnWithImage:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic) double translucent_alpha; // @synthesize translucent_alpha;
@property(nonatomic) double change_yOffset; // @synthesize change_yOffset;
@property(nonatomic) double max_yOffset; // @synthesize max_yOffset;

@end

