//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSString, UIColor;

@interface _TtC16JRJInvestAdviser16JRJTopInputModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: placeholder
    // Error parsing type: , name: cancelTitle
    // Error parsing type: , name: okTitle
    // Error parsing type: , name: cancelColor
    // Error parsing type: , name: okColor
    // Error parsing type: , name: disableColor
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) UIColor *disableColor; // @synthesize disableColor;
@property(nonatomic, retain) UIColor *okColor; // @synthesize okColor;
@property(nonatomic, retain) UIColor *cancelColor; // @synthesize cancelColor;
@property(nonatomic, copy) NSString *okTitle;
@property(nonatomic, copy) NSString *cancelTitle;
@property(nonatomic, copy) NSString *placeholder;

@end

