//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJZTradeTableViewController.h"

@class NSNumber, _TtC16JRJInvestAdviser17JRJZTradeHeadView;

@interface _TtC16JRJInvestAdviser35JRJZTradeDetailsTableViewController : JRJZTradeTableViewController
{
    // Error parsing type: , name: type
    // Error parsing type: , name: model
    // Error parsing type: , name: $__lazy_storage_$_headImageView
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithTableViewStyle:(long long)arg1;
- (void)detailsHandle;
- (id)createRightDetailsNavBtn;
- (void)addAndDelFuncWithOptionalAdded:(long long)arg1 model:(id)arg2 indexPath:(id)arg3;
- (void)tapHandlerBlockWithSection:(long long)arg1;
- (id)getModel;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)loadListRequest;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) _TtC16JRJInvestAdviser17JRJZTradeHeadView *headImageView;
@property(nonatomic, retain) NSNumber *type; // @synthesize type;

@end

