//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSArray, NSString;

@interface _TtC16JRJInvestAdviser26JRJConditionalSectionModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: title
    // Error parsing type: , name: isShowMore
    // Error parsing type: , name: isExpansion
    // Error parsing type: , name: allowMaxNum
    // Error parsing type: , name: itemData
    // Error parsing type: , name: isShowButton
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) _Bool isShowButton; // @synthesize isShowButton;
@property(nonatomic, copy) NSArray *itemData;
@property(nonatomic) long long allowMaxNum; // @synthesize allowMaxNum;
@property(nonatomic) _Bool isExpansion; // @synthesize isExpansion;
@property(nonatomic) _Bool isShowMore; // @synthesize isShowMore;
@property(nonatomic, copy) NSString *title;

@end

