//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface _TtC16JRJInvestAdviser17JRJStockAlertView : UIView
{
    // Error parsing type: , name: cancelButtonH
    // Error parsing type: , name: containerView
    // Error parsing type: , name: lineView
    // Error parsing type: , name: cancelButton
    // Error parsing type: , name: callback
    // Error parsing type: , name: alphaView
}

- (void).cxx_destruct;
- (void)dismiss:(_Bool)arg1;
- (void)show;
- (void)show:(CDUnknownBlockType)arg1;
- (void)cancelButtonTapped:(id)arg1;
- (void)setContainerView:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, copy) CDUnknownBlockType callback;
@property(nonatomic, readonly) double cancelButtonH; // @synthesize cancelButtonH;

@end

