//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSNumber, NSString;

@interface _TtC16JRJInvestAdviser15JRJProcessModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: desc
    // Error parsing type: , name: imageUrl
    // Error parsing type: , name: name
    // Error parsing type: , name: stage
    // Error parsing type: , name: stockNum
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) NSNumber *stockNum; // @synthesize stockNum;
@property(nonatomic, retain) NSNumber *stage; // @synthesize stage;
@property(nonatomic, copy) NSString *name;
@property(nonatomic, copy) NSString *imageUrl;
@property(nonatomic, copy) NSString *desc;

@end

