//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSNumber, NSString, _TtC16JRJInvestAdviser38JRJZPreferredPerformanceReferenceModel;

@interface _TtC16JRJInvestAdviser29JRJZPreferredPerformanceModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: reference
    // Error parsing type: , name: netAssert
    // Error parsing type: , name: currPrice
    // Error parsing type: , name: totalProfit
    // Error parsing type: , name: id
    // Error parsing type: , name: name
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSString *name;
@property(nonatomic, retain) NSNumber *id; // @synthesize id;
@property(nonatomic, retain) NSNumber *totalProfit; // @synthesize totalProfit;
@property(nonatomic, copy) NSString *currPrice;
@property(nonatomic, retain) _TtC16JRJInvestAdviser38JRJZPreferredPerformanceReferenceModel *netAssert; // @synthesize netAssert;
@property(nonatomic, retain) _TtC16JRJInvestAdviser38JRJZPreferredPerformanceReferenceModel *reference; // @synthesize reference;

@end

