//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSNumber, NSString;

@interface _TtC16JRJInvestAdviser26JRJDecisionRatingInfoModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: changeType
    // Error parsing type: , name: newName
    // Error parsing type: , name: newType
    // Error parsing type: , name: oldName
    // Error parsing type: , name: oldType
    // Error parsing type: , name: overallName
    // Error parsing type: , name: overallType
    // Error parsing type: , name: updateDate
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSString *updateDate;
@property(nonatomic, retain) NSNumber *overallType; // @synthesize overallType;
@property(nonatomic, copy) NSString *overallName;
@property(nonatomic, retain) NSNumber *oldType; // @synthesize oldType;
@property(nonatomic, copy) NSString *oldName;
@property(nonatomic, retain) NSNumber *newType; // @synthesize newType;
@property(nonatomic, copy) NSString *newName;
@property(nonatomic, retain) NSNumber *changeType; // @synthesize changeType;

@end

