//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser22ZKBaseHeaderFooterView.h"

@class NSNumber, UILabel;

@interface _TtC16JRJInvestAdviser30JRJPositionTableViewCellFooter : _TtC16JRJInvestAdviser22ZKBaseHeaderFooterView
{
    // Error parsing type: , name: percentUILabel
    // Error parsing type: , name: fillpositionPerTrade
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithReuseIdentifier:(id)arg1;
@property(nonatomic, retain) NSNumber *fillpositionPerTrade; // @synthesize fillpositionPerTrade;
@property(nonatomic, retain) UILabel *percentUILabel; // @synthesize percentUILabel;

@end

