//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser28JRJStandardizeViewController.h"

@class NSArray;

@interface _TtC16JRJInvestAdviser28JRJZPreferredMoreRecommendVC : _TtC16JRJInvestAdviser28JRJStandardizeViewController
{
    // Error parsing type: , name: basePosition
    // Error parsing type: , name: cell_VMS
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithTableViewStyle:(long long)arg1;
- (void)cellTapHandleWithParamModel:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)dataHandleWithObject:(id)arg1;
- (void)loadListRequest;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic, copy) NSArray *cell_VMS;

@end

