//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser10ZKBaseCell.h"

@class JFTagListView, NSLayoutConstraint, UIButton, UIImageView, UILabel, _TtC16JRJInvestAdviser19JRJZTradeStockModel;

@interface _TtC16JRJInvestAdviser29JRJZTradeDetailsTableViewCell : _TtC16JRJInvestAdviser10ZKBaseCell
{
    // Error parsing type: , name: stknameLabel
    // Error parsing type: , name: stkcodeLabel
    // Error parsing type: , name: priceLabel
    // Error parsing type: , name: changeRatioLabel
    // Error parsing type: , name: operationDescLabel
    // Error parsing type: , name: operationTypeImage
    // Error parsing type: , name: listTagView
    // Error parsing type: , name: addAndDelBtn
    // Error parsing type: , name: addAndDelFunc
    // Error parsing type: , name: heightConstraint
    // Error parsing type: , name: model
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)addAndDelHandle:(id)arg1;
- (void)updateViewForModel;
- (void)setSubViewStyle;
- (void)awakeFromNib;
@property(nonatomic, retain) _TtC16JRJInvestAdviser19JRJZTradeStockModel *model; // @synthesize model;
@property(nonatomic) __weak NSLayoutConstraint *heightConstraint; // @synthesize heightConstraint;
@property(nonatomic, copy) CDUnknownBlockType addAndDelFunc;
@property(nonatomic) __weak UIButton *addAndDelBtn; // @synthesize addAndDelBtn;
@property(nonatomic) __weak JFTagListView *listTagView; // @synthesize listTagView;
@property(nonatomic) __weak UIImageView *operationTypeImage; // @synthesize operationTypeImage;
@property(nonatomic) __weak UILabel *operationDescLabel; // @synthesize operationDescLabel;
@property(nonatomic) __weak UILabel *changeRatioLabel; // @synthesize changeRatioLabel;
@property(nonatomic) __weak UILabel *priceLabel; // @synthesize priceLabel;
@property(nonatomic) __weak UILabel *stkcodeLabel; // @synthesize stkcodeLabel;
@property(nonatomic) __weak UILabel *stknameLabel; // @synthesize stknameLabel;

@end

