//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSArray, NSNumber, NSString;

@interface _TtC16JRJInvestAdviser26JRJSetConditionalListModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: groupId
    // Error parsing type: , name: groupName
    // Error parsing type: , name: items
    // Error parsing type: , name: selectedItemsCount
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) NSNumber *selectedItemsCount; // @synthesize selectedItemsCount;
@property(nonatomic, copy) NSArray *items;
@property(nonatomic, copy) NSString *groupName;
@property(nonatomic, copy) NSString *groupId;

@end

