//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser28JRJStandardizeViewController.h"

@class NSDictionary, NSNumber, NSString, UIButton;

@interface _TtC16JRJInvestAdviser24JRJSetConditionalStockVC : _TtC16JRJInvestAdviser28JRJStandardizeViewController
{
    // Error parsing type: , name: model
    // Error parsing type: , name: ownerId
    // Error parsing type: , name: source
    // Error parsing type: , name: vcType
    // Error parsing type: , name: $__lazy_storage_$_searchBtn
    // Error parsing type: , name: selectDataDic
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithTableViewStyle:(long long)arg1;
- (void)dealloc;
- (void)pushSearchVC;
- (void)sectionEventHandleWithModel:(id)arg1;
- (void)searchParmHandleWithItemModel:(id)arg1 model:(id)arg2;
- (void)typeHandleWithItemModel:(id)arg1 model:(id)arg2 type:(long long)arg3;
- (void)cancleHandleWithItemModel:(id)arg1 model:(id)arg2 type:(long long)arg3;
- (void)viewEventHandleWithModel:(id)arg1;
- (void)sectionHeadCountHandleWithIndex:(long long)arg1 isAdd:(_Bool)arg2;
- (id)cellModelsWithHd_model:(id)arg1;
- (void)groupModelsWithG_model:(id)arg1;
- (void)dataHandleWithObject:(id)arg1;
- (void)loadListRequest;
- (void)viewDidLoad;
@property(nonatomic, copy) NSDictionary *selectDataDic;
@property(nonatomic, retain) UIButton *searchBtn;
@property(nonatomic, retain) NSNumber *source; // @synthesize source;
@property(nonatomic, copy) NSString *ownerId;

@end

