//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser28JRJStandardizeViewController.h"

@interface _TtC16JRJInvestAdviser23JRJTestVCViewController : _TtC16JRJInvestAdviser28JRJStandardizeViewController
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithTableViewStyle:(long long)arg1;
- (void)psectionHandleWithModel:(id)arg1;
- (void)zsectionHandleWithModel:(id)arg1;
- (void)useGuideCellWithModel:(id)arg1;
- (void)zReportCellHandleWithModel:(id)arg1;
- (void)allZCellHandleWithModel:(id)arg1;
- (void)dataHandleWithObject:(id)arg1;
- (void)loadListRequest;
- (void)viewDidLoad;

@end

