//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSString, UIColor;

@interface _TtC16JRJInvestAdviser21JRJOneTitleLabelModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: title
    // Error parsing type: , name: textFont
    // Error parsing type: , name: textColor
    // Error parsing type: , name: cellHight
    // Error parsing type: , name: isShowLine
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) _Bool isShowLine; // @synthesize isShowLine;
@property(nonatomic) double cellHight; // @synthesize cellHight;
@property(nonatomic, retain) UIColor *textColor; // @synthesize textColor;
@property(nonatomic) double textFont; // @synthesize textFont;
@property(nonatomic, copy) NSString *title;

@end

