//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser10ZKBaseCell.h"

@class NSString, UILabel;

@interface _TtC16JRJInvestAdviser19JRJNonePositionCell : _TtC16JRJInvestAdviser10ZKBaseCell
{
    // Error parsing type: , name: titleLabelText
    // Error parsing type: , name: titleLabel
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)awakeFromNib;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic, copy) NSString *titleLabelText;

@end

