//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser10ZKBaseCell.h"

@class NSLayoutConstraint, UIButton, UIImageView, UILabel;

@interface _TtC16JRJInvestAdviser22JRJZPreferredTodayCell : _TtC16JRJInvestAdviser10ZKBaseCell
{
    // Error parsing type: , name: giveupUILabel
    // Error parsing type: , name: stkcodeLabel
    // Error parsing type: , name: buyPriceLabel
    // Error parsing type: , name: changeRatio
    // Error parsing type: , name: fromAndToPriceLabel
    // Error parsing type: , name: trendNameLabel
    // Error parsing type: , name: riseProbabilityLabel
    // Error parsing type: , name: rxlyBtn
    // Error parsing type: , name: recommendLabel
    // Error parsing type: , name: ckjgqjLabel
    // Error parsing type: , name: qsypLabel
    // Error parsing type: , name: ylglImageV
    // Error parsing type: , name: ylglLabel
    // Error parsing type: , name: rightConstraint
    // Error parsing type: , name: bottomNSLayoutConstraint
    // Error parsing type: , name: topBaseLineConstraint
    // Error parsing type: , name: addBtn
    // Error parsing type: , name: buyDateLabel
    // Error parsing type: , name: leftFromAndToPriceConstraint
    // Error parsing type: , name: middleFromAndToPirceConstraint
    // Error parsing type: , name: middleLabelConstraint
    // Error parsing type: , name: rightLabelConstraint
    // Error parsing type: , name: labelBottomConstraint
    // Error parsing type: , name: lableTopConstraint
    // Error parsing type: , name: addFunc
    // Error parsing type: , name: cellType
    // Error parsing type: , name: showRiseProbability
    // Error parsing type: , name: showJZMNC
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)addBtnHandle:(id)arg1;
- (void)setCellLastestCellWithT_model:(id)arg1;
- (void)setShiRiCellWithT_model:(id)arg1;
- (void)setTodayCellWithT_model:(id)arg1;
- (void)updateViewForModelWithModel:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setSubViewStyle;
- (void)awakeFromNib;
@property(nonatomic) _Bool showJZMNC; // @synthesize showJZMNC;
@property(nonatomic) _Bool showRiseProbability; // @synthesize showRiseProbability;
@property(nonatomic, copy) CDUnknownBlockType addFunc;
@property(nonatomic) __weak NSLayoutConstraint *lableTopConstraint; // @synthesize lableTopConstraint;
@property(nonatomic) __weak NSLayoutConstraint *labelBottomConstraint; // @synthesize labelBottomConstraint;
@property(nonatomic) __weak NSLayoutConstraint *rightLabelConstraint; // @synthesize rightLabelConstraint;
@property(nonatomic) __weak NSLayoutConstraint *middleLabelConstraint; // @synthesize middleLabelConstraint;
@property(nonatomic) __weak NSLayoutConstraint *middleFromAndToPirceConstraint; // @synthesize middleFromAndToPirceConstraint;
@property(nonatomic) __weak NSLayoutConstraint *leftFromAndToPriceConstraint; // @synthesize leftFromAndToPriceConstraint;
@property(nonatomic) __weak UILabel *buyDateLabel; // @synthesize buyDateLabel;
@property(nonatomic) __weak UIButton *addBtn; // @synthesize addBtn;
@property(nonatomic) __weak NSLayoutConstraint *topBaseLineConstraint; // @synthesize topBaseLineConstraint;
@property(nonatomic) __weak NSLayoutConstraint *bottomNSLayoutConstraint; // @synthesize bottomNSLayoutConstraint;
@property(nonatomic) __weak NSLayoutConstraint *rightConstraint; // @synthesize rightConstraint;
@property(nonatomic) __weak UILabel *ylglLabel; // @synthesize ylglLabel;
@property(nonatomic) __weak UIImageView *ylglImageV; // @synthesize ylglImageV;
@property(nonatomic) __weak UILabel *qsypLabel; // @synthesize qsypLabel;
@property(nonatomic) __weak UILabel *ckjgqjLabel; // @synthesize ckjgqjLabel;
@property(nonatomic) __weak UILabel *recommendLabel; // @synthesize recommendLabel;
@property(nonatomic) __weak UILabel *rxlyBtn; // @synthesize rxlyBtn;
@property(nonatomic) __weak UILabel *riseProbabilityLabel; // @synthesize riseProbabilityLabel;
@property(nonatomic) __weak UILabel *trendNameLabel; // @synthesize trendNameLabel;
@property(nonatomic) __weak UILabel *fromAndToPriceLabel; // @synthesize fromAndToPriceLabel;
@property(nonatomic) __weak UILabel *changeRatio; // @synthesize changeRatio;
@property(nonatomic) __weak UILabel *buyPriceLabel; // @synthesize buyPriceLabel;
@property(nonatomic) __weak UILabel *stkcodeLabel; // @synthesize stkcodeLabel;
@property(nonatomic, retain) UILabel *giveupUILabel; // @synthesize giveupUILabel;

@end

