//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser10ZKBaseCell.h"

@class NSLayoutConstraint, UILabel;

@interface _TtC16JRJInvestAdviser20JRJZTradeAllNewZCell : _TtC16JRJInvestAdviser10ZKBaseCell
{
    // Error parsing type: , name: priceUILabel
    // Error parsing type: , name: stockCodeUILabel
    // Error parsing type: , name: stockNameUILabel
    // Error parsing type: , name: descUIlabel
    // Error parsing type: , name: signalUILabel
    // Error parsing type: , name: RaiseUILabel
    // Error parsing type: , name: priceLeftNSLayoutConstraint
    // Error parsing type: , name: raiseLeftNSLayoutConstraint
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)updateViewForModelWithModel:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
@property(nonatomic) __weak NSLayoutConstraint *raiseLeftNSLayoutConstraint; // @synthesize raiseLeftNSLayoutConstraint;
@property(nonatomic) __weak NSLayoutConstraint *priceLeftNSLayoutConstraint; // @synthesize priceLeftNSLayoutConstraint;
@property(nonatomic) __weak UILabel *RaiseUILabel; // @synthesize RaiseUILabel;
@property(nonatomic) __weak UILabel *signalUILabel; // @synthesize signalUILabel;
@property(nonatomic) __weak UILabel *descUIlabel; // @synthesize descUIlabel;
@property(nonatomic) __weak UILabel *stockNameUILabel; // @synthesize stockNameUILabel;
@property(nonatomic) __weak UILabel *stockCodeUILabel; // @synthesize stockCodeUILabel;
@property(nonatomic) __weak UILabel *priceUILabel; // @synthesize priceUILabel;

@end

