//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser10ZKBaseView.h"

@class UIImageView, UILabel, _TtC16JRJInvestAdviser31JRJZPreferredSelectProcessModel;

@interface _TtC16JRJInvestAdviser34JRJZPreferredSelectProcessHeadView : _TtC16JRJInvestAdviser10ZKBaseView
{
    // Error parsing type: , name: imageV
    // Error parsing type: , name: titleLabel
    // Error parsing type: , name: warnLabel
    // Error parsing type: , name: dateLabel
    // Error parsing type: , name: model
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateViewForModel;
@property(nonatomic, retain) _TtC16JRJInvestAdviser31JRJZPreferredSelectProcessModel *model; // @synthesize model;
@property(nonatomic) __weak UILabel *dateLabel; // @synthesize dateLabel;
@property(nonatomic) __weak UILabel *warnLabel; // @synthesize warnLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel;
@property(nonatomic) __weak UIImageView *imageV; // @synthesize imageV;

@end

