//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser28JRJStandardizeViewController.h"

@class NSString;

@interface _TtC16JRJInvestAdviser34JRJDecisionResearchReportDetailsVC : _TtC16JRJInvestAdviser28JRJStandardizeViewController
{
    // Error parsing type: , name: id
    // Error parsing type: , name: isFavor
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithTableViewStyle:(long long)arg1;
- (void)favorClicked;
- (void)createNavRightBtnWithWidth:(double)arg1 clickHandle:(CDUnknownBlockType)arg2;
- (void)dataHandleWithObject:(id)arg1;
- (void)loadListRequest;
- (void)viewDidLoad;
@property(nonatomic, copy) NSString *id;

@end

