//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSArray, NSNumber, NSString;

@interface _TtC16JRJInvestAdviser18JRJOptProcessModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: optDate
    // Error parsing type: , name: state
    // Error parsing type: , name: processList
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSArray *processList;
@property(nonatomic, retain) NSNumber *state; // @synthesize state;
@property(nonatomic, copy) NSString *optDate;

@end

