//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser28JRJStandardizeViewController.h"

@class NSDictionary, NSString;

@interface _TtC16JRJInvestAdviser27JRJZTradeAllZViewController : _TtC16JRJInvestAdviser28JRJStandardizeViewController
{
    // Error parsing type: , name: model
    // Error parsing type: , name: signalType
    // Error parsing type: , name: jsonDic
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithTableViewStyle:(long long)arg1;
- (void)loadIndexSignalRequest;
- (void)detailsHandle;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)dataHandleWithObject:(id)arg1;
- (void)loadListRequest;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) NSDictionary *jsonDic; // @synthesize jsonDic;
@property(nonatomic, copy) NSString *signalType;

@end

