//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSNumber;

@interface _TtC16JRJInvestAdviser15AuthInfoVOModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: remainDays
    // Error parsing type: , name: userType
    // Error parsing type: , name: valid
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) NSNumber *valid; // @synthesize valid;
@property(nonatomic, retain) NSNumber *userType; // @synthesize userType;
@property(nonatomic, retain) NSNumber *remainDays; // @synthesize remainDays;

@end

