//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSNumber, NSString, _TtC16JRJInvestAdviser17JRJStockInfoModel;

@interface _TtC16JRJInvestAdviser21JRJUserStrategieModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: id
    // Error parsing type: , name: name
    // Error parsing type: , name: order
    // Error parsing type: , name: stockInfo
    // Error parsing type: , name: totalCount
    // Error parsing type: , name: buyLink
    // Error parsing type: , name: valid
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) NSNumber *valid; // @synthesize valid;
@property(nonatomic, copy) NSString *buyLink;
@property(nonatomic, retain) NSNumber *totalCount; // @synthesize totalCount;
@property(nonatomic, retain) _TtC16JRJInvestAdviser17JRJStockInfoModel *stockInfo; // @synthesize stockInfo;
@property(nonatomic, retain) NSNumber *order; // @synthesize order;
@property(nonatomic, copy) NSString *name;
@property(nonatomic, retain) NSNumber *id; // @synthesize id;

@end

