//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser12JRJBaseModel.h"

@class NSArray, NSNumber, NSString, _TtC16JRJInvestAdviser30JRJStockCommunityUserInfoModel, _TtC16JRJInvestAdviser33JRJStockCommunityProductInfoModel;

@interface _TtC16JRJInvestAdviser22JRJStockCommunityModel : _TtC16JRJInvestAdviser12JRJBaseModel
{
    // Error parsing type: , name: filterInstruction
    // Error parsing type: , name: filters
    // Error parsing type: , name: strategies
    // Error parsing type: , name: userInfo
    // Error parsing type: , name: valid
    // Error parsing type: , name: productInfo
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, retain) _TtC16JRJInvestAdviser33JRJStockCommunityProductInfoModel *productInfo; // @synthesize productInfo;
@property(nonatomic, retain) NSNumber *valid; // @synthesize valid;
@property(nonatomic, retain) _TtC16JRJInvestAdviser30JRJStockCommunityUserInfoModel *userInfo; // @synthesize userInfo;
@property(nonatomic, copy) NSArray *strategies;
@property(nonatomic, copy) NSArray *filters;
@property(nonatomic, copy) NSString *filterInstruction;

@end

