//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "_TtC16JRJInvestAdviser28JRJStandardizeViewController.h"

@class NSString;

@interface _TtC16JRJInvestAdviser33JRJNavigationHandleViewController : _TtC16JRJInvestAdviser28JRJStandardizeViewController
{
    // Error parsing type: , name: head_Height
    // Error parsing type: , name: max_yOffset
    // Error parsing type: , name: vc_title
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithTableViewStyle:(long long)arg1;
- (void)yOffsetHandleWithYOffset:(double)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setTitleView;
- (void)loadTableView;
- (void)setTopHeadView;
- (void)setNavigationDefaultStyles;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)setNavigationCustomStyles;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, copy) NSString *vc_title;
@property(nonatomic) double max_yOffset; // @synthesize max_yOffset;
@property(nonatomic) double head_Height; // @synthesize head_Height;

@end

