//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface AdviserModel : NSObject
{
    NSString *_userId;
    NSString *_userName;
    NSString *_trueName;
    NSString *_headImage;
    NSString *_company;
    NSString *_orgName;
    NSString *_certificationNum;
    NSString *_experienceScope;
    NSNumber *_type;
    NSString *_typeDesc;
    NSString *_verify;
    NSString *_label;
    NSString *_intro;
    NSString *_about;
    NSString *_fansNum;
    NSArray *_activities;
    NSString *_introShare;
    NSString *_isFan;
    NSNumber *_relationStatus;
    NSNumber *_growupVal;
    NSNumber *_signV;
    NSNumber *_isAdviser;
    NSString *_city;
    NSString *_province;
    NSNumber *_level;
    NSString *_passportName;
}

@property(copy, nonatomic) NSString *passportName; // @synthesize passportName=_passportName;
@property(copy, nonatomic) NSNumber *level; // @synthesize level=_level;
@property(copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSNumber *isAdviser; // @synthesize isAdviser=_isAdviser;
@property(copy, nonatomic) NSNumber *signV; // @synthesize signV=_signV;
@property(copy, nonatomic) NSNumber *growupVal; // @synthesize growupVal=_growupVal;
@property(copy, nonatomic) NSNumber *relationStatus; // @synthesize relationStatus=_relationStatus;
@property(copy, nonatomic) NSString *isFan; // @synthesize isFan=_isFan;
@property(copy, nonatomic) NSString *introShare; // @synthesize introShare=_introShare;
@property(retain, nonatomic) NSArray *activities; // @synthesize activities=_activities;
@property(copy, nonatomic) NSString *fansNum; // @synthesize fansNum=_fansNum;
@property(copy, nonatomic) NSString *about; // @synthesize about=_about;
@property(copy, nonatomic) NSString *intro; // @synthesize intro=_intro;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
@property(copy, nonatomic) NSString *verify; // @synthesize verify=_verify;
@property(copy, nonatomic) NSString *typeDesc; // @synthesize typeDesc=_typeDesc;
@property(copy, nonatomic) NSNumber *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *experienceScope; // @synthesize experienceScope=_experienceScope;
@property(copy, nonatomic) NSString *certificationNum; // @synthesize certificationNum=_certificationNum;
@property(copy, nonatomic) NSString *orgName; // @synthesize orgName=_orgName;
@property(copy, nonatomic) NSString *company; // @synthesize company=_company;
@property(copy, nonatomic) NSString *headImage; // @synthesize headImage=_headImage;
@property(copy, nonatomic) NSString *trueName; // @synthesize trueName=_trueName;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;

@end

