//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseXibView.h"

@class JRJRCLabelProxy, RCLabel, UIImageView, UILabel, UserAskModel;

@interface AskView : BaseXibView
{
    _Bool _isQuestion;
    _Bool _userBackgroundColor;
    _Bool _isMe;
    _Bool _isShowCardStyle;
    UIImageView *_backImageView;
    UserAskModel *_userAskModel;
    double _maxContentWidth;
    RCLabel *_richTextLabel;
    CDUnknownBlockType _richTextLabelClickBlock;
    JRJRCLabelProxy *_rcLabelProxy;
    UIImageView *_askIconView;
    UILabel *_answerNumLabel;
}

+ (double)heightWithModel:(id)arg1;
+ (double)heightWithModel:(id)arg1 maxWidth:(double)arg2 fontSize:(double)arg3;
@property(nonatomic) __weak UILabel *answerNumLabel; // @synthesize answerNumLabel=_answerNumLabel;
@property(nonatomic) __weak UIImageView *askIconView; // @synthesize askIconView=_askIconView;
@property(retain, nonatomic) JRJRCLabelProxy *rcLabelProxy; // @synthesize rcLabelProxy=_rcLabelProxy;
@property(copy, nonatomic) CDUnknownBlockType richTextLabelClickBlock; // @synthesize richTextLabelClickBlock=_richTextLabelClickBlock;
@property(nonatomic) __weak RCLabel *richTextLabel; // @synthesize richTextLabel=_richTextLabel;
@property(nonatomic) _Bool isShowCardStyle; // @synthesize isShowCardStyle=_isShowCardStyle;
@property(nonatomic) _Bool isMe; // @synthesize isMe=_isMe;
@property(nonatomic) double maxContentWidth; // @synthesize maxContentWidth=_maxContentWidth;
@property(nonatomic) _Bool userBackgroundColor; // @synthesize userBackgroundColor=_userBackgroundColor;
@property(nonatomic) __weak UserAskModel *userAskModel; // @synthesize userAskModel=_userAskModel;
@property(nonatomic) _Bool isQuestion; // @synthesize isQuestion=_isQuestion;
@property(nonatomic) __weak UIImageView *backImageView; // @synthesize backImageView=_backImageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)configWithModel:(id)arg1;
- (void)awakeFromNib;

@end

