//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DataTradeBase.h"

@class NSNumber, NSString;

@interface BankTransAccountBankBroker : DataTradeBase
{
    int _direct;
    NSString *_userId;
    NSString *_sessionId;
    NSString *_password;
    NSString *_moneyType;
    NSString *_bankNo;
    NSNumber *_occurBalance;
    NSString *_broker;
    NSString *_accountId;
    NSString *_fundPassword;
    NSString *_bankPassword;
    NSNumber *_entrustNo;
}

@property(retain, nonatomic) NSNumber *entrustNo; // @synthesize entrustNo=_entrustNo;
@property(retain, nonatomic) NSString *bankPassword; // @synthesize bankPassword=_bankPassword;
@property(retain, nonatomic) NSString *fundPassword; // @synthesize fundPassword=_fundPassword;
@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
@property(retain, nonatomic) NSString *broker; // @synthesize broker=_broker;
@property(nonatomic) int direct; // @synthesize direct=_direct;
@property(retain, nonatomic) NSNumber *occurBalance; // @synthesize occurBalance=_occurBalance;
@property(retain, nonatomic) NSString *bankNo; // @synthesize bankNo=_bankNo;
@property(retain, nonatomic) NSString *moneyType; // @synthesize moneyType=_moneyType;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (void)update;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (id)init;

@end

