//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DataTradeBase.h"

@class NSArray, NSString;

@interface BankTransAccount : DataTradeBase
{
    NSString *_userId;
    NSString *_sessionId;
    NSString *_broker;
    NSString *_accountId;
    NSArray *_list;
}

@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
@property(retain, nonatomic) NSString *accountId; // @synthesize accountId=_accountId;
@property(retain, nonatomic) NSString *broker; // @synthesize broker=_broker;
@property(retain, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (void)update;
- (void)requestFailed:(id)arg1;
- (void)requestFinished:(id)arg1;
- (id)init;

@end

