//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJListTableViewController.h"

@class BigStarRecommendCell, BigStarsTableHeaderView, UIButton, UIView;

@interface BigStarDiscussMarketViewController : JRJListTableViewController
{
    _Bool _isNoAttentionAdvister;
    BigStarsTableHeaderView *_bigStarView;
    UIButton *_addBigshotBtn;
    BigStarRecommendCell *_bigStarRecommendCell;
    UIView *_tableHeaderView;
    long long _recommendPosition;
}

- (void).cxx_destruct;
- (void)startStockSearchViewController;
- (void)createTableHeaderViewWithArray:(id)arg1;
- (void)requestRecommendTouguIsClick:(_Bool)arg1;
- (void)dealData:(id)arg1 isRefresh:(_Bool)arg2;
- (void)requestTouGuAttentionListIsRefresh:(_Bool)arg1;
- (void)requestTouGuWhiteListIsRefresh:(_Bool)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)requestMoreListData;
- (void)refreshInfo;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)loadListRequest;
- (void)willRefreshInfo;
- (void)refreshData:(id)arg1;
- (void)createAddStockBtn;
- (void)viewDidLoad;

@end

