//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CJSimpleHUD : NSObject
{
}

+ (void)stopHUD;
+ (void)stopStringHUD;
+ (void)startStringHUD:(id)arg1 view_f:(id)arg2 delay:(double)arg3;
+ (id)viewForMessage:(id)arg1 title:(id)arg2 image:(id)arg3 view_f:(id)arg4;
+ (struct CGSize)sizeForString:(id)arg1 font:(id)arg2 constrainedToSize:(struct CGSize)arg3 lineBreakMode:(long long)arg4;
+ (void)startHUD:(id)arg1;
+ (void)startHUD;

@end

