//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DataBase.h"

#import "ASIHTTPRequestDelegate-Protocol.h"

@class ASIHTTPRequest, NSMutableDictionary, NSString, NSTimer;

@interface DataIStockBase : DataBase <ASIHTTPRequestDelegate>
{
    NSMutableDictionary *dictPackage;
    _Bool isRequestFinished;
    NSTimer *timer;
    _Bool isDataReqOk;
    ASIHTTPRequest *request;
}

+ (id)generateRequest:(id)arg1;
+ (id)addPackage:(id)arg1 withReq:(unsigned int)arg2 withBody:(char *)arg3 withBodyLen:(unsigned int)arg4;
+ (id)generateRequest:(unsigned int)arg1 withBody:(char *)arg2 withBodyLen:(unsigned int)arg3;
@property(nonatomic) ASIHTTPRequest *request; // @synthesize request;
@property(nonatomic) _Bool isDataReqOk; // @synthesize isDataReqOk;
- (void).cxx_destruct;
- (void)update:(unsigned long long)arg1;
- (void)update;
- (void)onIdle;
- (void)dealData;
- (void)requestFinished:(id)arg1;
- (void)requestFailed:(id)arg1;
- (void)requestStarted:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

