//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJRichTextModel.h"

@class NSDictionary, NSString, UserInformationModel;

@interface EditorMessgaePushListModel : JRJRichTextModel
{
    _Bool _isNewMessage;
    long long _dataid;
    long long _dataId;
    UserInformationModel *_userInfoModel;
    NSString *_titleStr;
    NSString *_timeStr;
    NSString *_subContentId;
    long long _contentType;
    long long _msgType;
    long long _roomId;
    NSString *_summary;
    NSString *_title;
    NSDictionary *_rawDict;
    NSDictionary *_dataEx;
    struct CGSize _titleLabelSize;
}

@property(retain, nonatomic) NSDictionary *dataEx; // @synthesize dataEx=_dataEx;
@property(retain, nonatomic) NSDictionary *rawDict; // @synthesize rawDict=_rawDict;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(nonatomic) long long roomId; // @synthesize roomId=_roomId;
@property(nonatomic) long long msgType; // @synthesize msgType=_msgType;
@property(nonatomic) long long contentType; // @synthesize contentType=_contentType;
@property(copy, nonatomic) NSString *subContentId; // @synthesize subContentId=_subContentId;
@property(nonatomic) struct CGSize titleLabelSize; // @synthesize titleLabelSize=_titleLabelSize;
@property(copy, nonatomic) NSString *timeStr; // @synthesize timeStr=_timeStr;
@property(nonatomic) _Bool isNewMessage; // @synthesize isNewMessage=_isNewMessage;
@property(copy, nonatomic) NSString *titleStr; // @synthesize titleStr=_titleStr;
@property(retain, nonatomic) UserInformationModel *userInfoModel; // @synthesize userInfoModel=_userInfoModel;
@property(nonatomic) long long dataId; // @synthesize dataId=_dataId;
@property(nonatomic) long long dataid; // @synthesize dataid=_dataid;
- (void).cxx_destruct;
- (id)getStockArrayFromPlainText:(id)arg1;
- (void)parseDictionary:(id)arg1;

@end

