//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "EMManager.h"

#import "IEMChatroomManager-Protocol.h"

@class EMMulticastDelegate, NSString;
@protocol EMChatroomManagerDelegate;

@interface EMChatroomManager : EMManager <IEMChatroomManager>
{
    struct EMChatroomManagerListener *chatroomListener_;
}

- (void)asyncFetchChatroomInfo:(id)arg1 includeMembersList:(_Bool)arg2 success:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
- (void)getChatroomSpecificationFromServerByID:(id)arg1 includeMembersList:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (void)asyncLeaveChatroom:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)leaveChatroom:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)fetchChatroomInfo:(id)arg1 includeMembersList:(_Bool)arg2 error:(id *)arg3;
- (id)leaveChatroom:(id)arg1 error:(id *)arg2;
- (void)asyncJoinChatroom:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)joinChatroom:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)handleChatroom:(id)arg1 request:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3;
- (id)joinChatroom:(id)arg1 error:(id *)arg2;
- (void)getChatroomsFromServerWithPage:(long long)arg1 pageSize:(long long)arg2 completion:(CDUnknownBlockType)arg3;
- (id)getChatroomsFromServerWithPage:(long long)arg1 pageSize:(long long)arg2 error:(id *)arg3;
- (void)asyncGetAllChatroomsFromServer:(CDUnknownBlockType)arg1 failure:(CDUnknownBlockType)arg2;
- (void)getAllChatroomsFromServerWithCompletion:(CDUnknownBlockType)arg1;
- (id)getAllChatroomsFromServerWithError:(id *)arg1;
- (id)_getCharroomWithId:(id)arg1;
@property(readonly, nonatomic) EMMulticastDelegate<EMChatroomManagerDelegate> *delegates;
- (void)removeChatroomListener;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (void)addDelegate:(id)arg1 delegateQueue:(id)arg2;
- (void)dealloc;
- (id)initWithClient:(struct EMChatClient *)arg1 reachability:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

