//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class EMGroup, NSArray, NSString;

@protocol EMGroupManagerDelegate <NSObject>

@optional
- (void)didUpdateGroupList:(NSArray *)arg1;
- (void)didReceiveAcceptedJoinGroup:(EMGroup *)arg1;
- (void)didReceiveDeclinedJoinGroup:(NSString *)arg1 reason:(NSString *)arg2;
- (void)didReceiveJoinGroupApplication:(EMGroup *)arg1 applicant:(NSString *)arg2 reason:(NSString *)arg3;
- (void)didReceiveLeavedGroup:(EMGroup *)arg1 reason:(int)arg2;
- (void)didJoinedGroup:(EMGroup *)arg1 inviter:(NSString *)arg2 message:(NSString *)arg3;
- (void)didReceiveDeclinedGroupInvitation:(EMGroup *)arg1 invitee:(NSString *)arg2 reason:(NSString *)arg3;
- (void)didReceiveAcceptedGroupInvitation:(EMGroup *)arg1 invitee:(NSString *)arg2;
- (void)didReceiveGroupInvitation:(NSString *)arg1 inviter:(NSString *)arg2 message:(NSString *)arg3;
- (void)groupListDidUpdate:(NSArray *)arg1;
- (void)joinGroupRequestDidApprove:(EMGroup *)arg1;
- (void)joinGroupRequestDidDecline:(NSString *)arg1 reason:(NSString *)arg2;
- (void)joinGroupRequestDidReceive:(EMGroup *)arg1 user:(NSString *)arg2 reason:(NSString *)arg3;
- (void)didLeaveGroup:(EMGroup *)arg1 reason:(int)arg2;
- (void)didJoinGroup:(EMGroup *)arg1 inviter:(NSString *)arg2 message:(NSString *)arg3;
- (void)groupInvitationDidDecline:(EMGroup *)arg1 invitee:(NSString *)arg2 reason:(NSString *)arg3;
- (void)groupInvitationDidAccept:(EMGroup *)arg1 invitee:(NSString *)arg2;
- (void)groupInvitationDidReceive:(NSString *)arg1 inviter:(NSString *)arg2 message:(NSString *)arg3;
@end

