//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "EMFileMessageBody.h"

@class NSString;

@interface EMImageMessageBody : EMFileMessageBody
{
    double _compressionRatio;
    NSString *_thumbnailLocalPath;
    shared_ptr_446457d5 _coreBody;
}

@property(nonatomic) shared_ptr_446457d5 coreBody; // @synthesize coreBody=_coreBody;
- (id).cxx_construct;
- (void).cxx_destruct;
- (shared_ptr_446457d5)getCoreBody;
- (id)initWithCoreBodyPtr:(shared_ptr_446457d5)arg1;
@property(nonatomic) int thumbnailDownloadStatus;
@property(nonatomic) long long thumbnailFileLength;
@property(nonatomic) struct CGSize thumbnailSize;
@property(copy, nonatomic) NSString *thumbnailSecretKey;
@property(copy, nonatomic) NSString *thumbnailRemotePath;
@property(copy, nonatomic) NSString *thumbnailLocalPath; // @synthesize thumbnailLocalPath=_thumbnailLocalPath;
@property(copy, nonatomic) NSString *thumbnailDisplayName;
@property(nonatomic) double compressionRatio;
@property(nonatomic) double compressRatio;
@property(nonatomic) struct CGSize size;
- (int)type;
- (id)initWithLocalPath:(id)arg1 displayName:(id)arg2;
- (id)initWithData:(id)arg1 thumbnailData:(id)arg2;

@end

