//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class EMMessageBody, NSDictionary, NSString;

@interface EMMessage : NSObject
{
    EMMessageBody *_body;
    shared_ptr_e84d5e87 _coreObject;
}

@property(nonatomic) shared_ptr_e84d5e87 coreObject; // @synthesize coreObject=_coreObject;
@property(retain, nonatomic) EMMessageBody *body; // @synthesize body=_body;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *ext;
@property(nonatomic) _Bool isRead;
@property(nonatomic) _Bool isDeliverAcked;
@property(nonatomic) _Bool isReadAcked;
@property(nonatomic) int status;
@property(nonatomic) int chatType;
@property(nonatomic) long long localTime;
@property(nonatomic) long long timestamp;
@property(copy, nonatomic) NSString *to;
@property(copy, nonatomic) NSString *from;
@property(nonatomic) int direction;
@property(copy, nonatomic) NSString *conversationId;
@property(copy, nonatomic) NSString *messageId;
- (id)initWithConversationID:(id)arg1 from:(id)arg2 to:(id)arg3 body:(id)arg4 ext:(id)arg5;
- (shared_ptr_e84d5e87)getCoreMessage;
- (id)initWithCoreMessage:(shared_ptr_e84d5e87)arg1;

@end

