//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIPageControl, UIScrollView;

@interface EmotionView : UIView
{
    UIPageControl *_pageControl;
    CDUnknownBlockType _emotionButtonBlock;
    CDUnknownBlockType _delbuttonBlock;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(copy, nonatomic) CDUnknownBlockType delbuttonBlock; // @synthesize delbuttonBlock=_delbuttonBlock;
@property(copy, nonatomic) CDUnknownBlockType emotionButtonBlock; // @synthesize emotionButtonBlock=_emotionButtonBlock;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
- (void).cxx_destruct;
- (void)emotionButtonClicked:(id)arg1;
- (void)delButtonClicked:(id)arg1;
- (id)delButton;
- (id)emotionButton:(long long)arg1;
- (void)initEmotions;
- (id)init;

@end

