//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FTInvestGroupDetailTrendingItem-Protocol.h"

@class NSString;

@interface FTInvestGroupDetailTrendingModel : NSObject <FTInvestGroupDetailTrendingItem>
{
    long long _index;
    double _rate;
    NSString *_date;
}

@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
@property(nonatomic) double rate; // @synthesize rate=_rate;
@property(nonatomic) long long index; // @synthesize index=_index;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

