//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FTPlateDataModel : NSObject
{
    NSString *_INNER_CODE;
    NSString *_IS_HK_CONNECT;
    NSString *_IS_MARGIN;
    NSString *_PROVINCE;
    NSString *_SECTION_CODE;
    NSString *_SECTION_NAME;
    NSString *_SW_INDU_CODE_2;
    NSString *_SW_INDU_NAME_2;
    NSString *_TRADE_MKT_REF;
}

@property(retain, nonatomic) NSString *TRADE_MKT_REF; // @synthesize TRADE_MKT_REF=_TRADE_MKT_REF;
@property(retain, nonatomic) NSString *SW_INDU_NAME_2; // @synthesize SW_INDU_NAME_2=_SW_INDU_NAME_2;
@property(retain, nonatomic) NSString *SW_INDU_CODE_2; // @synthesize SW_INDU_CODE_2=_SW_INDU_CODE_2;
@property(retain, nonatomic) NSString *SECTION_NAME; // @synthesize SECTION_NAME=_SECTION_NAME;
@property(retain, nonatomic) NSString *SECTION_CODE; // @synthesize SECTION_CODE=_SECTION_CODE;
@property(retain, nonatomic) NSString *PROVINCE; // @synthesize PROVINCE=_PROVINCE;
@property(retain, nonatomic) NSString *IS_MARGIN; // @synthesize IS_MARGIN=_IS_MARGIN;
@property(retain, nonatomic) NSString *IS_HK_CONNECT; // @synthesize IS_HK_CONNECT=_IS_HK_CONNECT;
@property(retain, nonatomic) NSString *INNER_CODE; // @synthesize INNER_CODE=_INNER_CODE;
- (void).cxx_destruct;

@end

