//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class HTTransparentView, JRJPopView, NSArray, UIColor, UIScrollView;
@protocol FTSegmentedControlDataSource;

@interface FTSegmentedControl : UIView
{
    _Bool _isLandscape;
    _Bool _isAutoAllFrameWidth;
    long long _selectedIndex;
    id <FTSegmentedControlDataSource> _dataSource;
    UIColor *_indicatorColor;
    long long _virtualIndex;
    long long _total_count;
    NSArray *_arr_segment_views;
    NSArray *_arr_segment_items_icons;
    UIView *_indicator;
    JRJPopView *_popView;
    HTTransparentView *_maskView;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) HTTransparentView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) JRJPopView *popView; // @synthesize popView=_popView;
@property(retain, nonatomic) UIView *indicator; // @synthesize indicator=_indicator;
@property(retain, nonatomic) NSArray *arr_segment_items_icons; // @synthesize arr_segment_items_icons=_arr_segment_items_icons;
@property(retain, nonatomic) NSArray *arr_segment_views; // @synthesize arr_segment_views=_arr_segment_views;
@property(nonatomic) _Bool isAutoAllFrameWidth; // @synthesize isAutoAllFrameWidth=_isAutoAllFrameWidth;
@property(nonatomic) long long total_count; // @synthesize total_count=_total_count;
@property(nonatomic) _Bool isLandscape; // @synthesize isLandscape=_isLandscape;
@property(nonatomic) long long virtualIndex; // @synthesize virtualIndex=_virtualIndex;
@property(retain, nonatomic) UIColor *indicatorColor; // @synthesize indicatorColor=_indicatorColor;
@property(nonatomic) __weak id <FTSegmentedControlDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
- (void).cxx_destruct;
- (long long)subMenuAtIndex;
- (void)dealloc;
- (void)removePopView;
- (double)segmentedItemWidth;
- (struct CGRect)indicatorFrame;
- (id)getSubMenuTitles:(long long)arg1;
- (struct CGRect)getSegmentItemFrameAtIndex:(long long)arg1;
- (id)segmentViewAtIndex:(long long)arg1;
- (void)switchIndicatorToIndex:(long long)arg1;
- (void)switchToIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)tapIndex:(long long)arg1;
- (int)getSubMenuShowByIndex:(long long)arg1;
- (void)didClickSegment:(id)arg1;
- (_Bool)haveSubMenuWithIndex:(long long)arg1;
- (id)arrow:(struct CGRect)arg1;
- (double)getItemWidth:(long long)arg1;
- (void)reloadSegmentedControl;
- (void)loadSegementedChildViews;
- (id)initWithFrame:(struct CGRect)arg1 dataSource:(id)arg2;

@end

