//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Mantle/MTLModel.h>

#import "MTLJSONSerializing-Protocol.h"

@class NSString;

@interface FTStockNotificationModel : MTLModel <MTLJSONSerializing>
{
    NSString *_notiId;
    NSString *_notiDate;
    NSString *_notiTitle;
    NSString *_stockCode;
    NSString *_stockName;
    NSString *_acceRoute;
    NSString *_readId;
    id _isBear;
}

+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) id isBear; // @synthesize isBear=_isBear;
@property(retain, nonatomic) NSString *readId; // @synthesize readId=_readId;
@property(retain, nonatomic) NSString *acceRoute; // @synthesize acceRoute=_acceRoute;
@property(retain, nonatomic) NSString *stockName; // @synthesize stockName=_stockName;
@property(retain, nonatomic) NSString *stockCode; // @synthesize stockCode=_stockCode;
@property(retain, nonatomic) NSString *notiTitle; // @synthesize notiTitle=_notiTitle;
@property(retain, nonatomic) NSString *notiDate; // @synthesize notiDate=_notiDate;
@property(retain, nonatomic) NSString *notiId; // @synthesize notiId=_notiId;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

