//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface FTStockAmazingTradeModel : NSObject
{
    NSString *_stockCode;
    NSString *_concludeTime;
    NSNumber *_commissionPrice;
    NSString *_durl;
    NSString *_stockName;
    NSString *_nickName;
    NSString *_wuserid;
    NSString *_headPic;
    NSNumber *_monthProfit;
    NSString *_commissionAmount;
    NSString *_commissionType;
    NSString *_passportId;
    NSNumber *_utype;
    NSArray *_tList;
}

+ (id)mj_objectClassInArray;
@property(retain, nonatomic) NSArray *tList; // @synthesize tList=_tList;
@property(retain, nonatomic) NSNumber *utype; // @synthesize utype=_utype;
@property(retain, nonatomic) NSString *passportId; // @synthesize passportId=_passportId;
@property(retain, nonatomic) NSString *commissionType; // @synthesize commissionType=_commissionType;
@property(retain, nonatomic) NSString *commissionAmount; // @synthesize commissionAmount=_commissionAmount;
@property(retain, nonatomic) NSNumber *monthProfit; // @synthesize monthProfit=_monthProfit;
@property(retain, nonatomic) NSString *headPic; // @synthesize headPic=_headPic;
@property(retain, nonatomic) NSString *wuserid; // @synthesize wuserid=_wuserid;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSString *stockName; // @synthesize stockName=_stockName;
@property(retain, nonatomic) NSString *durl; // @synthesize durl=_durl;
@property(retain, nonatomic) NSNumber *commissionPrice; // @synthesize commissionPrice=_commissionPrice;
@property(retain, nonatomic) NSString *concludeTime; // @synthesize concludeTime=_concludeTime;
@property(retain, nonatomic) NSString *stockCode; // @synthesize stockCode=_stockCode;
- (void).cxx_destruct;

@end

