//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FTBaseDrawView.h"

@class FTStockInfoDataManager, HTTransparentView, JRJPopView, NSArray, UIButton, UIImageView, UILabel, UIView;

@interface FTTimelineBarDrawView : FTBaseDrawView
{
    _Bool _isHiddenLine;
    _Bool _isShowRightVolValues;
    _Bool _showingCrossCursor;
    FTStockInfoDataManager *_dataSource;
    long long _timelineType;
    long long _selectedIndex;
    CDUnknownBlockType _enterLevel2;
    CDUnknownBlockType _changeTechTypeBlock;
    long long _stockType;
    NSArray *_titles;
    UILabel *_topLabel;
    UILabel *_middleLabel;
    UILabel *_bottomLabel;
    UILabel *_valueLabel;
    UIView *_normalTopView;
    UIView *_titleContainerView;
    UILabel *_titleLabel;
    UIImageView *_arrowView;
    UIImageView *_lv2ImgView;
    UIButton *_introduceBtn;
    UIView *_selectedIndexTopView;
    UILabel *_valueLabel1;
    UILabel *_valueLabel2;
    UILabel *_valueLabel3;
    UILabel *_valueLabel4;
    UIImageView *_level2View;
    HTTransparentView *_maskView;
    JRJPopView *_popView;
    double _leftWidth;
    double _rightWidth;
}

@property(nonatomic) double rightWidth; // @synthesize rightWidth=_rightWidth;
@property(nonatomic) double leftWidth; // @synthesize leftWidth=_leftWidth;
@property(retain, nonatomic) JRJPopView *popView; // @synthesize popView=_popView;
@property(retain, nonatomic) HTTransparentView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UIImageView *level2View; // @synthesize level2View=_level2View;
@property(retain, nonatomic) UILabel *valueLabel4; // @synthesize valueLabel4=_valueLabel4;
@property(retain, nonatomic) UILabel *valueLabel3; // @synthesize valueLabel3=_valueLabel3;
@property(retain, nonatomic) UILabel *valueLabel2; // @synthesize valueLabel2=_valueLabel2;
@property(retain, nonatomic) UILabel *valueLabel1; // @synthesize valueLabel1=_valueLabel1;
@property(retain, nonatomic) UIView *selectedIndexTopView; // @synthesize selectedIndexTopView=_selectedIndexTopView;
@property(retain, nonatomic) UIButton *introduceBtn; // @synthesize introduceBtn=_introduceBtn;
@property(retain, nonatomic) UIImageView *lv2ImgView; // @synthesize lv2ImgView=_lv2ImgView;
@property(retain, nonatomic) UIImageView *arrowView; // @synthesize arrowView=_arrowView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *titleContainerView; // @synthesize titleContainerView=_titleContainerView;
@property(retain, nonatomic) UIView *normalTopView; // @synthesize normalTopView=_normalTopView;
@property(retain, nonatomic) UILabel *valueLabel; // @synthesize valueLabel=_valueLabel;
@property(retain, nonatomic) UILabel *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(retain, nonatomic) UILabel *middleLabel; // @synthesize middleLabel=_middleLabel;
@property(retain, nonatomic) UILabel *topLabel; // @synthesize topLabel=_topLabel;
@property(retain, nonatomic) NSArray *titles; // @synthesize titles=_titles;
@property(nonatomic) _Bool showingCrossCursor; // @synthesize showingCrossCursor=_showingCrossCursor;
@property(nonatomic) long long stockType; // @synthesize stockType=_stockType;
@property(copy, nonatomic) CDUnknownBlockType changeTechTypeBlock; // @synthesize changeTechTypeBlock=_changeTechTypeBlock;
@property(copy, nonatomic) CDUnknownBlockType enterLevel2; // @synthesize enterLevel2=_enterLevel2;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) _Bool isShowRightVolValues; // @synthesize isShowRightVolValues=_isShowRightVolValues;
@property(nonatomic) _Bool isHiddenLine; // @synthesize isHiddenLine=_isHiddenLine;
@property(nonatomic) long long timelineType; // @synthesize timelineType=_timelineType;
- (id)dataSource;
- (void).cxx_destruct;
- (void)hiddenCrossCursor;
- (void)hiddenIndexList;
- (id)formatTimelineVolume:(double)arg1;
- (double)lineHeight;
- (double)drawHeight;
- (id)getContainer:(id)arg1;
- (void)setDataSource:(id)arg1;
- (void)drawFillColor;
- (void)drawL2AvgVolumeLine:(struct CGSize)arg1 dataSource:(id)arg2;
- (void)drawFiveDayTimelineVolume;
- (void)drawMainCapital;
- (void)drawCapitalGame;
- (void)drawDDX;
- (void)drawDayTimeLineVolume;
- (void)changeTechType;
- (void)drawDayTimeLine;
- (void)drawRect:(struct CGRect)arg1;
- (void)deSelectedIndex;
- (void)didSelectedIndex:(long long)arg1;
- (void)showIntroduceView;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)updateBtnInfoEx:(id)arg1;
- (void)updateBtnInfo;
- (void)showIndex;
- (void)addConstraints;
- (void)buildUI;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

