//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JRJTrendRedOrGreenView, NSArray, NSLayoutConstraint, UIImageView, UILabel;

@interface FTWonderfulHandleView : UIView
{
    int _lineCount;
    float _lineWidth;
    UILabel *_dateLabel;
    UIImageView *_questionImageView;
    JRJTrendRedOrGreenView *_trendDrawView;
    NSLayoutConstraint *_bottomLayout;
    NSArray *_trendListArr;
    UIView *_detailView;
    UIImageView *_trendImageView;
}

@property(nonatomic) __weak UIImageView *trendImageView; // @synthesize trendImageView=_trendImageView;
@property(nonatomic) __weak UIView *detailView; // @synthesize detailView=_detailView;
@property(nonatomic) float lineWidth; // @synthesize lineWidth=_lineWidth;
@property(nonatomic) int lineCount; // @synthesize lineCount=_lineCount;
@property(retain, nonatomic) NSArray *trendListArr; // @synthesize trendListArr=_trendListArr;
@property(nonatomic) __weak NSLayoutConstraint *bottomLayout; // @synthesize bottomLayout=_bottomLayout;
@property(nonatomic) __weak JRJTrendRedOrGreenView *trendDrawView; // @synthesize trendDrawView=_trendDrawView;
@property(nonatomic) __weak UIImageView *questionImageView; // @synthesize questionImageView=_questionImageView;
@property(nonatomic) __weak UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
- (void).cxx_destruct;
- (void)trendDetail:(id)arg1;
- (void)isLand;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;

@end

