//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IOBSUploadManager, NSFileHandle, NSMutableDictionary, NSString, NSTimer;

@interface HHTool : NSObject
{
    NSString *_callerNumber;
    NSString *_refreshUrl;
    NSString *_refreshToken;
    NSString *_refreshSystemId;
    NSString *_expiryDate;
    NSFileHandle *_writeHandle;
    NSFileHandle *_writeHandle2;
    IOBSUploadManager *_mgr;
    NSString *_todayZipDir;
    NSString *_token;
    NSString *_bucketName;
    NSMutableDictionary *_dictM;
    NSTimer *_categoryTimer;
    NSTimer *_refreshTimer;
    struct _opaque_pthread_rwlock_t _lock;
    struct _opaque_pthread_rwlock_t _lock2;
}

+ (id)shareTool;
@property(nonatomic) struct _opaque_pthread_rwlock_t lock2; // @synthesize lock2=_lock2;
@property(nonatomic) struct _opaque_pthread_rwlock_t lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSTimer *refreshTimer; // @synthesize refreshTimer=_refreshTimer;
@property(retain, nonatomic) NSTimer *categoryTimer; // @synthesize categoryTimer=_categoryTimer;
@property(retain, nonatomic) NSMutableDictionary *dictM; // @synthesize dictM=_dictM;
@property(copy, nonatomic) NSString *bucketName; // @synthesize bucketName=_bucketName;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(copy, nonatomic) NSString *todayZipDir; // @synthesize todayZipDir=_todayZipDir;
@property(retain, nonatomic) IOBSUploadManager *mgr; // @synthesize mgr=_mgr;
@property(retain, nonatomic) NSFileHandle *writeHandle2; // @synthesize writeHandle2=_writeHandle2;
@property(retain, nonatomic) NSFileHandle *writeHandle; // @synthesize writeHandle=_writeHandle;
- (void).cxx_destruct;
- (void)stopCategoryTimer;
- (void)category;
- (void)startCategoryTimer;
- (void)mgr:(id)arg1 uploadLogPath:(id)arg2;
- (void)uploadTodayZipLog;
- (void)uploadExpiredZipLog;
- (void)stopMonitorNetWork;
- (void)startMonitorNetWork:(CDUnknownBlockType)arg1;
- (id)googleReach;
- (void)deleteLog:(int)arg1;
- (void)deleteExpiredLog;
- (id)sha1:(id)arg1;
- (id)getExpiryDate;
- (id)encodeToPercentEscapeString:(id)arg1;
- (id)bundleDisplayName;
- (id)bundleName;
- (id)infoDict;
- (id)encryptWithKey:(id)arg1 content:(id)arg2;
- (void)authenticateWithURL:(id)arg1 userId:(id)arg2 appId:(id)arg3 success:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (void)postWithRequest:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)getRecordIdWithURL:(id)arg1 systemId:(id)arg2 callerNumber:(id)arg3 calleeNumber:(id)arg4 callID:(id)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
- (void)releaseCallerNumber:(id)arg1 url:(id)arg2 token:(id)arg3 systemId:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)refreshCallerNumber;
- (void)stopeRefresTimer;
- (void)startRefreshTimer;
- (void)getPhoneSipMsgWithURL:(id)arg1 token:(id)arg2 systemId:(id)arg3 refreshURL:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
- (void)putLicenseUse2Mcp:(id)arg1;
- (id)convertDict2Str:(id)arg1;
- (void)putRtcpReport2Mcp:(id)arg1 succeed:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)writeDict:(id)arg1 toFile:(id)arg2;
- (id)getTimeLong;
- (_Bool)isEnable3G;
- (_Bool)isEnableWIFI;
- (id)getNetworkType;
- (void)mgr:(id)arg1 putLogData2IobsWithToken:(id)arg2 bucket:(id)arg3 zipLogPath:(id)arg4 baseUrl:(id)arg5;
- (void)getIOBSTokenWithURL:(id)arg1 tokenKey:(id)arg2 systemId:(id)arg3 succeed:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
- (id)getZipLogPathWithLogPath:(id)arg1;
- (_Bool)isIPhoneX;
- (id)getDeviceName;
- (id)getIPAddressesInfo;
- (id)getIPAddress:(_Bool)arg1;
- (_Bool)judgeMicrophoneAuthority;
- (void)judgeMicrophoneAuthority:(CDUnknownBlockType)arg1;
- (_Bool)judgeCameraAuthority;
- (id)getTempFolder:(id)arg1;
- (id)getTempHHAudiosFolder;
- (id)getAudioFilePath;
- (id)getYYYYMMddHHmmssTime;
- (id)getDetailDateStr;
- (id)getLogPath2;
- (id)getLogPath;
- (void)writeLog2Txt2:(id)arg1;
- (void)writeLog2Txt:(id)arg1;
- (id)getTodayStr;
- (id)getTodayPath;
- (id)getUpLoadPath;
- (id)getRootPath;
- (void)setupMyLog;
- (id)initSingleton;

@end

