//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessageBuilder.h"

@class HqPackage;

@interface HqPackageBuilder : PBGeneratedMessageBuilder
{
    HqPackage *resultHqPackage;
}

@property(retain) HqPackage *resultHqPackage; // @synthesize resultHqPackage;
- (void).cxx_destruct;
- (id)clearIndustockrank;
- (id)mergeIndustockrank:(id)arg1;
- (id)setIndustockrankBuilder:(id)arg1;
- (id)setIndustockrank:(id)arg1;
- (id)industockrank;
- (_Bool)hasIndustockrank;
- (id)clearTurnoverrank;
- (id)mergeTurnoverrank:(id)arg1;
- (id)setTurnoverrankBuilder:(id)arg1;
- (id)setTurnoverrank:(id)arg1;
- (id)turnoverrank;
- (_Bool)hasTurnoverrank;
- (id)clearChangerank;
- (id)mergeChangerank:(id)arg1;
- (id)setChangerankBuilder:(id)arg1;
- (id)setChangerank:(id)arg1;
- (id)changerank;
- (_Bool)hasChangerank;
- (id)clearSliderank;
- (id)mergeSliderank:(id)arg1;
- (id)setSliderankBuilder:(id)arg1;
- (id)setSliderank:(id)arg1;
- (id)sliderank;
- (_Bool)hasSliderank;
- (id)clearIncrank;
- (id)mergeIncrank:(id)arg1;
- (id)setIncrankBuilder:(id)arg1;
- (id)setIncrank:(id)arg1;
- (id)incrank;
- (_Bool)hasIncrank;
- (id)clearZtdtPx;
- (id)mergeZtdtPx:(id)arg1;
- (id)setZtdtPxBuilder:(id)arg1;
- (id)setZtdtPx:(id)arg1;
- (id)ztdtPx;
- (_Bool)hasZtdtPx;
- (id)clearFundNetValueList;
- (id)mergeFundNetValueList:(id)arg1;
- (id)setFundNetValueListBuilder:(id)arg1;
- (id)setFundNetValueList:(id)arg1;
- (id)fundNetValueList;
- (_Bool)hasFundNetValueList;
- (id)clearRsiList;
- (id)mergeRsiList:(id)arg1;
- (id)setRsiListBuilder:(id)arg1;
- (id)setRsiList:(id)arg1;
- (id)rsiList;
- (_Bool)hasRsiList;
- (id)clearMacdList;
- (id)mergeMacdList:(id)arg1;
- (id)setMacdListBuilder:(id)arg1;
- (id)setMacdList:(id)arg1;
- (id)macdList;
- (_Bool)hasMacdList;
- (id)clearKdjList;
- (id)mergeKdjList:(id)arg1;
- (id)setKdjListBuilder:(id)arg1;
- (id)setKdjList:(id)arg1;
- (id)kdjList;
- (_Bool)hasKdjList;
- (id)clearBuyingAndSelling;
- (id)mergeBuyingAndSelling:(id)arg1;
- (id)setBuyingAndSellingBuilder:(id)arg1;
- (id)setBuyingAndSelling:(id)arg1;
- (id)buyingAndSelling;
- (_Bool)hasBuyingAndSelling;
- (id)clearTradeDetailList;
- (id)mergeTradeDetailList:(id)arg1;
- (id)setTradeDetailListBuilder:(id)arg1;
- (id)setTradeDetailList:(id)arg1;
- (id)tradeDetailList;
- (_Bool)hasTradeDetailList;
- (id)clearKlineList;
- (id)mergeKlineList:(id)arg1;
- (id)setKlineListBuilder:(id)arg1;
- (id)setKlineList:(id)arg1;
- (id)klineList;
- (_Bool)hasKlineList;
- (id)clearDayTimelineList;
- (id)mergeDayTimelineList:(id)arg1;
- (id)setDayTimelineListBuilder:(id)arg1;
- (id)setDayTimelineList:(id)arg1;
- (id)dayTimelineList;
- (_Bool)hasDayTimelineList;
- (id)clearDayTimeLine;
- (id)mergeDayTimeLine:(id)arg1;
- (id)setDayTimeLineBuilder:(id)arg1;
- (id)setDayTimeLine:(id)arg1;
- (id)dayTimeLine;
- (_Bool)hasDayTimeLine;
- (id)clearSnapshot;
- (id)mergeSnapshot:(id)arg1;
- (id)setSnapshotBuilder:(id)arg1;
- (id)setSnapshot:(id)arg1;
- (id)snapshot;
- (_Bool)hasSnapshot;
- (id)clearSecuritySyncList;
- (id)mergeSecuritySyncList:(id)arg1;
- (id)setSecuritySyncListBuilder:(id)arg1;
- (id)setSecuritySyncList:(id)arg1;
- (id)securitySyncList;
- (_Bool)hasSecuritySyncList;
- (id)clearSecuritySummaryList;
- (id)mergeSecuritySummaryList:(id)arg1;
- (id)setSecuritySummaryListBuilder:(id)arg1;
- (id)setSecuritySummaryList:(id)arg1;
- (id)securitySummaryList;
- (_Bool)hasSecuritySummaryList;
- (id)clearSecuritySummary;
- (id)mergeSecuritySummary:(id)arg1;
- (id)setSecuritySummaryBuilder:(id)arg1;
- (id)setSecuritySummary:(id)arg1;
- (id)securitySummary;
- (_Bool)hasSecuritySummary;
- (id)clearRankList;
- (id)mergeRankList:(id)arg1;
- (id)setRankListBuilder:(id)arg1;
- (id)setRankList:(id)arg1;
- (id)rankList;
- (_Bool)hasRankList;
- (id)clearMsg;
- (id)setMsg:(id)arg1;
- (id)msg;
- (_Bool)hasMsg;
- (id)clearRetCode;
- (id)setRetCode:(int)arg1;
- (int)retCode;
- (_Bool)hasRetCode;
- (id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (id)mergeFromCodedInputStream:(id)arg1;
- (id)mergeFrom:(id)arg1;
- (id)buildPartial;
- (id)build;
- (id)defaultInstance;
- (id)clone;
- (id)clear;
- (id)internalGetResult;
- (id)init;

@end

