//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabase, FMDatabaseQueue, NSString;

@interface HTSqliteManager : NSObject
{
    FMDatabase *_myFmdb;
    FMDatabaseQueue *_dbQueue;
    NSString *_sqlitePath;
}

+ (id)sharedManager;
@property(copy, nonatomic) NSString *sqlitePath; // @synthesize sqlitePath=_sqlitePath;
@property(retain, nonatomic) FMDatabaseQueue *dbQueue; // @synthesize dbQueue=_dbQueue;
@property(retain, nonatomic) FMDatabase *myFmdb; // @synthesize myFmdb=_myFmdb;
- (void).cxx_destruct;
- (id)createUserStockTable;
- (void)createTable;

@end

