//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseViewController.h"

#import "HTWebViewDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class HTWebProgressView, HTWebView, NSString, NSURL;

@interface HTWebViewController : JRJBaseViewController <HTWebViewDelegate, UIWebViewDelegate>
{
    long long errorCount;
    _Bool isLoadWebViewSuccess;
    NSURL *_url;
    HTWebView *_webView;
    HTWebProgressView *_progressView;
    NSString *_titleStr;
    unsigned long long _cachePolicy;
}

@property(nonatomic) unsigned long long cachePolicy; // @synthesize cachePolicy=_cachePolicy;
@property(copy, nonatomic) NSString *titleStr; // @synthesize titleStr=_titleStr;
@property(retain, nonatomic) HTWebProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) HTWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (void)responseHeaderData:(id)arg1 withHeaderData:(id)arg2 withstatusCode:(long long)arg3;
- (id)title;
- (void)loadUrl:(id)arg1;
- (id)mimeType:(id)arg1;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didReceiveDataPresent:(double)arg2;
- (id)addRequestHeader:(id)arg1;
- (void)refresh:(id)arg1;
- (void)loadListRequest;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

