//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class IALiveContainerModel, NSArray, NSDictionary;

@interface IAComplexModel : NSObject
{
    IALiveContainerModel *_live;
    IALiveContainerModel *_videoLive;
    NSArray *_loopimgs;
    NSArray *_menus;
    NSDictionary *_ques;
    NSArray *_tips;
    NSArray *_dynamics;
    NSArray *_hotStocks;
    NSArray *_advert;
    NSArray *_hot;
}

+ (id)mj_replacedKeyFromPropertyName;
+ (id)mj_objectClassInArray;
@property(retain, nonatomic) NSArray *hot; // @synthesize hot=_hot;
@property(retain, nonatomic) NSArray *advert; // @synthesize advert=_advert;
@property(retain, nonatomic) NSArray *hotStocks; // @synthesize hotStocks=_hotStocks;
@property(retain, nonatomic) NSArray *dynamics; // @synthesize dynamics=_dynamics;
@property(retain, nonatomic) NSArray *tips; // @synthesize tips=_tips;
@property(retain, nonatomic) NSDictionary *ques; // @synthesize ques=_ques;
@property(copy, nonatomic) NSArray *menus; // @synthesize menus=_menus;
@property(copy, nonatomic) NSArray *loopimgs; // @synthesize loopimgs=_loopimgs;
@property(retain, nonatomic) IALiveContainerModel *videoLive; // @synthesize videoLive=_videoLive;
@property(retain, nonatomic) IALiveContainerModel *live; // @synthesize live=_live;
- (void).cxx_destruct;

@end

