//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IAEvaluationDetailModel : NSObject
{
    NSString *_adviserId;
    NSString *_adviserName;
    NSString *_headImage;
    NSString *_content;
    long long _fwPoints;
    long long _tzPoints;
    long long _xyPoints;
}

@property(nonatomic) long long xyPoints; // @synthesize xyPoints=_xyPoints;
@property(nonatomic) long long tzPoints; // @synthesize tzPoints=_tzPoints;
@property(nonatomic) long long fwPoints; // @synthesize fwPoints=_fwPoints;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *headImage; // @synthesize headImage=_headImage;
@property(copy, nonatomic) NSString *adviserName; // @synthesize adviserName=_adviserName;
@property(copy, nonatomic) NSString *adviserId; // @synthesize adviserId=_adviserId;
- (void).cxx_destruct;

@end

