//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer;

@interface IAHomeZhiboRecBubbleView : UIView
{
    double _radius;
    CAShapeLayer *_bubbleLayer;
}

@property(retain, nonatomic) CAShapeLayer *bubbleLayer; // @synthesize bubbleLayer=_bubbleLayer;
@property(nonatomic) double radius; // @synthesize radius=_radius;
- (void).cxx_destruct;
- (id)p_bubblePath;
- (void)layoutSubviews;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

