//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJListTableViewController.h"

#import "YZStockInfoCenterCellDelegate-Protocol.h"

@class NSString, StockIndexRankRequest, StockInfoMainFooterView;

@interface IndexChengFenController : JRJListTableViewController <YZStockInfoCenterCellDelegate>
{
    StockInfoMainFooterView *requestStatusView;
    NSString *stockCode;
    long long _funType;
    StockIndexRankRequest *_indexRankRequest;
}

@property(retain, nonatomic) StockIndexRankRequest *indexRankRequest; // @synthesize indexRankRequest=_indexRankRequest;
@property(nonatomic) long long funType; // @synthesize funType=_funType;
@property(copy, nonatomic) NSString *stockCode; // @synthesize stockCode;
- (void).cxx_destruct;
- (void)addPushStockTrack;
- (void)addLoadMoreTrack;
- (void)StockLoadMoreAction;
- (void)addRequestStatusWithHeight:(double)arg1 withShowType:(int)arg2;
- (int)getLoadMoreSortType;
- (long long)getRequestTypeByFunType:(long long)arg1;
- (void)refreshIndexRankView;
- (void)fetchStockIndexRankList:(long long)arg1;
- (void)requestDataWithStart:(_Bool)arg1;
- (void)scrollsToTop;
- (double)heightForCenterCell;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)handleRequestDataArray:(id)arg1;
- (void)requestMoreListData;
- (void)loadListRequest;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

