//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

#import "GeneratedMessageProtocol-Protocol.h"
#import "JRJStockModelProtocol-Protocol.h"

@class NSString;

@interface InduSummary : PBGeneratedMessage <JRJStockModelProtocol, GeneratedMessageProtocol>
{
    unsigned int hasIndupxChgRadio_:1;
    unsigned int hasLastPx_:1;
    unsigned int hasPxChgRadio_:1;
    unsigned int hasInduCode_:1;
    unsigned int hasInduName_:1;
    unsigned int hasSecurityCode_:1;
    unsigned int hasSecurityName_:1;
    unsigned int hasMarketType_:1;
    unsigned int hasSecurityType_:1;
    float indupxChgRadio;
    float lastPx;
    float pxChgRadio;
    NSString *induCode;
    NSString *induName;
    NSString *securityCode;
    NSString *securityName;
    int marketType;
    int securityType;
}

+ (id)builderWithPrototype:(id)arg1;
+ (id)builder;
+ (id)parseFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromCodedInputStream:(id)arg1;
+ (id)parseFromInputStream:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromInputStream:(id)arg1;
+ (id)parseFromData:(id)arg1 extensionRegistry:(id)arg2;
+ (id)parseFromData:(id)arg1;
+ (id)defaultInstance;
+ (void)initialize;
@property int securityType; // @synthesize securityType;
@property float pxChgRadio; // @synthesize pxChgRadio;
@property float lastPx; // @synthesize lastPx;
@property(retain) NSString *securityName; // @synthesize securityName;
@property(retain) NSString *securityCode; // @synthesize securityCode;
@property float indupxChgRadio; // @synthesize indupxChgRadio;
@property int marketType; // @synthesize marketType;
@property(retain) NSString *induName; // @synthesize induName;
@property(retain) NSString *induCode; // @synthesize induCode;
- (void).cxx_destruct;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (void)storeInDictionary:(id)arg1;
- (void)writeDescriptionTo:(id)arg1 withIndent:(id)arg2;
- (id)toBuilder;
- (id)builder;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (_Bool)isInitialized;
- (id)defaultInstance;
- (id)init;
- (void)setHasSecurityType:(_Bool)arg1;
- (_Bool)hasSecurityType;
- (void)setHasPxChgRadio:(_Bool)arg1;
- (_Bool)hasPxChgRadio;
- (void)setHasLastPx:(_Bool)arg1;
- (_Bool)hasLastPx;
- (void)setHasSecurityName:(_Bool)arg1;
- (_Bool)hasSecurityName;
- (void)setHasSecurityCode:(_Bool)arg1;
- (_Bool)hasSecurityCode;
- (void)setHasIndupxChgRadio:(_Bool)arg1;
- (_Bool)hasIndupxChgRadio;
- (void)setHasMarketType:(_Bool)arg1;
- (_Bool)hasMarketType;
- (void)setHasInduName:(_Bool)arg1;
- (_Bool)hasInduName;
- (void)setHasInduCode:(_Bool)arg1;
- (_Bool)hasInduCode;
- (_Bool)isIndex;
- (long long)stock_typeConvertNumber;
- (id)stock_formatLatestPrice;
- (_Bool)stock_isStock;
- (_Bool)stock_isTradingStatusPrice;
- (id)stock_totalValue;
- (id)stock_changeValue;
- (_Bool)stock_isTradingHalt;
- (id)stock_amplitude;
- (id)stock_turnoverRatio;
- (id)stock_changeRatio;
- (id)stock_change;
- (id)stock_highestPrice;
- (id)stock_lowestPrice;
- (id)stock_price;
- (id)stock_stockName;
- (id)stock_stockCode;
- (id)stock_industryChangeRatio;
- (id)stock_industryName;
- (id)stock_industryCode;
- (id)stock_market;
- (id)stock_id;
- (long long)stock_type;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

