//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessageBuilder.h"

@class InduSummary;

@interface InduSummaryBuilder : PBGeneratedMessageBuilder
{
    InduSummary *resultInduSummary;
}

@property(retain) InduSummary *resultInduSummary; // @synthesize resultInduSummary;
- (void).cxx_destruct;
- (id)clearSecurityType;
- (id)setSecurityType:(int)arg1;
- (int)securityType;
- (_Bool)hasSecurityType;
- (id)clearPxChgRadio;
- (id)setPxChgRadio:(float)arg1;
- (float)pxChgRadio;
- (_Bool)hasPxChgRadio;
- (id)clearLastPx;
- (id)setLastPx:(float)arg1;
- (float)lastPx;
- (_Bool)hasLastPx;
- (id)clearSecurityName;
- (id)setSecurityName:(id)arg1;
- (id)securityName;
- (_Bool)hasSecurityName;
- (id)clearSecurityCode;
- (id)setSecurityCode:(id)arg1;
- (id)securityCode;
- (_Bool)hasSecurityCode;
- (id)clearIndupxChgRadio;
- (id)setIndupxChgRadio:(float)arg1;
- (float)indupxChgRadio;
- (_Bool)hasIndupxChgRadio;
- (id)clearMarketType;
- (id)setMarketType:(int)arg1;
- (int)marketType;
- (_Bool)hasMarketType;
- (id)clearInduName;
- (id)setInduName:(id)arg1;
- (id)induName;
- (_Bool)hasInduName;
- (id)clearInduCode;
- (id)setInduCode:(id)arg1;
- (id)induCode;
- (_Bool)hasInduCode;
- (id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (id)mergeFromCodedInputStream:(id)arg1;
- (id)mergeFrom:(id)arg1;
- (id)buildPartial;
- (id)build;
- (id)defaultInstance;
- (id)clone;
- (id)clear;
- (id)internalGetResult;
- (id)init;

@end

