//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary;

@interface InterPreferenceModel : NSObject
{
    long long _totalCount;
    long long _hasNext;
    NSDictionary *_labels;
    NSArray *_list;
}

+ (id)mj_objectClassInArray;
@property(copy, nonatomic) NSArray *list; // @synthesize list=_list;
@property(copy, nonatomic) NSDictionary *labels; // @synthesize labels=_labels;
@property(nonatomic) long long hasNext; // @synthesize hasNext=_hasNext;
@property(nonatomic) long long totalCount; // @synthesize totalCount=_totalCount;
- (void).cxx_destruct;

@end

