//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseViewController.h"

#import "UITextViewDelegate-Protocol.h"

@class BottomSendView, MCPlaceHolderTextView, NSString;

@interface IntroductionViewController : JRJBaseViewController <UITextViewDelegate>
{
    MCPlaceHolderTextView *_txtContent;
    BottomSendView *_bottomSendView;
    float keyBoardHeight;
    double keyBoardDuration;
    CDUnknownBlockType _introductionBlock;
    NSString *_introDuction;
}

@property(copy, nonatomic) NSString *introDuction; // @synthesize introDuction=_introDuction;
@property(copy, nonatomic) CDUnknownBlockType introductionBlock; // @synthesize introductionBlock=_introductionBlock;
- (void).cxx_destruct;
- (id)title;
- (void)viewWillDisappear:(_Bool)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

