//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KKTableViewBaseCell.h"

@class NSArray, UIImageView, UILabel;

@interface InvestAdviserHomePromotionTextCell : KKTableViewBaseCell
{
    UIImageView *_iconImageView;
    UILabel *_textLabel1;
    UILabel *_textLabel2;
    NSArray *_items;
}

+ (double)cellHeight;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) UILabel *textLabel2; // @synthesize textLabel2=_textLabel2;
@property(retain, nonatomic) UILabel *textLabel1; // @synthesize textLabel1=_textLabel1;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void).cxx_destruct;
- (void)updateCellWithSource:(id)arg1;
- (void)textLabel2Tapped;
- (void)textLabel1Tapped;
- (void)updateTextLabel:(id)arg1 withItem:(id)arg2;
- (void)didTapLabel:(id)arg1;
- (id)textLabelWithSelector:(SEL)arg1;
- (void)commonInit;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

