//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseViewController.h"

@class IARecommendViewController, InvestAdviserHandler, NSString, UIButton, UISegmentedControl, UIView, UIViewController, _TtC16JRJInvestAdviser21IAFocusViewController;

@interface InvestAdviserViewController : JRJBaseViewController
{
    UISegmentedControl *_segmentedControl;
    UIButton *_userHomeBtn;
    IARecommendViewController *_recommendVC;
    _TtC16JRJInvestAdviser21IAFocusViewController *_focusVC;
    UIViewController *_currentVC;
    UIView *_redMsgView;
    InvestAdviserHandler *_handler;
    NSString *_lastUpdate;
}

@property(copy, nonatomic) NSString *lastUpdate; // @synthesize lastUpdate=_lastUpdate;
@property(retain, nonatomic) InvestAdviserHandler *handler; // @synthesize handler=_handler;
@property(retain, nonatomic) UIView *redMsgView; // @synthesize redMsgView=_redMsgView;
@property(retain, nonatomic) UIViewController *currentVC; // @synthesize currentVC=_currentVC;
@property(retain, nonatomic) _TtC16JRJInvestAdviser21IAFocusViewController *focusVC; // @synthesize focusVC=_focusVC;
@property(retain, nonatomic) IARecommendViewController *recommendVC; // @synthesize recommendVC=_recommendVC;
- (void).cxx_destruct;
- (void)scrollToJingXuanGuanDian;
- (void)handleFocusNewMessage:(_Bool)arg1;
- (void)requestFocusNewMessage;
- (void)setNavigationItem;
- (void)updateHeaderImage:(id)arg1;
- (void)addNotification;
- (void)segmentAction:(id)arg1;
- (void)addSegmentController;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (void)dealloc;

@end

