//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseHandler.h"

@interface InvestGroupHandler : BaseHandler
{
}

+ (id)sharedHandler;
- (void)cancelSubscribedInvestGroup:(long long)arg1 block:(CDUnknownBlockType)arg2;
- (void)subscribedInvestGroup:(long long)arg1 userId:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)subscribedInvestGroupList:(CDUnknownBlockType)arg1;
- (void)parseRequestResponse:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)cancelFollowInvestGroup:(long long)arg1 block:(CDUnknownBlockType)arg2;
- (void)followInvestGroup:(long long)arg1 block:(CDUnknownBlockType)arg2;
- (id)queryInvestGroupListForUserId:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)collectionSubscribeInvestGroupWithType:(int)arg1 block:(CDUnknownBlockType)arg2;
- (id)collectionSubscribeInvestGroupWithType:(int)arg1 block:(CDUnknownBlockType)arg2 pageIndex:(int)arg3 pageSize:(int)arg4;
- (void)investGroupDetail:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)investGroupDetailTrending:(id)arg1 type:(long long)arg2 block:(CDUnknownBlockType)arg3;
- (void)commitAdjustInvestGroupReason:(id)arg1 commissionId:(id)arg2 context:(id)arg3 block:(CDUnknownBlockType)arg4;
- (id)adjustInvestGroup:(id)arg1 pageNumber:(int)arg2 pageSize:(int)arg3 block:(CDUnknownBlockType)arg4;
- (id)queryInvestGroupPositionInfo:(id)arg1 pageNumber:(int)arg2 pageSize:(int)arg3 block:(CDUnknownBlockType)arg4;
- (id)queryInvestGroupInfo:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)updateInvestGroup:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)deleteInvestGroup:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)createInvestGroup:(id)arg1 block:(CDUnknownBlockType)arg2;
- (id)queryInvestGroupList:(CDUnknownBlockType)arg1;
- (id)arrayWithInvestGroup:(id)arg1;

@end

