//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface InvesterAdviserModel : NSObject
{
    _Bool _onLive;
    _Bool _onVideo;
    NSString *_intro;
    NSString *_userId;
    NSString *_userName;
    long long _fansNum;
    long long _pvNum;
    long long _rankOrder;
    NSString *_headImage;
    NSString *_label;
    long long _isAdviser;
    long long _type;
    NSString *_sorts;
    NSString *_typeDesc;
}

@property(copy, nonatomic) NSString *typeDesc; // @synthesize typeDesc=_typeDesc;
@property(copy, nonatomic) NSString *sorts; // @synthesize sorts=_sorts;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long isAdviser; // @synthesize isAdviser=_isAdviser;
@property(copy, nonatomic) NSString *label; // @synthesize label=_label;
@property(copy, nonatomic) NSString *headImage; // @synthesize headImage=_headImage;
@property(nonatomic) _Bool onVideo; // @synthesize onVideo=_onVideo;
@property(nonatomic) _Bool onLive; // @synthesize onLive=_onLive;
@property(nonatomic) long long rankOrder; // @synthesize rankOrder=_rankOrder;
@property(nonatomic) long long pvNum; // @synthesize pvNum=_pvNum;
@property(nonatomic) long long fansNum; // @synthesize fansNum=_fansNum;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *intro; // @synthesize intro=_intro;
- (void).cxx_destruct;

@end

