//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UILabel;

@interface JDStatusBarView : UIView
{
    double _textVerticalPositionAdjustment;
    CDUnknownBlockType _toucheBlock;
    UILabel *_textLabel;
    UIActivityIndicatorView *_activityIndicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(copy, nonatomic) CDUnknownBlockType toucheBlock; // @synthesize toucheBlock=_toucheBlock;
@property(nonatomic) double textVerticalPositionAdjustment; // @synthesize textVerticalPositionAdjustment=_textVerticalPositionAdjustment;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (struct CGSize)currentTextSize;
- (void)layoutSubviews;

@end

