//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface JRJAnswerIconTableViewCell : JRJTableViewCell
{
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    UIView *_topBorder;
    UIView *_bottomBorder;
    UIImageView *_disclosureIndicator;
}

+ (double)cellHeight;
@property(nonatomic) __weak UIImageView *disclosureIndicator; // @synthesize disclosureIndicator=_disclosureIndicator;
@property(nonatomic) __weak UIView *bottomBorder; // @synthesize bottomBorder=_bottomBorder;
@property(nonatomic) __weak UIView *topBorder; // @synthesize topBorder=_topBorder;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void).cxx_destruct;
- (void)updateCellWithSource:(id)arg1;
- (void)awakeFromNib;

@end

