//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KKTableViewController.h"

@class JRJAdviserAnswerHandler, JRJAnswerCell2, NSString;

@interface JRJAdviserQuestionsViewController : KKTableViewController
{
    long long _adiviserAnswerType;
    NSString *_userId;
    JRJAdviserAnswerHandler *_handler;
    JRJAnswerCell2 *_answerCell2;
}

@property(retain, nonatomic) JRJAnswerCell2 *answerCell2; // @synthesize answerCell2=_answerCell2;
@property(retain, nonatomic) JRJAdviserAnswerHandler *handler; // @synthesize handler=_handler;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(nonatomic) long long adiviserAnswerType; // @synthesize adiviserAnswerType=_adiviserAnswerType;
- (void).cxx_destruct;
- (void)followUser:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)restartRequestWhenNetworkErrorOccurred;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)delayLoadMore;
- (void)showDetail:(id)arg1;
- (void)didClickedDetailAnswer:(id)arg1;
- (void)doTrack;
- (void)reloadDataSource;
- (void)loadListRequest;
- (void)followStateChanged:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;

@end

