//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UITextField;

@interface JRJAskSearchStockView : UIView
{
    CDUnknownBlockType _tapBlock;
    CDUnknownBlockType _deleteBlock;
    UITextField *_textField;
    UIButton *_deleteButton;
}

@property(nonatomic) __weak UIButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(nonatomic) __weak UITextField *textField; // @synthesize textField=_textField;
@property(copy, nonatomic) CDUnknownBlockType deleteBlock; // @synthesize deleteBlock=_deleteBlock;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
- (void).cxx_destruct;
- (void)deleteButtonPressed:(id)arg1;
- (void)buttonPressed:(id)arg1;
@property(retain, nonatomic) NSString *text;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

