//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BCBrowserViewController.h"

#import "BCBrowserViewControllerDelegate-Protocol.h"

@class NSString, UIProgressView, UIView;

@interface JRJBCBrowserViewController : BCBrowserViewController <BCBrowserViewControllerDelegate>
{
    UIView *_bcWebView;
    UIProgressView *_bcProgressView;
    UIView *_toolbarView;
}

@property(retain, nonatomic) UIView *toolbarView; // @synthesize toolbarView=_toolbarView;
@property(retain, nonatomic) UIProgressView *bcProgressView; // @synthesize bcProgressView=_bcProgressView;
@property(retain, nonatomic) UIView *bcWebView; // @synthesize bcWebView=_bcWebView;
- (void).cxx_destruct;
- (void)bcBrowserViewShareButtonClick:(id)arg1;
- (void)bcBrowserViewBackButtonClick:(id)arg1;
- (void)p_remakeLayout;
- (void)setAdData:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

