//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class JRJCourse, UILabel;

@interface JRJCourseHomeIntroductionCell : JRJTableViewCell
{
    JRJCourse *_course;
    UILabel *_videoNumLabel;
    UILabel *_numLabel;
    UILabel *_riskTypeLabel;
}

@property(nonatomic) __weak UILabel *riskTypeLabel; // @synthesize riskTypeLabel=_riskTypeLabel;
@property(nonatomic) __weak UILabel *numLabel; // @synthesize numLabel=_numLabel;
@property(nonatomic) __weak UILabel *videoNumLabel; // @synthesize videoNumLabel=_videoNumLabel;
@property(retain, nonatomic) JRJCourse *course; // @synthesize course=_course;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

