//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseHandler.h"

@class NSIndexPath, NSString;

@interface JRJCommentHandler : BaseHandler
{
    NSString *_itemTitle;
    long long _pageIndex;
    long long _totlaPages;
    long long _commentType;
    NSIndexPath *_replyIndexPath;
    long long _totlaCount;
    long long _bizType;
    long long _timeID;
}

@property(nonatomic) long long timeID; // @synthesize timeID=_timeID;
@property(nonatomic) long long bizType; // @synthesize bizType=_bizType;
@property(nonatomic) long long totlaCount; // @synthesize totlaCount=_totlaCount;
@property(retain, nonatomic) NSIndexPath *replyIndexPath; // @synthesize replyIndexPath=_replyIndexPath;
@property(nonatomic) long long commentType; // @synthesize commentType=_commentType;
@property(nonatomic) long long totlaPages; // @synthesize totlaPages=_totlaPages;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(copy, nonatomic) NSString *itemTitle; // @synthesize itemTitle=_itemTitle;
- (void).cxx_destruct;
- (id)handleResponseData:(id)arg1;
- (id)responseObjectForResponse:(id)arg1 responseObject:(id)arg2 error:(id *)arg3;
- (void)praiseCommentWithRootId:(id)arg1 commentId:(id)arg2 likeType:(id)arg3 block:(CDUnknownBlockType)arg4;
- (void)deleteComment:(id)arg1 appItemId:(id)arg2 rootId:(id)arg3 commentId:(id)arg4 block:(CDUnknownBlockType)arg5;
- (void)addComment:(id)arg1 andBizType:(id)arg2 appItemId:(id)arg3 block:(CDUnknownBlockType)arg4;
- (void)fetchCommentList:(id)arg1 appItemId:(id)arg2 block:(CDUnknownBlockType)arg3;

@end

