//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJCommentTableViewController.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class JRJCourse, NSString, UIView;

@interface JRJCourseCommentViewController : JRJCommentTableViewController <UIGestureRecognizerDelegate>
{
    JRJCourse *_course;
    NSString *_URLString;
    UIView *_emptyView;
    UIView *_lockView;
}

@property(retain, nonatomic) UIView *lockView; // @synthesize lockView=_lockView;
@property(retain, nonatomic) UIView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) NSString *URLString; // @synthesize URLString=_URLString;
@property(retain, nonatomic) JRJCourse *course; // @synthesize course=_course;
- (void).cxx_destruct;
- (void)scrollToFirstComment;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)removeNSNotification;
- (void)doPraiseComment;
- (void)beginEditing;
- (void)p_showEmptyView:(_Bool)arg1;
- (void)showLoadingViewWithState:(long long)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

