//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseWebViewController.h"

@interface JRJCustomNavigationBarWebViewController : BaseWebViewController
{
}

- (id)leftNavigationImageStr;
- (id)closeBarButtonItem;
- (void)setLeftNavigationItemBarButton;
- (long long)preferredStatusBarStyle;
- (void)setVCTitle:(id)arg1;
- (void)updateNavStyleToPortfolioDetail:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)viewDidLoad;

@end

