//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JRJCourse, UIButton, UILabel;

@interface JRJCourseBottomView : UIView
{
    JRJCourse *_course;
    CDUnknownBlockType _buyBlock;
    CDUnknownBlockType _startLearningBlock;
    CDUnknownBlockType _stopLearningBlock;
    CDUnknownBlockType _sendMessageBlock;
    UIView *_purchaseView;
    UILabel *_symbolLabel;
    UILabel *_priceLabel;
    UILabel *_freeLabel;
    UIButton *_purchaseButton;
    UIView *_messageView;
    UIView *_purchaseBackgroundView;
    UILabel *_qiLabel;
}

@property(retain, nonatomic) UILabel *qiLabel; // @synthesize qiLabel=_qiLabel;
@property(retain, nonatomic) UIView *purchaseBackgroundView; // @synthesize purchaseBackgroundView=_purchaseBackgroundView;
@property(retain, nonatomic) UIView *messageView; // @synthesize messageView=_messageView;
@property(retain, nonatomic) UIButton *purchaseButton; // @synthesize purchaseButton=_purchaseButton;
@property(retain, nonatomic) UILabel *freeLabel; // @synthesize freeLabel=_freeLabel;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) UILabel *symbolLabel; // @synthesize symbolLabel=_symbolLabel;
@property(retain, nonatomic) UIView *purchaseView; // @synthesize purchaseView=_purchaseView;
@property(copy, nonatomic) CDUnknownBlockType sendMessageBlock; // @synthesize sendMessageBlock=_sendMessageBlock;
@property(copy, nonatomic) CDUnknownBlockType stopLearningBlock; // @synthesize stopLearningBlock=_stopLearningBlock;
@property(copy, nonatomic) CDUnknownBlockType startLearningBlock; // @synthesize startLearningBlock=_startLearningBlock;
@property(copy, nonatomic) CDUnknownBlockType buyBlock; // @synthesize buyBlock=_buyBlock;
@property(retain, nonatomic) JRJCourse *course; // @synthesize course=_course;
- (void).cxx_destruct;
- (void)messageButtonTapped:(id)arg1;
- (void)purchaseButtonTapped:(id)arg1;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

