//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseTableViewController.h"

@class JRJNoStockView, NSMutableArray, NSString, UIBarButtonItem, UIButton, UIView;

@interface JRJCustomMadeViewController : JRJBaseTableViewController
{
    _Bool _isManualRrefresh;
    _Bool _loading;
    _Bool _hasData;
    JRJNoStockView *_noStockView;
    UIButton *_smartStareButton;
    UIView *_headerView;
    NSString *_beginDate;
    NSMutableArray *_dataArray;
    NSMutableArray *_totalArray;
    NSString *_lastStockCode;
    UIBarButtonItem *_rightButton;
    long long _status;
}

@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) UIBarButtonItem *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) NSString *lastStockCode; // @synthesize lastStockCode=_lastStockCode;
@property(nonatomic) _Bool hasData; // @synthesize hasData=_hasData;
@property(nonatomic, getter=isLoading) _Bool loading; // @synthesize loading=_loading;
@property(nonatomic) _Bool isManualRrefresh; // @synthesize isManualRrefresh=_isManualRrefresh;
@property(retain, nonatomic) NSMutableArray *totalArray; // @synthesize totalArray=_totalArray;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) NSString *beginDate; // @synthesize beginDate=_beginDate;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIButton *smartStareButton; // @synthesize smartStareButton=_smartStareButton;
@property(retain, nonatomic) JRJNoStockView *noStockView; // @synthesize noStockView=_noStockView;
- (void).cxx_destruct;
- (void)layoutSubviewsPage;
- (void)dingPanAction;
- (void)updateSubviewsContrainter;
- (void)_setupSubviewsUI;
- (void)startStockSearchViewController;
- (void)resetTableViewHeight:(float)arg1;
- (void)showLoadingViewWithState:(long long)arg1;
- (void)didPressedSmartStareButton;
- (void)openDingPan;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)synchronizeActiveSu:(id)arg1;
- (void)userLoginOut;
- (void)userLoginSuccess:(id)arg1;
- (void)analyDataWithDic:(id)arg1;
- (void)fetchDate;
- (void)showMainDecision;
- (void)refreshData;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

