//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class JRJCapitalFlowPieChartViewLeve2, JRJFundFlowModel, UILabel, UIView;

@interface JRJCapitalFlowLevel2Cell : JRJTableViewCell
{
    JRJCapitalFlowPieChartViewLeve2 *_chartBarView;
    JRJFundFlowModel *_todayFundFlowModel;
    UILabel *_sellHugeLabel;
    UILabel *_sellBigLabel;
    UILabel *_sellMidLabel;
    UILabel *_sellSmallLabel;
    UILabel *_buyHugeLabel;
    UILabel *_buyBigLabel;
    UILabel *_buyMidLabel;
    UILabel *_buySmallLabel;
    UILabel *_fundFlowLabel;
    UIView *_leftView;
    UIView *_rightView;
}

+ (double)cellHeight;
@property(nonatomic) __weak UIView *rightView; // @synthesize rightView=_rightView;
@property(nonatomic) __weak UIView *leftView; // @synthesize leftView=_leftView;
@property(nonatomic) __weak UILabel *fundFlowLabel; // @synthesize fundFlowLabel=_fundFlowLabel;
@property(nonatomic) __weak UILabel *buySmallLabel; // @synthesize buySmallLabel=_buySmallLabel;
@property(nonatomic) __weak UILabel *buyMidLabel; // @synthesize buyMidLabel=_buyMidLabel;
@property(nonatomic) __weak UILabel *buyBigLabel; // @synthesize buyBigLabel=_buyBigLabel;
@property(nonatomic) __weak UILabel *buyHugeLabel; // @synthesize buyHugeLabel=_buyHugeLabel;
@property(nonatomic) __weak UILabel *sellSmallLabel; // @synthesize sellSmallLabel=_sellSmallLabel;
@property(nonatomic) __weak UILabel *sellMidLabel; // @synthesize sellMidLabel=_sellMidLabel;
@property(nonatomic) __weak UILabel *sellBigLabel; // @synthesize sellBigLabel=_sellBigLabel;
@property(nonatomic) __weak UILabel *sellHugeLabel; // @synthesize sellHugeLabel=_sellHugeLabel;
@property(retain, nonatomic) JRJFundFlowModel *todayFundFlowModel; // @synthesize todayFundFlowModel=_todayFundFlowModel;
@property(nonatomic) __weak JRJCapitalFlowPieChartViewLeve2 *chartBarView; // @synthesize chartBarView=_chartBarView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

