//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseHeaderFooterView.h"

@class NSLayoutConstraint, UILabel;

@interface JRJCommentSectionHeaderView : BaseHeaderFooterView
{
    UILabel *commentNumLabel;
    NSLayoutConstraint *_topGrayViewHeight;
}

@property(nonatomic) __weak NSLayoutConstraint *topGrayViewHeight; // @synthesize topGrayViewHeight=_topGrayViewHeight;
- (void).cxx_destruct;
- (void)setCommentNumStr:(id)arg1;

@end

