//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface JRJDiagnosisSignalDetailView : UIView
{
    NSArray *_dataArray;
}

@property(retain, nonatomic) NSArray *dataArray; // @synthesize dataArray=_dataArray;
- (void).cxx_destruct;
- (id)getBoxImageName:(id)arg1 index:(int)arg2;
- (id)getPointImageName:(int)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateWithData:(id)arg1;
- (id)getBoxImage:(id)arg1 index:(int)arg2;
- (void)buildTitleLabelWithArr:(id)arg1;
- (void)buildTimeLabelWithArr:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

