//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, UIView;

@interface JRJDotPopUpCell : UITableViewCell
{
    UILabel *_lblDateTime;
    UILabel *_lblKeyName;
    UILabel *_lblOther;
    UIView *_repeatView;
}

@property(retain, nonatomic) UIView *repeatView; // @synthesize repeatView=_repeatView;
@property(retain, nonatomic) UILabel *lblOther; // @synthesize lblOther=_lblOther;
@property(retain, nonatomic) UILabel *lblKeyName; // @synthesize lblKeyName=_lblKeyName;
@property(retain, nonatomic) UILabel *lblDateTime; // @synthesize lblDateTime=_lblDateTime;
- (void).cxx_destruct;
- (void)clearLabelText;
- (void)setRowData:(id)arg1 repeatFlag:(_Bool)arg2;
- (void)buildUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

