//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface JRJEarlyPerformlistModel : NSObject
{
    NSString *_dateTo;
    NSString *_market;
    NSString *_buyPrice;
    NSString *_price;
    NSString *_stkname;
    NSString *_buyDate;
    NSString *_dateFrom;
    NSString *_stkid;
    NSString *_stkcode;
    NSNumber *_maxRiseRatio;
    NSNumber *_changeRatio;
    NSString *_stktype;
    NSArray *_dateList;
}

@property(retain, nonatomic) NSArray *dateList; // @synthesize dateList=_dateList;
@property(copy, nonatomic) NSString *stktype; // @synthesize stktype=_stktype;
@property(retain, nonatomic) NSNumber *changeRatio; // @synthesize changeRatio=_changeRatio;
@property(retain, nonatomic) NSNumber *maxRiseRatio; // @synthesize maxRiseRatio=_maxRiseRatio;
@property(copy, nonatomic) NSString *stkcode; // @synthesize stkcode=_stkcode;
@property(copy, nonatomic) NSString *stkid; // @synthesize stkid=_stkid;
@property(copy, nonatomic) NSString *dateFrom; // @synthesize dateFrom=_dateFrom;
@property(copy, nonatomic) NSString *buyDate; // @synthesize buyDate=_buyDate;
@property(copy, nonatomic) NSString *stkname; // @synthesize stkname=_stkname;
@property(copy, nonatomic) NSString *price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *buyPrice; // @synthesize buyPrice=_buyPrice;
@property(copy, nonatomic) NSString *market; // @synthesize market=_market;
@property(copy, nonatomic) NSString *dateTo; // @synthesize dateTo=_dateTo;
- (void).cxx_destruct;

@end

