//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseTableViewController.h"

@class NSMutableArray, _TtC16JRJInvestAdviser23JRJAuthorityControlView;

@interface JRJEstimatedTableViewController : JRJBaseTableViewController
{
    _Bool _isHaveNoneData;
    _Bool _isNetworkError;
    _Bool _isLoading;
    long long _pageSize;
    long long _pageNum;
    NSMutableArray *_dataArray;
    _TtC16JRJInvestAdviser23JRJAuthorityControlView *_authorityControlView;
}

@property(retain, nonatomic) _TtC16JRJInvestAdviser23JRJAuthorityControlView *authorityControlView; // @synthesize authorityControlView=_authorityControlView;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool isNetworkError; // @synthesize isNetworkError=_isNetworkError;
@property(nonatomic) _Bool isHaveNoneData; // @synthesize isHaveNoneData=_isHaveNoneData;
@property(nonatomic) long long pageNum; // @synthesize pageNum=_pageNum;
@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
- (void).cxx_destruct;
- (void)addAuthorityControlView;
- (void)loadDataFailHandle;
- (void)loadDataFinishHandle;
- (void)startLoadDataHandle;
- (_Bool)configCellWithDic;
- (void)loadListRequest;
- (void)requestMoreListData;
- (void)handleRequestDataArray:(id)arg1;
- (_Bool)isNibCell;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (Class)cellClass;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)viewDidLoad;

@end

