//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface JRJFundFinancialDingQiItemModel : NSObject
{
    NSString *_type;
    NSString *_tag;
    NSString *_partner;
    NSString *_contractname;
    NSString *_interest;
    NSString *_interestadd;
    NSString *_interestdesc;
    NSString *_period;
    NSString *_lowoffer;
    NSNumber *_surplusMoney;
    long long _status;
    NSString *_statusdesc;
    NSString *_url;
    NSString *_starttime;
    NSString *_image;
}

@property(copy, nonatomic) NSString *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *starttime; // @synthesize starttime=_starttime;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *statusdesc; // @synthesize statusdesc=_statusdesc;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSNumber *surplusMoney; // @synthesize surplusMoney=_surplusMoney;
@property(copy, nonatomic) NSString *lowoffer; // @synthesize lowoffer=_lowoffer;
@property(copy, nonatomic) NSString *period; // @synthesize period=_period;
@property(copy, nonatomic) NSString *interestdesc; // @synthesize interestdesc=_interestdesc;
@property(copy, nonatomic) NSString *interestadd; // @synthesize interestadd=_interestadd;
@property(copy, nonatomic) NSString *interest; // @synthesize interest=_interest;
@property(copy, nonatomic) NSString *contractname; // @synthesize contractname=_contractname;
@property(copy, nonatomic) NSString *partner; // @synthesize partner=_partner;
@property(copy, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

