//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class NSDictionary, UILabel;

@interface JRJFinacingChooseStockCell : JRJTableViewCell
{
    UILabel *_stockNameLabel;
    UILabel *_stockCodeLabel;
    UILabel *_numberFirstLabel;
    UILabel *_numberSecondLabel;
    UILabel *_numberThirdLabel;
    UILabel *_numberForthLabel;
    NSDictionary *_myDic;
    CDUnknownBlockType _pushStockDetailBlock;
}

@property(copy, nonatomic) CDUnknownBlockType pushStockDetailBlock; // @synthesize pushStockDetailBlock=_pushStockDetailBlock;
@property(retain, nonatomic) NSDictionary *myDic; // @synthesize myDic=_myDic;
@property(nonatomic) __weak UILabel *numberForthLabel; // @synthesize numberForthLabel=_numberForthLabel;
@property(nonatomic) __weak UILabel *numberThirdLabel; // @synthesize numberThirdLabel=_numberThirdLabel;
@property(nonatomic) __weak UILabel *numberSecondLabel; // @synthesize numberSecondLabel=_numberSecondLabel;
@property(nonatomic) __weak UILabel *numberFirstLabel; // @synthesize numberFirstLabel=_numberFirstLabel;
@property(nonatomic) __weak UILabel *stockCodeLabel; // @synthesize stockCodeLabel=_stockCodeLabel;
@property(nonatomic) __weak UILabel *stockNameLabel; // @synthesize stockNameLabel=_stockNameLabel;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)configCellWithDic:(id)arg1;
- (void)pushStockDetailAction:(id)arg1;
- (void)awakeFromNib;

@end

