//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class UIImageView;

@interface JRJFundFinancialFundGroupCell : JRJTableViewCell
{
    CDUnknownBlockType _didClickFundGroupAreaBlock;
    UIImageView *_lingxiGroup;
    UIImageView *_lingxiGroupVip;
    UIImageView *_fundGroupImage1;
    UIImageView *_fundGroupImage2;
    UIImageView *_fundGroupImage3;
    UIImageView *_fundGroupImage4;
}

@property(retain, nonatomic) UIImageView *fundGroupImage4; // @synthesize fundGroupImage4=_fundGroupImage4;
@property(retain, nonatomic) UIImageView *fundGroupImage3; // @synthesize fundGroupImage3=_fundGroupImage3;
@property(retain, nonatomic) UIImageView *fundGroupImage2; // @synthesize fundGroupImage2=_fundGroupImage2;
@property(retain, nonatomic) UIImageView *fundGroupImage1; // @synthesize fundGroupImage1=_fundGroupImage1;
@property(retain, nonatomic) UIImageView *lingxiGroupVip; // @synthesize lingxiGroupVip=_lingxiGroupVip;
@property(retain, nonatomic) UIImageView *lingxiGroup; // @synthesize lingxiGroup=_lingxiGroup;
@property(copy, nonatomic) CDUnknownBlockType didClickFundGroupAreaBlock; // @synthesize didClickFundGroupAreaBlock=_didClickFundGroupAreaBlock;
- (void).cxx_destruct;
- (void)layoutPageSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

