//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJLaunchpadItem.h"

@class NSString;

@interface JRJFundFinancialFunctionModel : JRJLaunchpadItem
{
    _Bool _show;
    _Bool _needLogin;
    NSString *_tag;
    NSString *_tarUrl;
    long long _sortIndex;
    NSString *_trackId;
}

+ (id)modelCustomPropertyMapper;
@property(copy, nonatomic) NSString *trackId; // @synthesize trackId=_trackId;
@property(nonatomic) long long sortIndex; // @synthesize sortIndex=_sortIndex;
@property(copy, nonatomic) NSString *tarUrl; // @synthesize tarUrl=_tarUrl;
@property(nonatomic) _Bool needLogin; // @synthesize needLogin=_needLogin;
@property(nonatomic) _Bool show; // @synthesize show=_show;
@property(copy, nonatomic) NSString *tag; // @synthesize tag=_tag;
- (void).cxx_destruct;

@end

