//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJFormBaseCell.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIButton, UIFont, UITextField, UIView;
@protocol JRJFormTextFieldCellDelegate;

@interface JRJFormTextFieldCell : JRJFormBaseCell <UITextFieldDelegate>
{
    _Bool _passwordEntry;
    NSString *_placeholder;
    UIFont *_placeholderFont;
    UIView *_leftView;
    UIView *_rightView;
    long long _maxLength;
    id <JRJFormTextFieldCellDelegate> _delegate;
    CDUnknownBlockType _returnButtonTappedBlock;
    CDUnknownBlockType _textChangedBlock;
    UITextField *_textField;
    UIView *_bottomBorder;
    UIButton *_eyeButton;
}

@property(retain, nonatomic) UIButton *eyeButton; // @synthesize eyeButton=_eyeButton;
@property(retain, nonatomic) UIView *bottomBorder; // @synthesize bottomBorder=_bottomBorder;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(nonatomic) _Bool passwordEntry; // @synthesize passwordEntry=_passwordEntry;
@property(copy, nonatomic) CDUnknownBlockType textChangedBlock; // @synthesize textChangedBlock=_textChangedBlock;
@property(copy, nonatomic) CDUnknownBlockType returnButtonTappedBlock; // @synthesize returnButtonTappedBlock=_returnButtonTappedBlock;
@property(nonatomic) __weak id <JRJFormTextFieldCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long maxLength; // @synthesize maxLength=_maxLength;
@property(retain, nonatomic) UIView *rightView; // @synthesize rightView=_rightView;
@property(retain, nonatomic) UIView *leftView; // @synthesize leftView=_leftView;
@property(retain, nonatomic) UIFont *placeholderFont; // @synthesize placeholderFont=_placeholderFont;
@property(retain, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
- (void).cxx_destruct;
- (void)editingChanged:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)p_updatePlaceholder;
- (void)eyeButtonTapped:(id)arg1;
@property(copy, nonatomic) NSString *text;
- (void)configure;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

