//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class JRJFundFinancialBankModel, JRJFundFinancialDingQiModel, JRJFundFinancialInsuranceModel, JRJFundFinancialNewsModel, JRJFundFinancialRecommendModel, NSArray;

@interface JRJFundFinancialConfigModel : NSObject
{
    NSArray *_functions;
    NSArray *_banners;
    JRJFundFinancialRecommendModel *_recommendModel;
    JRJFundFinancialDingQiModel *_dingqiModel;
    JRJFundFinancialInsuranceModel *_insuranceModel;
    JRJFundFinancialNewsModel *_newsModel;
    JRJFundFinancialBankModel *_bankModel;
}

+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) JRJFundFinancialBankModel *bankModel; // @synthesize bankModel=_bankModel;
@property(retain, nonatomic) JRJFundFinancialNewsModel *newsModel; // @synthesize newsModel=_newsModel;
@property(retain, nonatomic) JRJFundFinancialInsuranceModel *insuranceModel; // @synthesize insuranceModel=_insuranceModel;
@property(retain, nonatomic) JRJFundFinancialDingQiModel *dingqiModel; // @synthesize dingqiModel=_dingqiModel;
@property(retain, nonatomic) JRJFundFinancialRecommendModel *recommendModel; // @synthesize recommendModel=_recommendModel;
@property(retain, nonatomic) NSArray *banners; // @synthesize banners=_banners;
@property(retain, nonatomic) NSArray *functions; // @synthesize functions=_functions;
- (void).cxx_destruct;

@end

