//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WMMenuViewDelegate-Protocol.h"

@class NSString, UILabel, WMMenuView;

@interface JRJHotPlateSectionTabView : UIView <WMMenuViewDelegate>
{
    CDUnknownBlockType _didPressedMenuBlock;
    WMMenuView *_menuView;
    UIView *_lineView;
    UIView *_titleView;
    UILabel *_leftLebel;
    UILabel *_centerLabel;
    UILabel *_rightLabel;
    UIView *_sepLineView;
}

@property(retain, nonatomic) UIView *sepLineView; // @synthesize sepLineView=_sepLineView;
@property(retain, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(retain, nonatomic) UILabel *centerLabel; // @synthesize centerLabel=_centerLabel;
@property(retain, nonatomic) UILabel *leftLebel; // @synthesize leftLebel=_leftLebel;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) WMMenuView *menuView; // @synthesize menuView=_menuView;
@property(copy, nonatomic) CDUnknownBlockType didPressedMenuBlock; // @synthesize didPressedMenuBlock=_didPressedMenuBlock;
- (void).cxx_destruct;
- (void)layoutPageSubviews;
- (void)menuView:(id)arg1 didSelesctedIndex:(long long)arg2 currentIndex:(long long)arg3;
- (double)menuView:(id)arg1 widthForItemAtIndex:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

