//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSDictionary, UIImageView, UILabel, UIView;

@interface JRJHomePortalView : UICollectionViewCell
{
    UIImageView *_iconImageView;
    UILabel *_nameLabel;
    NSDictionary *_portal;
    UIView *_containerView;
}

@property(nonatomic) __weak UIView *containerView; // @synthesize containerView=_containerView;
@property(copy, nonatomic) NSDictionary *portal; // @synthesize portal=_portal;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)awakeFromNib;

@end

