//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseCell.h"

@class JRJHotTopicListModel, UIImageView, UILabel, UIView;

@interface JRJHotTopicListCell : JRJBaseCell
{
    CDUnknownBlockType _adviserBlock;
    UIImageView *_image;
    UILabel *_titleLbl;
    UILabel *_contentLbl;
    UILabel *_numLbl;
    UIView *_adviserBG;
    UILabel *_adviserName;
    UIImageView *_adviserIcon;
    JRJHotTopicListModel *_nowModel;
}

@property(retain, nonatomic) JRJHotTopicListModel *nowModel; // @synthesize nowModel=_nowModel;
@property(nonatomic) __weak UIImageView *adviserIcon; // @synthesize adviserIcon=_adviserIcon;
@property(nonatomic) __weak UILabel *adviserName; // @synthesize adviserName=_adviserName;
@property(nonatomic) __weak UIView *adviserBG; // @synthesize adviserBG=_adviserBG;
@property(nonatomic) __weak UILabel *numLbl; // @synthesize numLbl=_numLbl;
@property(nonatomic) __weak UILabel *contentLbl; // @synthesize contentLbl=_contentLbl;
@property(nonatomic) __weak UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;
@property(nonatomic) __weak UIImageView *image; // @synthesize image=_image;
@property(copy, nonatomic) CDUnknownBlockType adviserBlock; // @synthesize adviserBlock=_adviserBlock;
- (void).cxx_destruct;
- (void)updateCell:(id)arg1;
- (void)awakeFromNib;

@end

