//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TradeTableAlertModel.h"

@class NSNumber, NSString;

@interface JRJIpoapplyInfoModel : TradeTableAlertModel
{
    _Bool _isShowConfirm;
    NSString *_applyStatus;
    NSString *_applyStatusName;
    NSString *_applyMsg;
    NSString *_stockCode;
    NSString *_stockName;
    NSNumber *_applyAmount;
    NSString *_isTopBuy;
}

@property(nonatomic) _Bool isShowConfirm; // @synthesize isShowConfirm=_isShowConfirm;
@property(copy, nonatomic) NSString *isTopBuy; // @synthesize isTopBuy=_isTopBuy;
@property(retain, nonatomic) NSNumber *applyAmount; // @synthesize applyAmount=_applyAmount;
@property(copy, nonatomic) NSString *stockName; // @synthesize stockName=_stockName;
@property(copy, nonatomic) NSString *stockCode; // @synthesize stockCode=_stockCode;
@property(copy, nonatomic) NSString *applyMsg; // @synthesize applyMsg=_applyMsg;
@property(copy, nonatomic) NSString *applyStatusName; // @synthesize applyStatusName=_applyStatusName;
@property(copy, nonatomic) NSString *applyStatus; // @synthesize applyStatus=_applyStatus;
- (void).cxx_destruct;

@end

