//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class EmotionView, NSLayoutConstraint, NSString, UIButton, UILabel, UITextView;

@interface JRJInputAccessoryView : UIView <UITextViewDelegate>
{
    _Bool _isShowingEmotion;
    UIButton *_emotionButton;
    UIButton *_stockButton;
    UITextView *_textView;
    EmotionView *_emotionView;
    CDUnknownBlockType _emotionButtonPressedBlock;
    CDUnknownBlockType _stockButtonPressedBlock;
    CDUnknownBlockType _sendButtonPressedBlock;
    CDUnknownBlockType _textDidChangedBlock;
    CDUnknownBlockType _textCantChangeTipsBlock;
    CDUnknownBlockType _cancelButtonClickBlock;
    NSString *_placeholder;
    UIButton *_sendButton;
    UILabel *_placeholderLabel;
    NSLayoutConstraint *_emotionViewTopMarginConstraint;
}

@property(retain, nonatomic) NSLayoutConstraint *emotionViewTopMarginConstraint; // @synthesize emotionViewTopMarginConstraint=_emotionViewTopMarginConstraint;
@property(nonatomic) __weak UILabel *placeholderLabel; // @synthesize placeholderLabel=_placeholderLabel;
@property(nonatomic) __weak UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(copy, nonatomic) NSString *placeholder; // @synthesize placeholder=_placeholder;
@property(nonatomic) _Bool isShowingEmotion; // @synthesize isShowingEmotion=_isShowingEmotion;
@property(copy, nonatomic) CDUnknownBlockType cancelButtonClickBlock; // @synthesize cancelButtonClickBlock=_cancelButtonClickBlock;
@property(copy, nonatomic) CDUnknownBlockType textCantChangeTipsBlock; // @synthesize textCantChangeTipsBlock=_textCantChangeTipsBlock;
@property(copy, nonatomic) CDUnknownBlockType textDidChangedBlock; // @synthesize textDidChangedBlock=_textDidChangedBlock;
@property(copy, nonatomic) CDUnknownBlockType sendButtonPressedBlock; // @synthesize sendButtonPressedBlock=_sendButtonPressedBlock;
@property(copy, nonatomic) CDUnknownBlockType stockButtonPressedBlock; // @synthesize stockButtonPressedBlock=_stockButtonPressedBlock;
@property(copy, nonatomic) CDUnknownBlockType emotionButtonPressedBlock; // @synthesize emotionButtonPressedBlock=_emotionButtonPressedBlock;
@property(retain, nonatomic) EmotionView *emotionView; // @synthesize emotionView=_emotionView;
@property(nonatomic) __weak UITextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak UIButton *stockButton; // @synthesize stockButton=_stockButton;
@property(nonatomic) __weak UIButton *emotionButton; // @synthesize emotionButton=_emotionButton;
- (void).cxx_destruct;
- (void)needHideEmojiAndStockBtn:(_Bool)arg1;
- (void)cancelButtonClickHandle:(id)arg1;
- (void)clearTextView;
- (void)endEditing;
- (void)beginEditing;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)refreshUserInterface;
- (void)deleteText;
- (void)insertStock:(id)arg1;
- (void)insertEmotionWithIndex:(long long)arg1;
- (void)hideEmotionView;
- (void)showEmotionView;
- (void)sendButtonPressed:(id)arg1;
- (void)stockButtonPressed:(id)arg1;
- (void)emotionButtonPressed:(id)arg1;
- (void)loadNib;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

