//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class JRJDiagnoseChartView, NSDictionary, NSLayoutConstraint, UIButton, UIImageView, UILabel, UIView;

@interface JRJIntelligentChartCell : JRJTableViewCell
{
    UIView *_jiesuoView;
    UIButton *_checkDetailBtn;
    CDUnknownBlockType _questionBlock;
    CDUnknownBlockType _checkDetailBlock;
    CDUnknownBlockType _extendBlock;
    UILabel *_oneYearsLabel;
    UILabel *_totalProfitLabel;
    UIView *_leftRoundView;
    UIView *_rightRoundView;
    JRJDiagnoseChartView *_chartView;
    UIImageView *_runwinImageView;
    double _max;
    double _min;
    UILabel *_leftDateLabel;
    UILabel *_centerDateLabel;
    UILabel *_rightDateLabel;
    UILabel *_firstRateLabel;
    UILabel *_secondRateLabel;
    UILabel *_thirdRateLabel;
    UILabel *_fourthRateLabel;
    UILabel *_fivethRateLabel;
    UILabel *_wenanLabel;
    NSDictionary *_dataDic;
    NSLayoutConstraint *_vsImageViewLayout;
    UILabel *_topTotalProfitLabel;
    UILabel *_topOneYearProfitLabel;
    UILabel *_xinHaoLabel;
    UILabel *_vsLabel;
    UIImageView *_extendImageView;
}

@property(nonatomic) __weak UIImageView *extendImageView; // @synthesize extendImageView=_extendImageView;
@property(nonatomic) __weak UILabel *vsLabel; // @synthesize vsLabel=_vsLabel;
@property(nonatomic) __weak UILabel *xinHaoLabel; // @synthesize xinHaoLabel=_xinHaoLabel;
@property(nonatomic) __weak UILabel *topOneYearProfitLabel; // @synthesize topOneYearProfitLabel=_topOneYearProfitLabel;
@property(nonatomic) __weak UILabel *topTotalProfitLabel; // @synthesize topTotalProfitLabel=_topTotalProfitLabel;
@property(nonatomic) __weak NSLayoutConstraint *vsImageViewLayout; // @synthesize vsImageViewLayout=_vsImageViewLayout;
@property(retain, nonatomic) NSDictionary *dataDic; // @synthesize dataDic=_dataDic;
@property(nonatomic) __weak UILabel *wenanLabel; // @synthesize wenanLabel=_wenanLabel;
@property(nonatomic) __weak UILabel *fivethRateLabel; // @synthesize fivethRateLabel=_fivethRateLabel;
@property(nonatomic) __weak UILabel *fourthRateLabel; // @synthesize fourthRateLabel=_fourthRateLabel;
@property(nonatomic) __weak UILabel *thirdRateLabel; // @synthesize thirdRateLabel=_thirdRateLabel;
@property(nonatomic) __weak UILabel *secondRateLabel; // @synthesize secondRateLabel=_secondRateLabel;
@property(nonatomic) __weak UILabel *firstRateLabel; // @synthesize firstRateLabel=_firstRateLabel;
@property(nonatomic) __weak UILabel *rightDateLabel; // @synthesize rightDateLabel=_rightDateLabel;
@property(nonatomic) __weak UILabel *centerDateLabel; // @synthesize centerDateLabel=_centerDateLabel;
@property(nonatomic) __weak UILabel *leftDateLabel; // @synthesize leftDateLabel=_leftDateLabel;
@property(nonatomic) double min; // @synthesize min=_min;
@property(nonatomic) double max; // @synthesize max=_max;
@property(nonatomic) __weak UIImageView *runwinImageView; // @synthesize runwinImageView=_runwinImageView;
@property(nonatomic) __weak JRJDiagnoseChartView *chartView; // @synthesize chartView=_chartView;
@property(nonatomic) __weak UIView *rightRoundView; // @synthesize rightRoundView=_rightRoundView;
@property(nonatomic) __weak UIView *leftRoundView; // @synthesize leftRoundView=_leftRoundView;
@property(nonatomic) __weak UILabel *totalProfitLabel; // @synthesize totalProfitLabel=_totalProfitLabel;
@property(nonatomic) __weak UILabel *oneYearsLabel; // @synthesize oneYearsLabel=_oneYearsLabel;
@property(copy, nonatomic) CDUnknownBlockType extendBlock; // @synthesize extendBlock=_extendBlock;
@property(copy, nonatomic) CDUnknownBlockType checkDetailBlock; // @synthesize checkDetailBlock=_checkDetailBlock;
@property(copy, nonatomic) CDUnknownBlockType questionBlock; // @synthesize questionBlock=_questionBlock;
@property(nonatomic) __weak UIButton *checkDetailBtn; // @synthesize checkDetailBtn=_checkDetailBtn;
@property(nonatomic) __weak UIView *jiesuoView; // @synthesize jiesuoView=_jiesuoView;
- (void).cxx_destruct;
- (void)setExtend:(_Bool)arg1;
- (void)cellExtendAction:(id)arg1;
- (void)questionAction:(id)arg1;
- (void)checkDetailAction:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setDateLabelWithArr:(id)arg1;
- (void)getMaxAndMinDataWith:(id)arg1;
- (void)updateWithDic:(id)arg1;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

