//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FTStockSummaryUnloginRequest, NSArray, NSTimer, UIButton;

@interface JRJIndexHeaderView : UIView
{
    NSArray *_indexLabels;
    NSArray *_percentLabels;
    UIButton *_marketBtn;
    NSArray *_buttons;
    NSArray *_indexes;
    FTStockSummaryUnloginRequest *_indexRequest;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) FTStockSummaryUnloginRequest *indexRequest; // @synthesize indexRequest=_indexRequest;
@property(retain, nonatomic) NSArray *indexes; // @synthesize indexes=_indexes;
@property(retain, nonatomic) NSArray *buttons; // @synthesize buttons=_buttons;
@property(nonatomic) __weak UIButton *marketBtn; // @synthesize marketBtn=_marketBtn;
@property(retain, nonatomic) NSArray *percentLabels; // @synthesize percentLabels=_percentLabels;
@property(retain, nonatomic) NSArray *indexLabels; // @synthesize indexLabels=_indexLabels;
- (void).cxx_destruct;
- (void)bindDataWithArray:(id)arg1;
- (void)requestIndexInfo;
- (void)shouldStartRefresh:(_Bool)arg1;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

