//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString, UIImage;

@interface JRJKCBNewsPageListModel : NSObject
{
    NSDictionary *__id;
    NSString *_iiid;
    NSString *_click;
    NSString *_title;
    NSString *_author;
    NSString *_keyword;
    NSString *_makedate;
    NSString *_timestamp;
    NSString *_channum;
    NSString *_infocls;
    NSString *_detail;
    NSString *_apptop;
    NSString *_imgurl;
    NSString *_infourl;
    NSString *_isblod;
    NSString *_isred;
    NSArray *_images;
    NSString *_createTimeString;
    UIImage *_placeholderImage;
}

@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(copy, nonatomic) NSString *createTimeString; // @synthesize createTimeString=_createTimeString;
@property(retain, nonatomic) NSArray *images; // @synthesize images=_images;
@property(copy, nonatomic) NSString *isred; // @synthesize isred=_isred;
@property(copy, nonatomic) NSString *isblod; // @synthesize isblod=_isblod;
@property(copy, nonatomic) NSString *infourl; // @synthesize infourl=_infourl;
@property(copy, nonatomic) NSString *imgurl; // @synthesize imgurl=_imgurl;
@property(copy, nonatomic) NSString *apptop; // @synthesize apptop=_apptop;
@property(copy, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property(copy, nonatomic) NSString *infocls; // @synthesize infocls=_infocls;
@property(copy, nonatomic) NSString *channum; // @synthesize channum=_channum;
@property(copy, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
@property(copy, nonatomic) NSString *makedate; // @synthesize makedate=_makedate;
@property(copy, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
@property(copy, nonatomic) NSString *author; // @synthesize author=_author;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *click; // @synthesize click=_click;
@property(copy, nonatomic) NSString *iiid; // @synthesize iiid=_iiid;
@property(retain, nonatomic) NSDictionary *_id; // @synthesize _id=__id;
- (void).cxx_destruct;

@end

