//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface JRJLDRecordDataModel : NSObject
{
    _Bool _needHightLight;
    NSString *_content;
    NSString *_bkname;
    NSNumber *_dateTime;
    NSString *_bkcode;
    NSString *_formatDateStr;
}

@property(nonatomic) _Bool needHightLight; // @synthesize needHightLight=_needHightLight;
@property(copy, nonatomic) NSString *formatDateStr; // @synthesize formatDateStr=_formatDateStr;
@property(copy, nonatomic) NSString *bkcode; // @synthesize bkcode=_bkcode;
@property(retain, nonatomic) NSNumber *dateTime; // @synthesize dateTime=_dateTime;
@property(copy, nonatomic) NSString *bkname; // @synthesize bkname=_bkname;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;

@end

