//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class FXPageControl, NSArray, NSMutableArray, NSString, UICollectionView, UIFont;

@interface JRJLaunchpadView : UIView <UICollectionViewDataSource, UICollectionViewDelegate>
{
    CDUnknownBlockType _selectBlock;
    NSArray *_items;
    FXPageControl *_pageControl;
    unsigned long long _showRowType;
    long long _numberOfColumns;
    long long _numberOfRows;
    UIFont *_font;
    Class _cellClass;
    NSString *_cellNibName;
    UICollectionView *_collectionView;
    NSMutableArray *_data;
    long long _numberOfPages;
    long long _pageSize;
}

@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) long long numberOfPages; // @synthesize numberOfPages=_numberOfPages;
@property(retain, nonatomic) NSMutableArray *data; // @synthesize data=_data;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(copy, nonatomic) NSString *cellNibName; // @synthesize cellNibName=_cellNibName;
@property(retain, nonatomic) Class cellClass; // @synthesize cellClass=_cellClass;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(nonatomic) long long numberOfRows; // @synthesize numberOfRows=_numberOfRows;
@property(nonatomic) long long numberOfColumns; // @synthesize numberOfColumns=_numberOfColumns;
@property(nonatomic) unsigned long long showRowType; // @synthesize showRowType=_showRowType;
@property(retain, nonatomic) FXPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(copy, nonatomic) CDUnknownBlockType selectBlock; // @synthesize selectBlock=_selectBlock;
- (void).cxx_destruct;
- (void)remakePageControlPosY:(double)arg1;
- (void)showPageHit:(_Bool)arg1;
- (id)p_itemAtSection:(long long)arg1 atRow:(long long)arg2;
- (long long)p_transposeIndex:(long long)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 cellClass:(Class)arg2 cellNibName:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1 cellClass:(Class)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

