//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UIImageView;

@interface JRJLoginCaptchaView : UIView
{
    _Bool _loading;
    UIImageView *_captchaImageView;
    UIImageView *_refreshImageView;
    UIActivityIndicatorView *_loadingIndicator;
}

@property(nonatomic, getter=isLoading) _Bool loading; // @synthesize loading=_loading;
@property(retain, nonatomic) UIActivityIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) UIImageView *refreshImageView; // @synthesize refreshImageView=_refreshImageView;
@property(retain, nonatomic) UIImageView *captchaImageView; // @synthesize captchaImageView=_captchaImageView;
- (void).cxx_destruct;
- (void)refreshCaptcha;
- (void)tapped:(id)arg1;
- (void)willMoveToWindow:(id)arg1;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

