//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIButton, UIImageView, UILabel;

@interface JRJMyintegatingAlertView : UIView
{
    int _todayIndex;
    CDUnknownBlockType _signBtnTapped;
    CDUnknownBlockType _dismissBtnTapped;
    UIButton *_dismissUIButton;
    UILabel *_signCountUILabel;
    NSArray *_imageBgArray;
    NSArray *_dateUILabelArray;
    NSArray *_scoreUILabelArray;
    NSArray *_allViewArray;
    UIButton *_signUIButton;
    UIImageView *_todayUIImageView;
}

@property(retain, nonatomic) UIImageView *todayUIImageView; // @synthesize todayUIImageView=_todayUIImageView;
@property(retain, nonatomic) UIButton *signUIButton; // @synthesize signUIButton=_signUIButton;
@property(nonatomic) int todayIndex; // @synthesize todayIndex=_todayIndex;
@property(retain, nonatomic) NSArray *allViewArray; // @synthesize allViewArray=_allViewArray;
@property(retain, nonatomic) NSArray *scoreUILabelArray; // @synthesize scoreUILabelArray=_scoreUILabelArray;
@property(retain, nonatomic) NSArray *dateUILabelArray; // @synthesize dateUILabelArray=_dateUILabelArray;
@property(retain, nonatomic) NSArray *imageBgArray; // @synthesize imageBgArray=_imageBgArray;
@property(retain, nonatomic) UILabel *signCountUILabel; // @synthesize signCountUILabel=_signCountUILabel;
@property(retain, nonatomic) UIButton *dismissUIButton; // @synthesize dismissUIButton=_dismissUIButton;
@property(copy, nonatomic) CDUnknownBlockType dismissBtnTapped; // @synthesize dismissBtnTapped=_dismissBtnTapped;
@property(copy, nonatomic) CDUnknownBlockType signBtnTapped; // @synthesize signBtnTapped=_signBtnTapped;
- (void).cxx_destruct;
- (void)delayAction:(id)arg1;
- (void)signStartAnimation;
- (void)dismissAlertView:(id)arg1;
- (void)signBtn:(id)arg1;
- (void)showJRJMyintegatingScoreWithDic:(id)arg1;
- (void)awakeFromNib;

@end

