//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel, UIView;

@interface JRJMystockButtonCell : UICollectionViewCell
{
    UILabel *_plateDetailLabel;
    UIImageView *_imageView;
    UILabel *_redPointLabel;
    UIView *_unReadView;
}

@property(retain, nonatomic) UIView *unReadView; // @synthesize unReadView=_unReadView;
@property(retain, nonatomic) UILabel *redPointLabel; // @synthesize redPointLabel=_redPointLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UILabel *plateDetailLabel; // @synthesize plateDetailLabel=_plateDetailLabel;
- (void).cxx_destruct;
- (void)updateRedPointLabelWithCount:(long long)arg1;
- (void)commit;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;

@end

