//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseSource.h"

@interface JRJMyPortfolioSource : BaseSource
{
    _Bool _expand;
    _Bool _showAdviser;
}

@property(nonatomic) _Bool showAdviser; // @synthesize showAdviser=_showAdviser;
@property(nonatomic) _Bool expand; // @synthesize expand=_expand;
- (double)heightForSource:(double)arg1;

@end

