//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JRJMyStockOperate : NSObject
{
}

+ (id)modelFromSecuritySummary:(id)arg1;
+ (id)instance;
- (id)allStockModels;
- (id)allIndexIDsAndstockIDsString;
- (id)allIndexIDsAndStockCodesString;
- (id)allStockCodesStringLimit:(long long)arg1;
- (id)allStockCodesString;
- (id)allStockIDsString;
- (_Bool)deleteStockInGuestWithSummary:(id)arg1;
- (_Bool)insertStockInGuestWithSummary:(id)arg1;
- (_Bool)isExistsGuestStockWithSummary:(id)arg1;
- (id)getLocalStocks:(id)arg1;
- (_Bool)isExistsStockWithGroupModel:(id)arg1;
- (_Bool)isExistsStockInModeluser:(id)arg1;
- (_Bool)haveBeenAddedStock:(id)arg1;
- (id)searchStockInAllGroup:(id)arg1;
- (id)allModelWithGroup:(id)arg1 user:(id)arg2;
- (id)allModelWithGroup:(id)arg1;
- (_Bool)deleteDataFromGroupDefaulWithModel:(id)arg1;
- (_Bool)deleteDataFromDefaultGroupWithModels:(id)arg1;
- (_Bool)deleteDataFromGroupWithModels:(id)arg1;
- (_Bool)deleteDataFromGroupWithModel:(id)arg1;
- (_Bool)deleteLocalDataWithModel:(id)arg1;
- (_Bool)deleteDataWithModel:(id)arg1;
- (_Bool)deleteAllLocalDataWithUserId:(id)arg1;
- (_Bool)deleteAllLocalDataWithGroupId:(id)arg1;
- (_Bool)updateDataWithModel:(id)arg1;
- (_Bool)updateLocalSnWithModels:(id)arg1;
- (_Bool)updateLocalSnWithModel:(id)arg1;
- (_Bool)updateSnWithModel:(id)arg1;
- (_Bool)updateSnWithModels:(id)arg1;
- (_Bool)insertDataWithModel:(id)arg1;
- (_Bool)insertDataToDefaultGroupWithModel:(id)arg1;
- (id)getStockMaxSnWithUserID:(id)arg1;
- (id)getStockMaxSn:(id)arg1;
- (id)stockUniIDStringsWithModel:(id)arg1;
- (_Bool)updateStocksToSaveUser:(id)arg1 stocks:(id)arg2;

@end

