//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseCell.h"

@class NSLayoutConstraint;

@interface JRJNewZFristHeadCell : JRJBaseCell
{
    NSLayoutConstraint *_priceLeftNSLayoutConstraint;
    NSLayoutConstraint *_raiseLeftNSLayoutConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *raiseLeftNSLayoutConstraint; // @synthesize raiseLeftNSLayoutConstraint=_raiseLeftNSLayoutConstraint;
@property(nonatomic) __weak NSLayoutConstraint *priceLeftNSLayoutConstraint; // @synthesize priceLeftNSLayoutConstraint=_priceLeftNSLayoutConstraint;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

