//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WMPageController.h"

#import "FSSegmentTitleViewDelegate-Protocol.h"
#import "WMPageControllerDelegate-Protocol.h"

@class FSSegmentTitleView, JRJNotionRadarFundVC, JRJNotionRadarNewsVC, NSString;

@interface JRJNotionRadarPageVC : WMPageController <WMPageControllerDelegate, FSSegmentTitleViewDelegate>
{
    JRJNotionRadarFundVC *_fundVC;
    JRJNotionRadarNewsVC *_hotNewsVC;
    FSSegmentTitleView *_segmentTitleView;
}

@property(retain, nonatomic) FSSegmentTitleView *segmentTitleView; // @synthesize segmentTitleView=_segmentTitleView;
@property(retain, nonatomic) JRJNotionRadarNewsVC *hotNewsVC; // @synthesize hotNewsVC=_hotNewsVC;
@property(retain, nonatomic) JRJNotionRadarFundVC *fundVC; // @synthesize fundVC=_fundVC;
- (void).cxx_destruct;
- (void)FSSegmentTitleView:(id)arg1 startIndex:(long long)arg2 endIndex:(long long)arg3;
- (void)didSelectedPageController:(id)arg1 index:(long long)arg2;
- (void)willSlidePageController:(id)arg1 index:(long long)arg2;
- (id)pageControllerForIndex:(long long)arg1;
- (long long)numberOfPages:(id)arg1;
- (void)configTitleView;
- (void)viewDidLoad;
- (id)initWithIndex:(long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

