//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseCell.h"

@class NSLayoutConstraint, UIImageView;

@interface JRJNewZLastOptionCell : JRJBaseCell
{
    UIImageView *_vimUIImageView;
    NSLayoutConstraint *_heightConstrait;
    CDUnknownBlockType _clickVimImageBlock;
}

@property(copy, nonatomic) CDUnknownBlockType clickVimImageBlock; // @synthesize clickVimImageBlock=_clickVimImageBlock;
@property(nonatomic) __weak NSLayoutConstraint *heightConstrait; // @synthesize heightConstrait=_heightConstrait;
@property(nonatomic) __weak UIImageView *vimUIImageView; // @synthesize vimUIImageView=_vimUIImageView;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

