//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseHandler.h"

@interface JRJNotionRadarHandler : BaseHandler
{
}

- (id)responseObjectForResponse:(id)arg1 responseObject:(id)arg2 error:(id *)arg3;
- (void)requestNotionHotNewsListWithPageNum:(long long)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (void)requestNotionConseptionInfoListFinishBlock:(CDUnknownBlockType)arg1;
- (void)requestNotionRadarMainDataFinishBlock:(CDUnknownBlockType)arg1;

@end

