//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface JRJOutFundModel : NSObject
{
    NSString *_stid;
    NSString *_code;
    NSString *_name;
    NSString *_shrt;
    NSString *_mrkt;
    NSString *_type;
    NSString *_stat;
}

@property(copy, nonatomic) NSString *stat; // @synthesize stat=_stat;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *mrkt; // @synthesize mrkt=_mrkt;
@property(copy, nonatomic) NSString *shrt; // @synthesize shrt=_shrt;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *stid; // @synthesize stid=_stid;
- (void).cxx_destruct;

@end

