//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseCell.h"

@class NSLayoutConstraint, NSString, UIColor, UIImageView, UILabel, UIView;

@interface JRJOrdinamryUserCell : JRJBaseCell
{
    UILabel *_rightLabel;
    UIImageView *_badgeView;
    UIImageView *_moreIconImageView;
    NSString *_imageName;
    NSString *_userTitle;
    CDUnknownBlockType _tapBlock;
    UIView *_line;
    NSLayoutConstraint *_leftLayoutConstraint;
    UIColor *_titleColor;
    UIImageView *_iconImage;
    UILabel *_title;
}

@property(nonatomic) __weak UILabel *title; // @synthesize title=_title;
@property(nonatomic) __weak UIImageView *iconImage; // @synthesize iconImage=_iconImage;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(nonatomic) __weak NSLayoutConstraint *leftLayoutConstraint; // @synthesize leftLayoutConstraint=_leftLayoutConstraint;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
@property(retain, nonatomic) NSString *userTitle; // @synthesize userTitle=_userTitle;
@property(retain, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
@property(nonatomic) __weak UIImageView *moreIconImageView; // @synthesize moreIconImageView=_moreIconImageView;
@property(nonatomic) __weak UIImageView *badgeView; // @synthesize badgeView=_badgeView;
@property(nonatomic) __weak UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
- (void).cxx_destruct;
- (void)hideImageView;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

