//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface JRJPlatesHeadView : UIView
{
    UILabel *_upTrendLabel;
    UILabel *_downTrendLabel;
    UILabel *_zPointLabel;
    UILabel *_sPointLabel;
}

@property(nonatomic) __weak UILabel *sPointLabel; // @synthesize sPointLabel=_sPointLabel;
@property(nonatomic) __weak UILabel *zPointLabel; // @synthesize zPointLabel=_zPointLabel;
@property(nonatomic) __weak UILabel *downTrendLabel; // @synthesize downTrendLabel=_downTrendLabel;
@property(nonatomic) __weak UILabel *upTrendLabel; // @synthesize upTrendLabel=_upTrendLabel;
- (void).cxx_destruct;
- (void)updateDataWithDic:(id)arg1;

@end

