//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class NSDictionary, NSLayoutConstraint, UILabel;

@interface JRJPortfolioReallocationTableViewCell : JRJTableViewCell
{
    double _separatorLeftMargin;
    NSDictionary *_tradeData;
    CDUnknownBlockType _touchBlock;
    CDUnknownBlockType _stockPressedBlock;
    UILabel *_actionLabel;
    UILabel *_stockNameLabel;
    UILabel *_stockSymbolLabel;
    UILabel *_priceLabel;
    UILabel *_reallocationLabel;
    UILabel *_dateLabel;
    NSLayoutConstraint *_separatorLeftMarginConstraint;
}

+ (double)cellHeight;
@property(nonatomic) __weak NSLayoutConstraint *separatorLeftMarginConstraint; // @synthesize separatorLeftMarginConstraint=_separatorLeftMarginConstraint;
@property(nonatomic) __weak UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(nonatomic) __weak UILabel *reallocationLabel; // @synthesize reallocationLabel=_reallocationLabel;
@property(nonatomic) __weak UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(nonatomic) __weak UILabel *stockSymbolLabel; // @synthesize stockSymbolLabel=_stockSymbolLabel;
@property(nonatomic) __weak UILabel *stockNameLabel; // @synthesize stockNameLabel=_stockNameLabel;
@property(nonatomic) __weak UILabel *actionLabel; // @synthesize actionLabel=_actionLabel;
@property(copy, nonatomic) CDUnknownBlockType stockPressedBlock; // @synthesize stockPressedBlock=_stockPressedBlock;
@property(copy, nonatomic) CDUnknownBlockType touchBlock; // @synthesize touchBlock=_touchBlock;
@property(retain, nonatomic) NSDictionary *tradeData; // @synthesize tradeData=_tradeData;
@property(nonatomic) double separatorLeftMargin; // @synthesize separatorLeftMargin=_separatorLeftMargin;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)stockPressedHandler:(id)arg1;
- (id)tradeTypeString;
- (id)reallocationString;
- (void)configCellWithModel:(id)arg1;
- (void)awakeFromNib;

@end

