//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface JRJPlateHotPlateCell : JRJTableViewCell
{
    UIImageView *_hotIcon;
    UILabel *_leftLebel;
    UILabel *_centerLabel;
    UILabel *_rightLabel;
    UIView *_sepLineView;
}

@property(retain, nonatomic) UIView *sepLineView; // @synthesize sepLineView=_sepLineView;
@property(retain, nonatomic) UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(retain, nonatomic) UILabel *centerLabel; // @synthesize centerLabel=_centerLabel;
@property(retain, nonatomic) UILabel *leftLebel; // @synthesize leftLebel=_leftLebel;
@property(retain, nonatomic) UIImageView *hotIcon; // @synthesize hotIcon=_hotIcon;
- (void).cxx_destruct;
- (void)layoutPageSubviews;
- (void)updateCellWithSource:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

