//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseHandler.h"

@class NSNumber;

@interface JRJPortfolioRankingListHandler : BaseHandler
{
    _Bool _isRefresh;
    int _pageId;
    int _totalPageNum;
    NSNumber *_rankingTypeId;
}

@property(nonatomic) _Bool isRefresh; // @synthesize isRefresh=_isRefresh;
@property(nonatomic) int totalPageNum; // @synthesize totalPageNum=_totalPageNum;
@property(nonatomic) int pageId; // @synthesize pageId=_pageId;
@property(retain, nonatomic) NSNumber *rankingTypeId; // @synthesize rankingTypeId=_rankingTypeId;
- (void).cxx_destruct;
- (_Bool)isNeedAutoLoadingResponse:(id)arg1;
- (_Bool)isCacheResponse:(id)arg1;
- (id)viewModelOfClass:(Class)arg1 fromModelArray:(id)arg2;
- (id)responseObjectForResponse:(id)arg1 responseObject:(id)arg2 error:(id *)arg3;
- (void)requestRankList:(CDUnknownBlockType)arg1;

@end

