//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KKTableViewController.h"

@class JRJPortfolioListViewControllerHandler, UIView;

@interface JRJPortfolioMastersListViewController : KKTableViewController
{
    _Bool _isLoadMore;
    int _rankType;
    UIView *_headerView;
    JRJPortfolioListViewControllerHandler *_handler;
}

@property(retain, nonatomic) JRJPortfolioListViewControllerHandler *handler; // @synthesize handler=_handler;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) _Bool isLoadMore; // @synthesize isLoadMore=_isLoadMore;
@property(nonatomic) int rankType; // @synthesize rankType=_rankType;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)doGetCoupons;
- (void)loadListRequest;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)fetchList;
- (void)delayLoadMore;
- (void)reloadDataSource;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (id)init;

@end

