//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseViewController.h"

@class JRJPortfolioDetailSource, JRJPortfolioNewUserGiftView, NSMutableDictionary, NSString, UIView;

@interface JRJPortfolioDetailViewController : JRJBaseViewController
{
    _Bool _isLoading;
    NSString *_portfolioId;
    NSMutableDictionary *_dataDic;
    JRJPortfolioDetailSource *_source;
    JRJPortfolioNewUserGiftView *_giftView;
    UIView *_blackView;
}

@property(retain, nonatomic) UIView *blackView; // @synthesize blackView=_blackView;
@property(retain, nonatomic) JRJPortfolioNewUserGiftView *giftView; // @synthesize giftView=_giftView;
@property(retain, nonatomic) JRJPortfolioDetailSource *source; // @synthesize source=_source;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) NSMutableDictionary *dataDic; // @synthesize dataDic=_dataDic;
@property(copy, nonatomic) NSString *portfolioId; // @synthesize portfolioId=_portfolioId;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)showPortfolioDetail;
- (void)changeUserPrivilege;
- (void)freePortfolioTry:(id)arg1;
- (void)fetchList;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)closePopWindowAnimation;
- (void)backButtonPressed:(id)arg1;
- (void)shareButtonPressed:(id)arg1;
- (void)initNavagationBtns;
- (void)updateNavStyleToPortfolioDetail:(_Bool)arg1;
- (void)navagationStyle;
- (void)navagationTitle;
- (void)viewDidLoad;

@end

