//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface JRJPopWindowModel : NSObject
{
    long long _pop_id;
    NSString *_title;
    long long _adDiscoveryFlag;
    NSNumber *_startTime;
    NSNumber *_endTime;
    NSNumber *_userType;
    long long _type;
    NSNumber *_couponInfoId;
    long long _platform;
    long long _iosChannel;
    long long _andriodChannel;
    NSString *_publishLink;
    NSString *_firstImg;
    NSString *_secondImg;
    NSString *_throughLink;
    long long _status;
    NSString *_remark;
    long long _throughType;
}

@property(nonatomic) long long throughType; // @synthesize throughType=_throughType;
@property(copy, nonatomic) NSString *remark; // @synthesize remark=_remark;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *throughLink; // @synthesize throughLink=_throughLink;
@property(copy, nonatomic) NSString *secondImg; // @synthesize secondImg=_secondImg;
@property(copy, nonatomic) NSString *firstImg; // @synthesize firstImg=_firstImg;
@property(copy, nonatomic) NSString *publishLink; // @synthesize publishLink=_publishLink;
@property(nonatomic) long long andriodChannel; // @synthesize andriodChannel=_andriodChannel;
@property(nonatomic) long long iosChannel; // @synthesize iosChannel=_iosChannel;
@property(nonatomic) long long platform; // @synthesize platform=_platform;
@property(retain, nonatomic) NSNumber *couponInfoId; // @synthesize couponInfoId=_couponInfoId;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) NSNumber *userType; // @synthesize userType=_userType;
@property(retain, nonatomic) NSNumber *endTime; // @synthesize endTime=_endTime;
@property(retain, nonatomic) NSNumber *startTime; // @synthesize startTime=_startTime;
@property(nonatomic) long long adDiscoveryFlag; // @synthesize adDiscoveryFlag=_adDiscoveryFlag;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long pop_id; // @synthesize pop_id=_pop_id;
- (void).cxx_destruct;
- (void)setValue:(id)arg1 forUndefinedKey:(id)arg2;

@end

