//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface JRJPourIntoOptionStocksAlertView : UIView
{
    CDUnknownBlockType _goOptionListBlock;
    UIButton *_dismissAlertview;
    UIButton *_gotoOptionStockList;
    UIView *_alertUIView;
}

+ (id)p_keywindow;
+ (id)p_currentView;
+ (void)dismiss;
+ (void)showWithVC:(id)arg1 withgotoOptionListBlock:(CDUnknownBlockType)arg2;
@property(nonatomic) __weak UIView *alertUIView; // @synthesize alertUIView=_alertUIView;
@property(nonatomic) __weak UIButton *gotoOptionStockList; // @synthesize gotoOptionStockList=_gotoOptionStockList;
@property(nonatomic) __weak UIButton *dismissAlertview; // @synthesize dismissAlertview=_dismissAlertview;
@property(copy, nonatomic) CDUnknownBlockType goOptionListBlock; // @synthesize goOptionListBlock=_goOptionListBlock;
- (void).cxx_destruct;
- (void)dismiss;
- (void)handleTap:(id)arg1;
- (void)p_registerNotifications;
- (void)p_loadNib;
- (void)dealloc;
- (id)init;
- (void)clickGotoOptionStockList:(id)arg1;
- (void)dismissAlertView:(id)arg1;

@end

