//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KKTableViewController.h"

#import "JRJDropDownViewDataSource-Protocol.h"
#import "JRJDropDownViewDelegate-Protocol.h"

@class JRJDropDownView, JRJPortfolioListViewControllerHandler, NSArray, NSIndexPath, NSMutableArray, NSMutableDictionary, NSNumber, NSString;

@interface JRJPortfolioListViewController : KKTableViewController <JRJDropDownViewDelegate, JRJDropDownViewDataSource>
{
    _Bool _flag;
    _Bool _isLoadMore;
    _Bool _isDefaultRefresh;
    _Bool _isFirstFetch;
    NSIndexPath *_defaultIndexPath;
    NSNumber *_defaultOrderBySelected;
    NSNumber *_defaultPriceSelected;
    JRJDropDownView *_dropDownView;
    JRJPortfolioListViewControllerHandler *_handler;
    NSMutableDictionary *_indexPaths;
    NSMutableArray *_topViewTitleArray;
    NSMutableArray *_topViewInfoArray;
    NSArray *_defaultRunStatusArray;
    NSMutableArray *_selectedRowCopy;
    NSString *_chosenStatus;
    NSMutableArray *_trackKeyArray;
}

@property(retain, nonatomic) NSMutableArray *trackKeyArray; // @synthesize trackKeyArray=_trackKeyArray;
@property(copy, nonatomic) NSString *chosenStatus; // @synthesize chosenStatus=_chosenStatus;
@property(nonatomic) _Bool isFirstFetch; // @synthesize isFirstFetch=_isFirstFetch;
@property(nonatomic) _Bool isDefaultRefresh; // @synthesize isDefaultRefresh=_isDefaultRefresh;
@property(nonatomic) _Bool isLoadMore; // @synthesize isLoadMore=_isLoadMore;
@property(retain, nonatomic) NSMutableArray *selectedRowCopy; // @synthesize selectedRowCopy=_selectedRowCopy;
@property(retain, nonatomic) NSArray *defaultRunStatusArray; // @synthesize defaultRunStatusArray=_defaultRunStatusArray;
@property(retain, nonatomic) NSMutableArray *topViewInfoArray; // @synthesize topViewInfoArray=_topViewInfoArray;
@property(retain, nonatomic) NSMutableArray *topViewTitleArray; // @synthesize topViewTitleArray=_topViewTitleArray;
@property(retain, nonatomic) NSMutableDictionary *indexPaths; // @synthesize indexPaths=_indexPaths;
@property(nonatomic) _Bool flag; // @synthesize flag=_flag;
@property(retain, nonatomic) JRJPortfolioListViewControllerHandler *handler; // @synthesize handler=_handler;
@property(retain, nonatomic) JRJDropDownView *dropDownView; // @synthesize dropDownView=_dropDownView;
@property(retain, nonatomic) NSNumber *defaultPriceSelected; // @synthesize defaultPriceSelected=_defaultPriceSelected;
@property(retain, nonatomic) NSNumber *defaultOrderBySelected; // @synthesize defaultOrderBySelected=_defaultOrderBySelected;
@property(retain, nonatomic) NSIndexPath *defaultIndexPath; // @synthesize defaultIndexPath=_defaultIndexPath;
- (void).cxx_destruct;
- (void)toggleCellAtIndexPath:(id)arg1;
- (void)doTrack:(id)arg1;
- (long long)runStatusClickedAtRow:(id)arg1;
- (id)requesetUrl;
- (void)refreshTopInfoArray:(id)arg1;
- (void)loadListRequest;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)fetchList;
- (_Bool)isValidClick:(id)arg1;
- (void)dropDownView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)dropDownView:(id)arg1 titleForSection:(long long)arg2;
- (id)dropDownView:(id)arg1 itemForRowAtIndexPath:(id)arg2;
- (long long)dropDownView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInDropDownView:(id)arg1;
- (void)delayLoadMore;
- (void)reloadDataSource;
- (void)shieldBtnClicked;
- (void)addShieldButton;
- (void)addGuideTip;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

