//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Mantle/MTLModel.h>

#import "MTLJSONSerializing-Protocol.h"

@class NSArray, NSNumber, NSString, NSURL;

@interface JRJPortfolioV3 : MTLModel <MTLJSONSerializing>
{
    _Bool _isReceiveMsg;
    _Bool _isForMasterList;
    _Bool _isWeekRank;
    _Bool _historyExpanded;
    NSString *_userId;
    NSString *_userName;
    NSNumber *_portfolioId;
    NSURL *_avatarURL;
    NSString *_company;
    NSString *_portfolioName;
    NSNumber *_subscriptionPrice;
    NSNumber *_targetYield;
    NSNumber *_lossLine;
    NSNumber *_maxDuration;
    NSString *_startDate;
    NSString *_endDate;
    NSNumber *_portfolioStatus;
    NSNumber *_portfolioRunStatus;
    NSNumber *_currentyield;
    NSNumber *_showDate;
    NSString *_portfolioLabel;
    NSArray *_portfolioList;
    NSNumber *_portfolioType;
    NSNumber *_weekYield;
    NSNumber *_totalRank;
    NSNumber *_weekRank;
    NSNumber *_msgStatus;
    NSString *_currentyieldString;
    NSString *_targetYieldString;
    NSString *_maxDurationString;
    NSString *_lossLineString;
    NSString *_subscriptionPriceString;
    NSString *_showDateString;
    NSString *_weekYieldString;
    NSString *_runStatusString;
    NSString *_countString;
    NSString *_monthYieldString;
}

+ (id)portfolioListJSONTransformer;
+ (id)avatarURLJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) _Bool historyExpanded; // @synthesize historyExpanded=_historyExpanded;
@property(copy, nonatomic) NSString *monthYieldString; // @synthesize monthYieldString=_monthYieldString;
@property(copy, nonatomic) NSString *countString; // @synthesize countString=_countString;
@property(copy, nonatomic) NSString *runStatusString; // @synthesize runStatusString=_runStatusString;
@property(nonatomic) _Bool isWeekRank; // @synthesize isWeekRank=_isWeekRank;
@property(nonatomic) _Bool isForMasterList; // @synthesize isForMasterList=_isForMasterList;
@property(nonatomic) _Bool isReceiveMsg; // @synthesize isReceiveMsg=_isReceiveMsg;
@property(copy, nonatomic) NSString *weekYieldString; // @synthesize weekYieldString=_weekYieldString;
@property(copy, nonatomic) NSString *showDateString; // @synthesize showDateString=_showDateString;
@property(copy, nonatomic) NSString *subscriptionPriceString; // @synthesize subscriptionPriceString=_subscriptionPriceString;
@property(copy, nonatomic) NSString *lossLineString; // @synthesize lossLineString=_lossLineString;
@property(copy, nonatomic) NSString *maxDurationString; // @synthesize maxDurationString=_maxDurationString;
@property(copy, nonatomic) NSString *targetYieldString; // @synthesize targetYieldString=_targetYieldString;
@property(copy, nonatomic) NSString *currentyieldString; // @synthesize currentyieldString=_currentyieldString;
@property(retain, nonatomic) NSNumber *msgStatus; // @synthesize msgStatus=_msgStatus;
@property(retain, nonatomic) NSNumber *weekRank; // @synthesize weekRank=_weekRank;
@property(retain, nonatomic) NSNumber *totalRank; // @synthesize totalRank=_totalRank;
@property(retain, nonatomic) NSNumber *weekYield; // @synthesize weekYield=_weekYield;
@property(retain, nonatomic) NSNumber *portfolioType; // @synthesize portfolioType=_portfolioType;
@property(retain, nonatomic) NSArray *portfolioList; // @synthesize portfolioList=_portfolioList;
@property(copy, nonatomic) NSString *portfolioLabel; // @synthesize portfolioLabel=_portfolioLabel;
@property(retain, nonatomic) NSNumber *showDate; // @synthesize showDate=_showDate;
@property(retain, nonatomic) NSNumber *currentyield; // @synthesize currentyield=_currentyield;
@property(retain, nonatomic) NSNumber *portfolioRunStatus; // @synthesize portfolioRunStatus=_portfolioRunStatus;
@property(retain, nonatomic) NSNumber *portfolioStatus; // @synthesize portfolioStatus=_portfolioStatus;
@property(copy, nonatomic) NSString *endDate; // @synthesize endDate=_endDate;
@property(copy, nonatomic) NSString *startDate; // @synthesize startDate=_startDate;
@property(retain, nonatomic) NSNumber *maxDuration; // @synthesize maxDuration=_maxDuration;
@property(retain, nonatomic) NSNumber *lossLine; // @synthesize lossLine=_lossLine;
@property(retain, nonatomic) NSNumber *targetYield; // @synthesize targetYield=_targetYield;
@property(retain, nonatomic) NSNumber *subscriptionPrice; // @synthesize subscriptionPrice=_subscriptionPrice;
@property(copy, nonatomic) NSString *portfolioName; // @synthesize portfolioName=_portfolioName;
@property(copy, nonatomic) NSString *company; // @synthesize company=_company;
@property(copy, nonatomic) NSURL *avatarURL; // @synthesize avatarURL=_avatarURL;
@property(retain, nonatomic) NSNumber *portfolioId; // @synthesize portfolioId=_portfolioId;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (id)dealPortfolioNum:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

