//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface JRJReportPosterModel : NSObject
{
    NSString *_showDate;
    NSString *_imgDesc;
    NSString *_imgUrl;
    UIImage *_moon;
    NSString *_timestamp;
    NSString *_showContent;
    NSString *_title;
    NSString *_logicStep1;
    NSString *_logicStep2;
    NSString *_logicStep3;
}

@property(copy, nonatomic) NSString *logicStep3; // @synthesize logicStep3=_logicStep3;
@property(copy, nonatomic) NSString *logicStep2; // @synthesize logicStep2=_logicStep2;
@property(copy, nonatomic) NSString *logicStep1; // @synthesize logicStep1=_logicStep1;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *showContent; // @synthesize showContent=_showContent;
@property(copy, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) UIImage *moon; // @synthesize moon=_moon;
@property(copy, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
@property(copy, nonatomic) NSString *imgDesc; // @synthesize imgDesc=_imgDesc;
@property(copy, nonatomic) NSString *showDate; // @synthesize showDate=_showDate;
- (void).cxx_destruct;

@end

