//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Mantle/MTLModel.h>

#import "MTLJSONSerializing-Protocol.h"

@class NSArray, NSAttributedString, NSDate, NSNumber, NSString, NSURL;

@interface JRJReference : MTLModel <MTLJSONSerializing>
{
    _Bool _purchased;
    _Bool _expanding;
    _Bool _updating;
    _Bool _longTerm;
    NSString *_referenceId;
    NSString *_name;
    NSString *_desc;
    NSURL *_thumbURL;
    NSString *_userId;
    NSString *_userName;
    NSURL *_userAvatarURL;
    NSNumber *_price;
    NSNumber *_signedPrice;
    NSNumber *_appPrice;
    NSString *_appPriceString;
    NSNumber *_viewpointNumbers;
    long long _status;
    long long _type;
    NSDate *_startDate;
    NSDate *_endDate;
    NSString *_startDateString;
    NSString *_endDateString;
    NSString *_subscriptionDateString;
    NSNumber *_subscriberNumbers;
    NSString *_subscriberNumbersStr;
    NSNumber *_unreadNumbers;
    NSNumber *_signStatus;
    NSNumber *_ctime;
    NSString *_message;
    NSNumber *_finalPrice;
    NSString *_validity;
    NSAttributedString *_validityPeriod;
    NSString *_subscriberNumbersString;
    NSString *_statusImageName;
    NSString *_suittypeStr;
    NSArray *_options;
    long long _payTimeType;
    long long _payTimeNums;
    long long _begintime;
    NSNumber *_signedPrice2;
    NSString *_referenceId2;
}

+ (long long)daysBetweenDate:(id)arg1 andDate:(id)arg2;
+ (id)dateFormatter;
+ (id)optionsJSONTransformer;
+ (id)subscriptionDateStringJSONTransformer;
+ (id)appPriceJSONTransformer;
+ (id)signedPrice2JSONTransformer;
+ (id)signedPriceJSONTransformer;
+ (id)priceJSONTransformer;
+ (id)endDateJSONTransformer;
+ (id)referenceIdJSONTransformer;
+ (id)startDateJSONTransformer;
+ (id)userAvatarURLJSONTransformer;
+ (id)thumbURLJSONTransformer;
+ (id)nameJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(copy, nonatomic) NSString *referenceId2; // @synthesize referenceId2=_referenceId2;
@property(copy, nonatomic) NSNumber *signedPrice2; // @synthesize signedPrice2=_signedPrice2;
@property(nonatomic) long long begintime; // @synthesize begintime=_begintime;
@property(nonatomic) long long payTimeNums; // @synthesize payTimeNums=_payTimeNums;
@property(nonatomic) long long payTimeType; // @synthesize payTimeType=_payTimeType;
@property(copy, nonatomic) NSArray *options; // @synthesize options=_options;
@property(nonatomic) _Bool longTerm; // @synthesize longTerm=_longTerm;
@property(copy, nonatomic) NSString *suittypeStr; // @synthesize suittypeStr=_suittypeStr;
@property(nonatomic, getter=isUpdating) _Bool updating; // @synthesize updating=_updating;
@property(retain, nonatomic) NSString *statusImageName; // @synthesize statusImageName=_statusImageName;
@property(retain, nonatomic) NSString *subscriberNumbersString; // @synthesize subscriberNumbersString=_subscriberNumbersString;
@property(retain, nonatomic) NSAttributedString *validityPeriod; // @synthesize validityPeriod=_validityPeriod;
@property(retain, nonatomic) NSString *validity; // @synthesize validity=_validity;
@property(retain, nonatomic) NSNumber *finalPrice; // @synthesize finalPrice=_finalPrice;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic, getter=isExpanding) _Bool expanding; // @synthesize expanding=_expanding;
@property(retain, nonatomic) NSNumber *ctime; // @synthesize ctime=_ctime;
@property(retain, nonatomic) NSNumber *signStatus; // @synthesize signStatus=_signStatus;
@property(retain, nonatomic) NSNumber *unreadNumbers; // @synthesize unreadNumbers=_unreadNumbers;
@property(copy, nonatomic) NSString *subscriberNumbersStr; // @synthesize subscriberNumbersStr=_subscriberNumbersStr;
@property(copy, nonatomic) NSNumber *subscriberNumbers; // @synthesize subscriberNumbers=_subscriberNumbers;
@property(copy, nonatomic) NSString *subscriptionDateString; // @synthesize subscriptionDateString=_subscriptionDateString;
@property(copy, nonatomic) NSString *endDateString; // @synthesize endDateString=_endDateString;
@property(copy, nonatomic) NSString *startDateString; // @synthesize startDateString=_startDateString;
@property(retain, nonatomic) NSDate *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSNumber *viewpointNumbers; // @synthesize viewpointNumbers=_viewpointNumbers;
@property(nonatomic, getter=isPurchased) _Bool purchased; // @synthesize purchased=_purchased;
@property(retain, nonatomic) NSString *appPriceString; // @synthesize appPriceString=_appPriceString;
@property(retain, nonatomic) NSNumber *appPrice; // @synthesize appPrice=_appPrice;
@property(retain, nonatomic) NSNumber *signedPrice; // @synthesize signedPrice=_signedPrice;
@property(retain, nonatomic) NSNumber *price; // @synthesize price=_price;
@property(copy, nonatomic) NSURL *userAvatarURL; // @synthesize userAvatarURL=_userAvatarURL;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSURL *thumbURL; // @synthesize thumbURL=_thumbURL;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *referenceId; // @synthesize referenceId=_referenceId;
- (void).cxx_destruct;
- (id)weekdayOfDate:(id)arg1;
- (id)initWithDictionary:(id)arg1 error:(id *)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

