//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Mantle/MTLModel.h>

#import "MTLJSONSerializing-Protocol.h"

@class NSNumber, NSString;

@interface JRJReferenceSubscriptionOption : MTLModel <MTLJSONSerializing>
{
    NSString *_ID;
    NSString *_beginTime;
    NSString *_endTime;
    NSNumber *_days;
    NSNumber *_months;
    long long _price;
    long long _originalPrice;
    NSNumber *_discount;
    NSString *_monthDescription;
    NSString *_discountDescription;
    long long _payTimeType;
    long long _payTimeNums;
}

+ (id)IDJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) long long payTimeNums; // @synthesize payTimeNums=_payTimeNums;
@property(nonatomic) long long payTimeType; // @synthesize payTimeType=_payTimeType;
@property(copy, nonatomic) NSString *discountDescription; // @synthesize discountDescription=_discountDescription;
@property(copy, nonatomic) NSString *monthDescription; // @synthesize monthDescription=_monthDescription;
@property(retain, nonatomic) NSNumber *discount; // @synthesize discount=_discount;
@property(nonatomic) long long originalPrice; // @synthesize originalPrice=_originalPrice;
@property(nonatomic) long long price; // @synthesize price=_price;
@property(retain, nonatomic) NSNumber *months; // @synthesize months=_months;
@property(retain, nonatomic) NSNumber *days; // @synthesize days=_days;
@property(copy, nonatomic) NSString *endTime; // @synthesize endTime=_endTime;
@property(copy, nonatomic) NSString *beginTime; // @synthesize beginTime=_beginTime;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

