//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJListTableViewController.h"

#import "JRJReferenceDateDropViewDelegate-Protocol.h"

@class JRJAdviser, JRJCourse, JRJReference, JRJReferenceDateDropView, JRJReferenceSubscriptionHelper, NSString, ReferenceDateHisDateModel, UIBarButtonItem, UIView;

@interface JRJReferenceViewpointViewController : JRJListTableViewController <JRJReferenceDateDropViewDelegate>
{
    _Bool _isDaren;
    _Bool _fromMyReferences;
    _Bool _noData;
    NSString *_referenceId;
    JRJAdviser *_adviser;
    JRJReference *_reference;
    UIView *_heguiView;
    JRJReferenceSubscriptionHelper *_subscriptionHelper;
    JRJReferenceDateDropView *_dropV;
    ReferenceDateHisDateModel *_currentM;
    UIBarButtonItem *_renewBarButtonItem;
    JRJCourse *_relatedCourse;
}

@property(retain, nonatomic) JRJCourse *relatedCourse; // @synthesize relatedCourse=_relatedCourse;
@property(retain, nonatomic) UIBarButtonItem *renewBarButtonItem; // @synthesize renewBarButtonItem=_renewBarButtonItem;
@property(retain, nonatomic) ReferenceDateHisDateModel *currentM; // @synthesize currentM=_currentM;
@property(retain, nonatomic) JRJReferenceDateDropView *dropV; // @synthesize dropV=_dropV;
@property(retain, nonatomic) JRJReferenceSubscriptionHelper *subscriptionHelper; // @synthesize subscriptionHelper=_subscriptionHelper;
@property(retain, nonatomic) UIView *heguiView; // @synthesize heguiView=_heguiView;
@property(nonatomic) _Bool noData; // @synthesize noData=_noData;
@property(retain, nonatomic) JRJReference *reference; // @synthesize reference=_reference;
@property(retain, nonatomic) JRJAdviser *adviser; // @synthesize adviser=_adviser;
@property(nonatomic) _Bool fromMyReferences; // @synthesize fromMyReferences=_fromMyReferences;
@property(nonatomic) _Bool isDaren; // @synthesize isDaren=_isDaren;
@property(retain, nonatomic) NSString *referenceId; // @synthesize referenceId=_referenceId;
- (void).cxx_destruct;
- (void)openRelatedCourse;
- (void)bgControlDidSelected;
- (void)showLoadingViewWithState:(long long)arg1;
- (void)showAdviserDetail;
- (void)addLineToCell:(id)arg1 padding:(double)arg2 top:(double)arg3;
- (void)addLineToCell:(id)arg1 padding:(double)arg2;
- (void)sendMessage:(id)arg1;
- (void)renew:(id)arg1;
- (id)viewpointCellAtIndexPath:(id)arg1;
- (id)noDataCellAtIndexPath:(id)arg1;
- (id)presellingCellAtIndexPath:(id)arg1;
- (id)infoCellAtIndexPath:(id)arg1;
- (id)titleCellAtIndexPath:(id)arg1;
- (id)loadMoreCellAtIndexPath:(id)arg1;
- (id)referenceDteCellWithTableview:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)referenceDateDropDidSelected:(id)arg1 andDateM:(id)arg2;
- (void)handleRequestDataArray:(id)arg1;
- (void)loadDataWithTid:(long long)arg1;
- (void)loadListRequest;
- (void)loadData;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)viewDidLoad;
- (id)initWithReferenceId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

