//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface JRJRelatedInvestReferenceItem : UIView
{
    _Bool _hiddenService;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UILabel *_servicePeriodLabel;
    UILabel *_priceLabel;
    UILabel *_subscribeCountLabel;
    UIButton *_subscribeButton;
}

@property(nonatomic) _Bool hiddenService; // @synthesize hiddenService=_hiddenService;
@property(retain, nonatomic) UIButton *subscribeButton; // @synthesize subscribeButton=_subscribeButton;
@property(retain, nonatomic) UILabel *subscribeCountLabel; // @synthesize subscribeCountLabel=_subscribeCountLabel;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) UILabel *servicePeriodLabel; // @synthesize servicePeriodLabel=_servicePeriodLabel;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void).cxx_destruct;
- (void)layoutPageSubviews;
- (id)init;

@end

