//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface JRJResearchReportListContentModel : NSObject
{
    _Bool _isNew;
    _Bool _subStatus;
    _Bool _favorStatus;
    _Bool _read;
    NSString *_title;
    NSArray *_subTitles;
    NSString *_ID;
    NSArray *_stocks;
    long long _subTotal;
    long long _favorTotal;
    NSString *_pubTime;
}

+ (id)modelContainerPropertyGenericClass;
+ (id)modelCustomPropertyMapper;
@property(nonatomic) _Bool read; // @synthesize read=_read;
@property(copy, nonatomic) NSString *pubTime; // @synthesize pubTime=_pubTime;
@property(nonatomic) long long favorTotal; // @synthesize favorTotal=_favorTotal;
@property(nonatomic) _Bool favorStatus; // @synthesize favorStatus=_favorStatus;
@property(nonatomic) long long subTotal; // @synthesize subTotal=_subTotal;
@property(nonatomic) _Bool subStatus; // @synthesize subStatus=_subStatus;
@property(retain, nonatomic) NSArray *stocks; // @synthesize stocks=_stocks;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
@property(retain, nonatomic) NSArray *subTitles; // @synthesize subTitles=_subTitles;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool isNew; // @synthesize isNew=_isNew;
- (void).cxx_destruct;

@end

