//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YCBBaseTableViewCell.h"

@class JRJReference, NSLayoutConstraint, RiskInfoModel, UIButton, UIImageView, UILabel, UIView;
@protocol JRJReferenceCellDelegate;

@interface JRJReferenceCell : YCBBaseTableViewCell
{
    RiskInfoModel *_riskInfo;
    JRJReference *_refrenceM;
    id <JRJReferenceCellDelegate> _delegate;
    UIButton *_subBtn;
    UIImageView *_iconImageView;
    UILabel *_titleL;
    UILabel *_dateL;
    UILabel *_moneyIconL;
    UILabel *_moneyL;
    UILabel *_qiLabel;
    UILabel *_numL;
    UILabel *_originalMoneyL;
    UIView *_originalMoneyThroughLine;
    UIImageView *_lineIV;
    UIButton *_statusBtn;
    UILabel *_riskLabel;
    UIImageView *_img_risk;
    NSLayoutConstraint *_numLeftConstraint;
    NSLayoutConstraint *_numCenterYConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *numCenterYConstraint; // @synthesize numCenterYConstraint=_numCenterYConstraint;
@property(nonatomic) __weak NSLayoutConstraint *numLeftConstraint; // @synthesize numLeftConstraint=_numLeftConstraint;
@property(nonatomic) __weak UIImageView *img_risk; // @synthesize img_risk=_img_risk;
@property(nonatomic) __weak UILabel *riskLabel; // @synthesize riskLabel=_riskLabel;
@property(nonatomic) __weak UIButton *statusBtn; // @synthesize statusBtn=_statusBtn;
@property(nonatomic) __weak UIImageView *lineIV; // @synthesize lineIV=_lineIV;
@property(nonatomic) __weak UIView *originalMoneyThroughLine; // @synthesize originalMoneyThroughLine=_originalMoneyThroughLine;
@property(nonatomic) __weak UILabel *originalMoneyL; // @synthesize originalMoneyL=_originalMoneyL;
@property(nonatomic) __weak UILabel *numL; // @synthesize numL=_numL;
@property(nonatomic) __weak UILabel *qiLabel; // @synthesize qiLabel=_qiLabel;
@property(nonatomic) __weak UILabel *moneyL; // @synthesize moneyL=_moneyL;
@property(nonatomic) __weak UILabel *moneyIconL; // @synthesize moneyIconL=_moneyIconL;
@property(nonatomic) __weak UILabel *dateL; // @synthesize dateL=_dateL;
@property(nonatomic) __weak UILabel *titleL; // @synthesize titleL=_titleL;
@property(nonatomic) __weak UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak UIButton *subBtn; // @synthesize subBtn=_subBtn;
@property(nonatomic) __weak id <JRJReferenceCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) JRJReference *refrenceM; // @synthesize refrenceM=_refrenceM;
@property(retain, nonatomic) RiskInfoModel *riskInfo; // @synthesize riskInfo=_riskInfo;
- (void).cxx_destruct;
- (void)hideNumLabel;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)subButtonDidPressed:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;

@end

