//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "InterPreferenceViewModel.h"

@class NSString;

@interface JRJRelatedInvestReferenceModel : InterPreferenceViewModel
{
    NSString *_stockcode;
    long long _stockcount;
    NSString *_stockname;
}

+ (id)modelCustomPropertyMapper;
@property(copy, nonatomic) NSString *stockname; // @synthesize stockname=_stockname;
@property(nonatomic) long long stockcount; // @synthesize stockcount=_stockcount;
@property(copy, nonatomic) NSString *stockcode; // @synthesize stockcode=_stockcode;
- (void).cxx_destruct;

@end

