//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJPassportFormViewController.h"

@class JRJFormTextFieldCell, NSString;
@protocol JRJRegisterNicknameViewControllerDelegate;

@interface JRJRegisterNicknameViewController : JRJPassportFormViewController
{
    _Bool _showsSkipButton;
    id <JRJRegisterNicknameViewControllerDelegate> _delegate;
    CDUnknownBlockType _didCancelBlock;
    CDUnknownBlockType _didFinishBlock;
    NSString *_pageTitle;
    JRJFormTextFieldCell *_nickNameCell;
}

@property(retain, nonatomic) JRJFormTextFieldCell *nickNameCell; // @synthesize nickNameCell=_nickNameCell;
@property(copy, nonatomic) NSString *pageTitle; // @synthesize pageTitle=_pageTitle;
@property(copy, nonatomic) CDUnknownBlockType didFinishBlock; // @synthesize didFinishBlock=_didFinishBlock;
@property(copy, nonatomic) CDUnknownBlockType didCancelBlock; // @synthesize didCancelBlock=_didCancelBlock;
@property(nonatomic) _Bool showsSkipButton; // @synthesize showsSkipButton=_showsSkipButton;
@property(nonatomic) __weak id <JRJRegisterNicknameViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)skipButtonTapped:(id)arg1;
- (void)submitButtonTapped:(id)arg1;
- (void)stateChanged;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)loadNickName;
- (void)willMoveToParentViewController:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)initCustomNavigatiobBar;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

