//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface JRJReportPosterApi : NSObject
{
    long long _product;
    NSString *_reportId;
}

@property(copy, nonatomic) NSString *reportId; // @synthesize reportId=_reportId;
@property(nonatomic) long long product; // @synthesize product=_product;
- (void).cxx_destruct;
- (void)downloadMoonIcon:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)makingPoster;

@end

