//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseCell.h"

@class JRJReference, UIImageView, UILabel, UIView;

@interface JRJReferenceTitleCell : JRJBaseCell
{
    UILabel *_titleLabel;
    UIImageView *_statusImageView;
    UIView *_redDotView;
    JRJReference *_reference;
}

+ (double)cellHeight;
@property(retain, nonatomic) JRJReference *reference; // @synthesize reference=_reference;
@property(nonatomic) __weak UIView *redDotView; // @synthesize redDotView=_redDotView;
@property(nonatomic) __weak UIImageView *statusImageView; // @synthesize statusImageView=_statusImageView;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

