//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class JRJResearchReportProductPriceModel, NSIndexPath, UIButton, UILabel;

@interface JRJResearchReportPriceListCell : UITableViewCell
{
    _Bool _cellSelected;
    JRJResearchReportProductPriceModel *_model;
    NSIndexPath *_indexPath;
    CDUnknownBlockType _selecteBlock;
    UILabel *_priceLabel;
    UILabel *_timeLabel;
    UILabel *_originalPriceLabel;
    UILabel *_discountPriceLabel;
    UIButton *_selectedBtn;
}

@property(retain, nonatomic) UIButton *selectedBtn; // @synthesize selectedBtn=_selectedBtn;
@property(retain, nonatomic) UILabel *discountPriceLabel; // @synthesize discountPriceLabel=_discountPriceLabel;
@property(retain, nonatomic) UILabel *originalPriceLabel; // @synthesize originalPriceLabel=_originalPriceLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(nonatomic) _Bool cellSelected; // @synthesize cellSelected=_cellSelected;
@property(copy, nonatomic) CDUnknownBlockType selecteBlock; // @synthesize selecteBlock=_selecteBlock;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(retain, nonatomic) JRJResearchReportProductPriceModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)clicked:(id)arg1;
- (void)buildUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

