//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KKTableViewController.h"

@class JRJReverseReposHandler, JRJReverseReposMainView, JRJTradeBuyAndSellHandler, JRJTradeBuyAndSellRiskInfoModel, NSDictionary, NSString, NSTimer, SASnapShotHandler;

@interface JRJReverseReposMainVC : KKTableViewController
{
    JRJReverseReposMainView *_headerView;
    JRJReverseReposHandler *_reverseHandler;
    JRJTradeBuyAndSellHandler *_buySellHandler;
    SASnapShotHandler *_snapShotHandler;
    NSTimer *_timer;
    JRJTradeBuyAndSellRiskInfoModel *_buyRiskInfoModel;
    NSString *_code;
    long long _type;
    NSDictionary *_paramDic;
}

@property(retain, nonatomic) NSDictionary *paramDic; // @synthesize paramDic=_paramDic;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(retain, nonatomic) JRJTradeBuyAndSellRiskInfoModel *buyRiskInfoModel; // @synthesize buyRiskInfoModel=_buyRiskInfoModel;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) SASnapShotHandler *snapShotHandler; // @synthesize snapShotHandler=_snapShotHandler;
@property(retain, nonatomic) JRJTradeBuyAndSellHandler *buySellHandler; // @synthesize buySellHandler=_buySellHandler;
@property(retain, nonatomic) JRJReverseReposHandler *reverseHandler; // @synthesize reverseHandler=_reverseHandler;
@property(retain, nonatomic) JRJReverseReposMainView *headerView; // @synthesize headerView=_headerView;
- (void).cxx_destruct;
- (void)setCurrentTitle:(id)arg1;
- (double)getStockPriceWith:(id)arg1;
- (id)getExchangeType;
- (void)scrollViewDidScroll:(id)arg1;
- (void)buyOrSellFinish;
- (void)reLogin;
- (void)confirmBuyStockWithParamDic:(id)arg1;
- (void)getFivePriceWithCode:(id)arg1;
- (void)startTimerWithStockCode:(id)arg1;
- (void)stockDealWithDic:(id)arg1;
- (void)getMaxNumberPriceWithStockCode:(id)arg1 price:(id)arg2 exchangeType:(id)arg3 entrustBs:(id)arg4 placeholder:(_Bool)arg5;
- (void)getStockInfoWithCode:(id)arg1;
- (void)getInfoRequest;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCode:(id)arg1;

@end

