//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "FSCalendarDataSource-Protocol.h"
#import "FSCalendarDelegate-Protocol.h"

@class FSCalendar, NSCalendar, NSDateFormatter, NSString, UIButton, UILabel;

@interface JRJStrategyCalendarPopView : UIView <FSCalendarDataSource, FSCalendarDelegate>
{
    UIButton *_leftUIButton;
    UIButton *_rightUIbutton;
    UILabel *_dateTitleUIlabel;
    FSCalendar *_dateFSCalendar;
    NSDateFormatter *_formatter;
    NSCalendar *_gregorian;
    CDUnknownBlockType _selectDateBlock;
}

@property(copy, nonatomic) CDUnknownBlockType selectDateBlock; // @synthesize selectDateBlock=_selectDateBlock;
@property(retain, nonatomic) NSCalendar *gregorian; // @synthesize gregorian=_gregorian;
@property(copy, nonatomic) NSDateFormatter *formatter; // @synthesize formatter=_formatter;
@property(retain, nonatomic) FSCalendar *dateFSCalendar; // @synthesize dateFSCalendar=_dateFSCalendar;
@property(retain, nonatomic) UILabel *dateTitleUIlabel; // @synthesize dateTitleUIlabel=_dateTitleUIlabel;
@property(retain, nonatomic) UIButton *rightUIbutton; // @synthesize rightUIbutton=_rightUIbutton;
@property(retain, nonatomic) UIButton *leftUIButton; // @synthesize leftUIButton=_leftUIButton;
- (void).cxx_destruct;
- (id)maximumDateForCalendar:(id)arg1;
- (void)calendar:(id)arg1 didSelectDate:(id)arg2 atMonthPosition:(unsigned long long)arg3;
- (void)p_nextMonth;
- (void)p_previousMonth;
- (void)calendarCurrentPageDidChange:(id)arg1;
- (void)calendarSelectedDateWithDateStr:(id)arg1;
- (void)p_configBaseDate;
- (void)clickRightUIbutton:(id)arg1;
- (void)clickLeftUIbutton:(id)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

