//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton;

@interface JRJStockHotButtonCell : UITableViewCell
{
    UIButton *_stockUpButton;
    UIButton *_changeButton;
    UIButton *_fiveMinuteUpButton;
    UIButton *_stockDownButton;
    UIButton *_amplitudeButton;
    UIButton *_fiveMinuteDownButton;
    CDUnknownBlockType _didSelectBlock;
}

+ (double)cellHeight;
@property(copy, nonatomic) CDUnknownBlockType didSelectBlock; // @synthesize didSelectBlock=_didSelectBlock;
@property(nonatomic) __weak UIButton *fiveMinuteDownButton; // @synthesize fiveMinuteDownButton=_fiveMinuteDownButton;
@property(nonatomic) __weak UIButton *amplitudeButton; // @synthesize amplitudeButton=_amplitudeButton;
@property(nonatomic) __weak UIButton *stockDownButton; // @synthesize stockDownButton=_stockDownButton;
@property(nonatomic) __weak UIButton *fiveMinuteUpButton; // @synthesize fiveMinuteUpButton=_fiveMinuteUpButton;
@property(nonatomic) __weak UIButton *changeButton; // @synthesize changeButton=_changeButton;
@property(nonatomic) __weak UIButton *stockUpButton; // @synthesize stockUpButton=_stockUpButton;
- (void).cxx_destruct;
- (void)hshshs:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

