//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YCBBaseTableViewCell.h"

@class JRJOutFundModel, NSDictionary, SecuritySummary, UIButton, UILabel;
@protocol JRJGlobalSearchDelegate;

@interface JRJSearchStockCell : YCBBaseTableViewCell
{
    UILabel *_codeNumL;
    UILabel *_titleL;
    NSDictionary *_stock;
    SecuritySummary *_item;
    id <JRJGlobalSearchDelegate> _delegate;
    JRJOutFundModel *_fundModel;
    UIButton *_followBtn;
    UILabel *_selectedLabel;
}

+ (double)heightForCell;
@property(retain, nonatomic) UILabel *selectedLabel; // @synthesize selectedLabel=_selectedLabel;
@property(nonatomic) __weak UIButton *followBtn; // @synthesize followBtn=_followBtn;
@property(retain, nonatomic) JRJOutFundModel *fundModel; // @synthesize fundModel=_fundModel;
@property(nonatomic) __weak id <JRJGlobalSearchDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SecuritySummary *item; // @synthesize item=_item;
@property(retain, nonatomic) NSDictionary *stock; // @synthesize stock=_stock;
@property(retain, nonatomic) UILabel *titleL; // @synthesize titleL=_titleL;
@property(retain, nonatomic) UILabel *codeNumL; // @synthesize codeNumL=_codeNumL;
- (void).cxx_destruct;
- (void)layoutPageSubviews;
- (void)followButtonDidPressed:(id)arg1;
- (void)awakeFromNib;

@end

