//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray;

@interface JRJShortcutsView : UIView
{
    NSArray *_shortcutsItems;
    CDUnknownBlockType _shortcutsViewClickedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType shortcutsViewClickedBlock; // @synthesize shortcutsViewClickedBlock=_shortcutsViewClickedBlock;
@property(retain, nonatomic) NSArray *shortcutsItems; // @synthesize shortcutsItems=_shortcutsItems;
- (void).cxx_destruct;
- (void)buttonClicked:(id)arg1;
- (id)itemViewAtIndex:(long long)arg1 Item:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

