//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSLayoutConstraint, UIImageView, UILabel, UIView;

@interface JRJStockMarketGridCollectionViewCell : UICollectionViewCell
{
    _Bool _hidesStockName;
    UIView *_rightLine;
    UILabel *_nameLabel;
    UILabel *_mainLabel;
    UILabel *_stockNameLabel;
    UILabel *_detailLabel;
    UIImageView *_upOrDownImage;
    NSLayoutConstraint *_topPaddingConstraint;
    NSLayoutConstraint *_detailLabelTopMarginConstraint;
    NSLayoutConstraint *_imageViewTrailingConstraint;
    NSLayoutConstraint *_priceTopMarginConstraint;
}

+ (double)cellHeight;
@property(nonatomic) __weak NSLayoutConstraint *priceTopMarginConstraint; // @synthesize priceTopMarginConstraint=_priceTopMarginConstraint;
@property(nonatomic) __weak NSLayoutConstraint *imageViewTrailingConstraint; // @synthesize imageViewTrailingConstraint=_imageViewTrailingConstraint;
@property(nonatomic) __weak NSLayoutConstraint *detailLabelTopMarginConstraint; // @synthesize detailLabelTopMarginConstraint=_detailLabelTopMarginConstraint;
@property(nonatomic) __weak NSLayoutConstraint *topPaddingConstraint; // @synthesize topPaddingConstraint=_topPaddingConstraint;
@property(nonatomic) _Bool hidesStockName; // @synthesize hidesStockName=_hidesStockName;
@property(nonatomic) __weak UIImageView *upOrDownImage; // @synthesize upOrDownImage=_upOrDownImage;
@property(nonatomic) __weak UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(nonatomic) __weak UILabel *stockNameLabel; // @synthesize stockNameLabel=_stockNameLabel;
@property(nonatomic) __weak UILabel *mainLabel; // @synthesize mainLabel=_mainLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UIView *rightLine; // @synthesize rightLine=_rightLine;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)awakeFromNib;

@end

