//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseViewController.h"

#import "FSPageContentViewDelegate-Protocol.h"
#import "FSSegmentTitleViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class FSSegmentTitleView, JRJMineNavigationBar, JRJRefreshHeaderView, JRJSimHoldPositionHandler, JRJSimMainHeader, JRJSimTradeRecordVC, JRJStockFriendsTouTiaoView, JRJUserDetailsBottomCell, JRJUserDetialBaseTableview, NSArray, NSDictionary, NSString, TradeAlertView, UIView;

@interface JRJSimHoldPositionMainVC : JRJBaseViewController <UITableViewDelegate, UITableViewDataSource, FSPageContentViewDelegate, FSSegmentTitleViewDelegate>
{
    _Bool _canScroll;
    JRJRefreshHeaderView *_refreshHeaderView;
    JRJUserDetialBaseTableview *_tableView;
    JRJUserDetailsBottomCell *_contentCell;
    FSSegmentTitleView *_sectionTitleView;
    JRJSimMainHeader *_headerView;
    UIView *_sectionFooterView;
    JRJSimHoldPositionHandler *_handler;
    NSArray *_VPositionProfitArr;
    JRJSimTradeRecordVC *_simTradeRecordVC;
    TradeAlertView *_reminderAlert;
    JRJMineNavigationBar *_myNavigationBar;
    JRJStockFriendsTouTiaoView *_stockFriendsTouTiaoView;
    NSDictionary *_userTradeAbilityInfo;
}

@property(retain, nonatomic) NSDictionary *userTradeAbilityInfo; // @synthesize userTradeAbilityInfo=_userTradeAbilityInfo;
@property(retain, nonatomic) JRJStockFriendsTouTiaoView *stockFriendsTouTiaoView; // @synthesize stockFriendsTouTiaoView=_stockFriendsTouTiaoView;
@property(retain, nonatomic) JRJMineNavigationBar *myNavigationBar; // @synthesize myNavigationBar=_myNavigationBar;
@property(retain, nonatomic) TradeAlertView *reminderAlert; // @synthesize reminderAlert=_reminderAlert;
@property(retain, nonatomic) JRJSimTradeRecordVC *simTradeRecordVC; // @synthesize simTradeRecordVC=_simTradeRecordVC;
@property(retain, nonatomic) NSArray *VPositionProfitArr; // @synthesize VPositionProfitArr=_VPositionProfitArr;
@property(retain, nonatomic) JRJSimHoldPositionHandler *handler; // @synthesize handler=_handler;
@property(retain, nonatomic) UIView *sectionFooterView; // @synthesize sectionFooterView=_sectionFooterView;
@property(retain, nonatomic) JRJSimMainHeader *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) _Bool canScroll; // @synthesize canScroll=_canScroll;
@property(retain, nonatomic) FSSegmentTitleView *sectionTitleView; // @synthesize sectionTitleView=_sectionTitleView;
@property(retain, nonatomic) JRJUserDetailsBottomCell *contentCell; // @synthesize contentCell=_contentCell;
@property(retain, nonatomic) JRJUserDetialBaseTableview *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) JRJRefreshHeaderView *refreshHeaderView; // @synthesize refreshHeaderView=_refreshHeaderView;
- (void).cxx_destruct;
- (id)title;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)FSContentViewDidScroll:(id)arg1 startIndex:(long long)arg2 endIndex:(long long)arg3 progress:(double)arg4;
- (void)FSSegmentTitleView:(id)arg1 startIndex:(long long)arg2 endIndex:(long long)arg3;
- (void)FSContenViewDidEndDecelerating:(id)arg1 startIndex:(long long)arg2 endIndex:(long long)arg3;
- (void)changeScrollStatus;
- (void)p_isShowStockFriendsView:(_Bool)arg1;
- (void)p_checkShowReminderAlert;
- (void)requestVPProfitNoticeInfo;
- (void)requestUserTradeAbilityInfo;
- (void)requestVPositionProfitInfo;
- (void)requestZPointSmartAuth;
- (void)requestBegin;
- (void)insertRowAtTop;
- (void)endRefresh;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)refreshViewStateChanged:(id)arg1;
- (void)initRefreshView;
- (void)p_showRemindAlert;
- (void)p_personBackBarButtonitemClick;
- (id)p_navRightButtonItem;
- (id)p_personBackButtonItem;
- (void)p_setNavigationItemBarButton;
- (void)configSubViews;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

