//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface JRJStockTrendAnalysisHeader : UIView
{
    UILabel *_descUILabel;
    CDUnknownBlockType _dismissHeaderBlock;
    CDUnknownBlockType _gestureTapBlock;
}

@property(copy, nonatomic) CDUnknownBlockType gestureTapBlock; // @synthesize gestureTapBlock=_gestureTapBlock;
@property(copy, nonatomic) CDUnknownBlockType dismissHeaderBlock; // @synthesize dismissHeaderBlock=_dismissHeaderBlock;
@property(nonatomic) __weak UILabel *descUILabel; // @synthesize descUILabel=_descUILabel;
- (void).cxx_destruct;
- (id)getAttributedStringWithString:(id)arg1 lineSpace:(double)arg2;
- (void)dismissHeader:(id)arg1;
- (void)awakeFromNib;

@end

