//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class JRJShortChartKlineView, NSDictionary, UIImageView, UILabel, UIView;

@interface JRJShortDiagnoseCell : JRJTableViewCell
{
    UILabel *_situationLabel;
    UILabel *_industryLabel;
    UILabel *_subHeadLabel;
    UILabel *_leftNameLabel;
    UILabel *_leftRateLabel;
    UILabel *_rightNameLabel;
    UILabel *_rightRateLabel;
    UIImageView *_leftStarImageView;
    UIImageView *_rightStarImageView;
    JRJShortChartKlineView *_klineView;
    UILabel *_leftDateLabel;
    UILabel *_rightDateLabel;
    UIView *_backView;
    NSDictionary *_dic;
}

@property(retain, nonatomic) NSDictionary *dic; // @synthesize dic=_dic;
@property(nonatomic) __weak UIView *backView; // @synthesize backView=_backView;
@property(nonatomic) __weak UILabel *rightDateLabel; // @synthesize rightDateLabel=_rightDateLabel;
@property(nonatomic) __weak UILabel *leftDateLabel; // @synthesize leftDateLabel=_leftDateLabel;
@property(nonatomic) __weak JRJShortChartKlineView *klineView; // @synthesize klineView=_klineView;
@property(nonatomic) __weak UIImageView *rightStarImageView; // @synthesize rightStarImageView=_rightStarImageView;
@property(nonatomic) __weak UIImageView *leftStarImageView; // @synthesize leftStarImageView=_leftStarImageView;
@property(nonatomic) __weak UILabel *rightRateLabel; // @synthesize rightRateLabel=_rightRateLabel;
@property(nonatomic) __weak UILabel *rightNameLabel; // @synthesize rightNameLabel=_rightNameLabel;
@property(nonatomic) __weak UILabel *leftRateLabel; // @synthesize leftRateLabel=_leftRateLabel;
@property(nonatomic) __weak UILabel *leftNameLabel; // @synthesize leftNameLabel=_leftNameLabel;
@property(nonatomic) __weak UILabel *subHeadLabel; // @synthesize subHeadLabel=_subHeadLabel;
@property(nonatomic) __weak UILabel *industryLabel; // @synthesize industryLabel=_industryLabel;
@property(nonatomic) __weak UILabel *situationLabel; // @synthesize situationLabel=_situationLabel;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)updateWithDic:(id)arg1;
- (void)awakeFromNib;

@end

