//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseCell.h"

@class UILabel;

@interface JRJSimInvestorCell : JRJBaseCell
{
    CDUnknownBlockType _anyliseBlock;
    UILabel *_zsSorce;
    UILabel *_zsName;
    UILabel *_userAbilityAvg;
    UILabel *_userName;
}

@property(nonatomic) __weak UILabel *userName; // @synthesize userName=_userName;
@property(nonatomic) __weak UILabel *userAbilityAvg; // @synthesize userAbilityAvg=_userAbilityAvg;
@property(nonatomic) __weak UILabel *zsName; // @synthesize zsName=_zsName;
@property(nonatomic) __weak UILabel *zsSorce; // @synthesize zsSorce=_zsSorce;
@property(copy, nonatomic) CDUnknownBlockType anyliseBlock; // @synthesize anyliseBlock=_anyliseBlock;
- (void).cxx_destruct;
- (void)updateCellWithParamDic:(id)arg1;
- (void)anyliseClick:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

