//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class JRJDapanChangeSegmentView, JRJMarketReadingFirstView, NSArray, NSMutableArray, NSString, UICollectionView, UIImageView, UIPageControl;

@interface JRJStockMarketGridScrollCell : UITableViewCell <UICollectionViewDelegate, UICollectionViewDataSource>
{
    CDUnknownBlockType _didSelectBlock;
    CDUnknownBlockType _didMoreBlock;
    CDUnknownBlockType _didMarketReadingFirstClickBlock;
    CDUnknownBlockType _didDapanChangeSegmentClickBlock;
    long long _columns;
    double _horizontalSeparatorPadding;
    NSArray *_data;
    long long _listType;
    NSMutableArray *_horizontalLines;
    UICollectionView *_collectionView;
    UIPageControl *_pageControl;
    UIImageView *_imageBack;
    JRJMarketReadingFirstView *_marketReadingFirstView;
    JRJDapanChangeSegmentView *_changeSegView;
}

+ (double)rowHeight;
@property(retain, nonatomic) JRJDapanChangeSegmentView *changeSegView; // @synthesize changeSegView=_changeSegView;
@property(retain, nonatomic) JRJMarketReadingFirstView *marketReadingFirstView; // @synthesize marketReadingFirstView=_marketReadingFirstView;
@property(nonatomic) __weak UIImageView *imageBack; // @synthesize imageBack=_imageBack;
@property(retain, nonatomic) UIPageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) NSMutableArray *horizontalLines; // @synthesize horizontalLines=_horizontalLines;
@property(nonatomic) long long listType; // @synthesize listType=_listType;
@property(retain, nonatomic) NSArray *data; // @synthesize data=_data;
@property(nonatomic) double horizontalSeparatorPadding; // @synthesize horizontalSeparatorPadding=_horizontalSeparatorPadding;
@property(nonatomic) long long columns; // @synthesize columns=_columns;
@property(copy, nonatomic) CDUnknownBlockType didDapanChangeSegmentClickBlock; // @synthesize didDapanChangeSegmentClickBlock=_didDapanChangeSegmentClickBlock;
@property(copy, nonatomic) CDUnknownBlockType didMarketReadingFirstClickBlock; // @synthesize didMarketReadingFirstClickBlock=_didMarketReadingFirstClickBlock;
@property(copy, nonatomic) CDUnknownBlockType didMoreBlock; // @synthesize didMoreBlock=_didMoreBlock;
@property(copy, nonatomic) CDUnknownBlockType didSelectBlock; // @synthesize didSelectBlock=_didSelectBlock;
- (void).cxx_destruct;
- (void)updateSegmentWithIncNum:(int)arg1 horNum:(int)arg2 slideNum:(int)arg3;
- (void)setMarketReadingFirstTitle:(id)arg1;
- (void)moreAction:(id)arg1;
- (void)pageControlClick:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)configureLabel:(id)arg1 value:(id)arg2 colorized:(_Bool)arg3 percentile:(_Bool)arg4 signed:(_Bool)arg5;
- (void)configureIndustryCell:(id)arg1 withModel:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)drawLines;
- (void)marketReadingFirstClick;
- (void)changeSegViewClick;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

