//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseTableViewController.h"

@class BaseWebViewController, JRJInvestCalendarHandler, JRJSTStocksHeader, NSArray, NSString, TradeEmptyView, UIView;

@interface JRJSTStocksVC : JRJBaseTableViewController
{
    NSString *_dateStr;
    NSArray *_dataArr;
    BaseWebViewController *_klineWebVC;
    UIView *_sectionView;
    JRJSTStocksHeader *_header;
    JRJInvestCalendarHandler *_handler;
    TradeEmptyView *_emptyView;
}

@property(retain, nonatomic) TradeEmptyView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) JRJInvestCalendarHandler *handler; // @synthesize handler=_handler;
@property(retain, nonatomic) JRJSTStocksHeader *header; // @synthesize header=_header;
@property(retain, nonatomic) UIView *sectionView; // @synthesize sectionView=_sectionView;
@property(retain, nonatomic) BaseWebViewController *klineWebVC; // @synthesize klineWebVC=_klineWebVC;
@property(retain, nonatomic) NSArray *dataArr; // @synthesize dataArr=_dataArr;
@property(copy, nonatomic) NSString *dateStr; // @synthesize dateStr=_dateStr;
- (void).cxx_destruct;
- (id)title;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)p_removeEmptyView;
- (void)p_showEmptyView;
- (void)p_handlerStockHQWithArr:(id)arg1;
- (id)p_getCellTitleListWithModel:(id)arg1;
- (void)updateStocksHQWithStockList:(id)arg1;
- (void)requestSTStockInfo;
- (void)refreshViewBeginRefresh:(id)arg1;
- (void)configBaseSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

