//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "JRJVerticalBannerDataSource-Protocol.h"
#import "JRJVerticalBannerDelegate-Protocol.h"

@class JRJVerticalBanner, NSArray, NSLayoutConstraint, NSString, UIButton, UILabel;

@interface JRJSmartAuthHeaderView : UIView <JRJVerticalBannerDelegate, JRJVerticalBannerDataSource>
{
    UILabel *_titleLbl;
    UILabel *_contentLbl;
    UILabel *_authTodayOutLbl;
    UIView *_authDayBg;
    UILabel *_endTimeLbl;
    UIButton *_getZPointBtn;
    NSArray *_titleArr;
    CDUnknownBlockType _getZPointBlock;
    UIView *_authBannerBG;
    NSLayoutConstraint *_banner_W;
    JRJVerticalBanner *_bannerView;
}

+ (id)viewFromNIB;
@property(retain, nonatomic) JRJVerticalBanner *bannerView; // @synthesize bannerView=_bannerView;
@property(nonatomic) __weak NSLayoutConstraint *banner_W; // @synthesize banner_W=_banner_W;
@property(nonatomic) __weak UIView *authBannerBG; // @synthesize authBannerBG=_authBannerBG;
@property(copy, nonatomic) CDUnknownBlockType getZPointBlock; // @synthesize getZPointBlock=_getZPointBlock;
@property(copy, nonatomic) NSArray *titleArr; // @synthesize titleArr=_titleArr;
@property(nonatomic) __weak UIButton *getZPointBtn; // @synthesize getZPointBtn=_getZPointBtn;
@property(nonatomic) __weak UILabel *endTimeLbl; // @synthesize endTimeLbl=_endTimeLbl;
@property(nonatomic) __weak UIView *authDayBg; // @synthesize authDayBg=_authDayBg;
@property(nonatomic) __weak UILabel *authTodayOutLbl; // @synthesize authTodayOutLbl=_authTodayOutLbl;
@property(nonatomic) __weak UILabel *contentLbl; // @synthesize contentLbl=_contentLbl;
@property(nonatomic) __weak UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;
- (void).cxx_destruct;
- (void)banner:(id)arg1 didSelectIndex:(long long)arg2;
- (id)banner:(id)arg1 viewForItemAtIndex:(long long)arg2;
- (long long)numberOfItemsInBanner:(id)arg1;
- (void)getZPointClick:(id)arg1;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

