//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "YCBBaseTableViewCell.h"

@class MLLinkLabel, SearchAskModel, UIImageView, UILabel;
@protocol JRJSearchAskCellDelegate;

@interface JRJSearchAskCell : YCBBaseTableViewCell
{
    SearchAskModel *_askM;
    id <JRJSearchAskCellDelegate> _delegate;
    MLLinkLabel *_answerL;
    UILabel *_askL;
    UIImageView *_avatarIV;
    UILabel *_nameL;
    UILabel *_updateTimeLabel;
}

+ (double)heightForCell;
@property(nonatomic) __weak UILabel *updateTimeLabel; // @synthesize updateTimeLabel=_updateTimeLabel;
@property(nonatomic) __weak UILabel *nameL; // @synthesize nameL=_nameL;
@property(nonatomic) __weak UIImageView *avatarIV; // @synthesize avatarIV=_avatarIV;
@property(nonatomic) __weak UILabel *askL; // @synthesize askL=_askL;
@property(nonatomic) __weak MLLinkLabel *answerL; // @synthesize answerL=_answerL;
@property(nonatomic) __weak id <JRJSearchAskCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SearchAskModel *askM; // @synthesize askM=_askM;
- (void).cxx_destruct;
- (void)avatarDidPressed;
- (void)awakeFromNib;

@end

