//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, NSMutableAttributedString, NSString, UIColor, UILabel;

@interface JRJSuperSignalAnimationView : UIView
{
    UIColor *_lineColor1;
    UIColor *_lineSmoothColor;
    UIColor *_smallCircleFristColor;
    UIColor *_smallCircleFristColor2;
    UIColor *_smallCircleSecondColor1;
    UIColor *_smallCircleSecondColor2;
    UIColor *_fristShadowColor;
    UIColor *_circlebgColor;
    UIColor *_circleMainColor;
    UIColor *_circleMainColor2;
    UIColor *_animationColor;
    NSString *_tagStr;
    NSMutableAttributedString *_descAttributedText;
    NSString *_desc;
    UIColor *_descUIColor;
    UIColor *_sugTextUIColor;
    long long _indexStyle;
    UILabel *_descUILabel;
    UILabel *_infomationUILabel;
    NSArray *_lineColor1Array;
    NSArray *_lineSmoothColorArray;
    NSArray *_smallCircleFristColorArray;
    NSArray *_smallCircleFristColor2Array;
    NSArray *_smallCircleSecondColor1Array;
    NSArray *_smallCircleSecondColor2Array;
    NSArray *_fristShadowColorArray;
    NSArray *_circlebgColor1Array;
    NSArray *_circleMainColorArray;
    NSArray *_circleMainColor2Array;
    NSArray *_animationColorArray;
    NSArray *_textColorArray;
    NSArray *_descArray;
}

@property(retain, nonatomic) NSArray *descArray; // @synthesize descArray=_descArray;
@property(retain, nonatomic) NSArray *textColorArray; // @synthesize textColorArray=_textColorArray;
@property(retain, nonatomic) NSArray *animationColorArray; // @synthesize animationColorArray=_animationColorArray;
@property(retain, nonatomic) NSArray *circleMainColor2Array; // @synthesize circleMainColor2Array=_circleMainColor2Array;
@property(retain, nonatomic) NSArray *circleMainColorArray; // @synthesize circleMainColorArray=_circleMainColorArray;
@property(retain, nonatomic) NSArray *circlebgColor1Array; // @synthesize circlebgColor1Array=_circlebgColor1Array;
@property(retain, nonatomic) NSArray *fristShadowColorArray; // @synthesize fristShadowColorArray=_fristShadowColorArray;
@property(retain, nonatomic) NSArray *smallCircleSecondColor2Array; // @synthesize smallCircleSecondColor2Array=_smallCircleSecondColor2Array;
@property(retain, nonatomic) NSArray *smallCircleSecondColor1Array; // @synthesize smallCircleSecondColor1Array=_smallCircleSecondColor1Array;
@property(retain, nonatomic) NSArray *smallCircleFristColor2Array; // @synthesize smallCircleFristColor2Array=_smallCircleFristColor2Array;
@property(retain, nonatomic) NSArray *smallCircleFristColorArray; // @synthesize smallCircleFristColorArray=_smallCircleFristColorArray;
@property(retain, nonatomic) NSArray *lineSmoothColorArray; // @synthesize lineSmoothColorArray=_lineSmoothColorArray;
@property(retain, nonatomic) NSArray *lineColor1Array; // @synthesize lineColor1Array=_lineColor1Array;
@property(retain, nonatomic) UILabel *infomationUILabel; // @synthesize infomationUILabel=_infomationUILabel;
@property(retain, nonatomic) UILabel *descUILabel; // @synthesize descUILabel=_descUILabel;
@property(nonatomic) long long indexStyle; // @synthesize indexStyle=_indexStyle;
@property(retain, nonatomic) UIColor *sugTextUIColor; // @synthesize sugTextUIColor=_sugTextUIColor;
@property(retain, nonatomic) UIColor *descUIColor; // @synthesize descUIColor=_descUIColor;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSMutableAttributedString *descAttributedText; // @synthesize descAttributedText=_descAttributedText;
@property(retain, nonatomic) NSString *tagStr; // @synthesize tagStr=_tagStr;
@property(retain, nonatomic) UIColor *animationColor; // @synthesize animationColor=_animationColor;
@property(retain, nonatomic) UIColor *circleMainColor2; // @synthesize circleMainColor2=_circleMainColor2;
@property(retain, nonatomic) UIColor *circleMainColor; // @synthesize circleMainColor=_circleMainColor;
@property(retain, nonatomic) UIColor *circlebgColor; // @synthesize circlebgColor=_circlebgColor;
@property(retain, nonatomic) UIColor *fristShadowColor; // @synthesize fristShadowColor=_fristShadowColor;
@property(retain, nonatomic) UIColor *smallCircleSecondColor2; // @synthesize smallCircleSecondColor2=_smallCircleSecondColor2;
@property(retain, nonatomic) UIColor *smallCircleSecondColor1; // @synthesize smallCircleSecondColor1=_smallCircleSecondColor1;
@property(retain, nonatomic) UIColor *smallCircleFristColor2; // @synthesize smallCircleFristColor2=_smallCircleFristColor2;
@property(retain, nonatomic) UIColor *smallCircleFristColor; // @synthesize smallCircleFristColor=_smallCircleFristColor;
@property(retain, nonatomic) UIColor *lineSmoothColor; // @synthesize lineSmoothColor=_lineSmoothColor;
@property(retain, nonatomic) UIColor *lineColor1; // @synthesize lineColor1=_lineColor1;
- (void).cxx_destruct;
- (void)initJRJSuperSignalUIView:(long long)arg1 withDesc:(id)arg2;
- (void)initColorArray;
- (void)addCAGradientLayer:(struct CGPoint)arg1 withRadius:(double)arg2;
- (void)drawHorizonLine;
- (void)verticalLine;
- (void)drawCiclePointWithArc:(struct CGPoint)arg1 withRadius:(double)arg2 withColor:(struct CGColor *)arg3 withFillColor:(struct CGColor *)arg4;
- (void)smoothedPathWithPoints:(id)arg1 andGranularity:(long long)arg2;
- (void)drawSmoothLine;
- (void)drawMainCirclewithRadius:(double)arg1 withstartAngle:(double)arg2 withendAngle:(double)arg3 withLineWidth:(double)arg4 withColor:(id)arg5;
- (void)drawCenterCirclewithRadius:(double)arg1 withstartAngle:(double)arg2 withendAngle:(double)arg3 withLineWidth:(double)arg4 withColor:(id)arg5;
- (void)drawAnimationCircle:(double)arg1 withstartAngle:(double)arg2 withendAngle:(double)arg3 withLineWidth:(double)arg4 withTimer:(double)arg5 beginTime:(double)arg6;
- (void)drawZhwText;
- (void)drawRect:(struct CGRect)arg1;

@end

