//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseHandler.h"

@interface JRJSimulatorPortfolioHandler : BaseHandler
{
    _Bool _isFirstPage;
    long long _pageIndex;
    long long _totlaPages;
}

@property(nonatomic) _Bool isFirstPage; // @synthesize isFirstPage=_isFirstPage;
@property(nonatomic) long long totlaPages; // @synthesize totlaPages=_totlaPages;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
- (_Bool)isNeedAutoLoadingResponse:(id)arg1;
- (_Bool)isCacheResponse:(id)arg1;
- (id)updateMyPortfolioModelList:(id)arg1;
- (id)viewModelOfClass:(Class)arg1 fromModelArray:(id)arg2;
- (id)responseObjectForResponse:(id)arg1 responseObject:(id)arg2 error:(id *)arg3;
- (void)fetchSimulatorPortfolioList:(CDUnknownBlockType)arg1 cacheBlock:(CDUnknownBlockType)arg2;

@end

