//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class JRJShakeDiagnoseModel, JRJShakeDiagnoseStockInfoModel, NSLayoutConstraint, UIButton, UILabel;

@interface JRJShakeDiagnoseSectionHeader : UITableViewHeaderFooterView
{
    UILabel *_leftTitleLabel;
    UILabel *_bottomLabel;
    UIButton *_addStockButton;
    UILabel *_leftSecondLabel;
    UILabel *_suggestLabel;
    UILabel *_signalLabel;
    NSLayoutConstraint *_suggestLabelWidth;
    JRJShakeDiagnoseStockInfoModel *_infoModel;
    JRJShakeDiagnoseModel *_diagnoseModel;
    CDUnknownBlockType _addBlock;
    CDUnknownBlockType _pushBlock;
}

@property(copy, nonatomic) CDUnknownBlockType pushBlock; // @synthesize pushBlock=_pushBlock;
@property(copy, nonatomic) CDUnknownBlockType addBlock; // @synthesize addBlock=_addBlock;
@property(retain, nonatomic) JRJShakeDiagnoseModel *diagnoseModel; // @synthesize diagnoseModel=_diagnoseModel;
@property(retain, nonatomic) JRJShakeDiagnoseStockInfoModel *infoModel; // @synthesize infoModel=_infoModel;
@property(nonatomic) __weak NSLayoutConstraint *suggestLabelWidth; // @synthesize suggestLabelWidth=_suggestLabelWidth;
@property(nonatomic) __weak UILabel *signalLabel; // @synthesize signalLabel=_signalLabel;
@property(nonatomic) __weak UILabel *suggestLabel; // @synthesize suggestLabel=_suggestLabel;
@property(nonatomic) __weak UILabel *leftSecondLabel; // @synthesize leftSecondLabel=_leftSecondLabel;
@property(nonatomic) __weak UIButton *addStockButton; // @synthesize addStockButton=_addStockButton;
@property(nonatomic) __weak UILabel *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(nonatomic) __weak UILabel *leftTitleLabel; // @synthesize leftTitleLabel=_leftTitleLabel;
- (void).cxx_destruct;
- (_Bool)existStock:(id)arg1;
- (void)pushTapGes;
- (void)addStock;
- (void)configData:(id)arg1 auth:(int)arg2;

@end

