//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSLayoutConstraint, UIImageView, UILabel;
@protocol JRJStockModelProtocol;

@interface JRJStockMarketListCell : UITableViewCell
{
    id <JRJStockModelProtocol> _model;
    long long _listType;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_centerLabel;
    UILabel *_rightLabel;
    NSLayoutConstraint *_centerYConstraint;
    UIImageView *_identifyImageView;
    NSLayoutConstraint *_leftLayoutConstraint;
}

+ (double)cellHeight;
@property(nonatomic) __weak NSLayoutConstraint *leftLayoutConstraint; // @synthesize leftLayoutConstraint=_leftLayoutConstraint;
@property(nonatomic) __weak UIImageView *identifyImageView; // @synthesize identifyImageView=_identifyImageView;
@property(nonatomic) __weak NSLayoutConstraint *centerYConstraint; // @synthesize centerYConstraint=_centerYConstraint;
@property(nonatomic) __weak UILabel *rightLabel; // @synthesize rightLabel=_rightLabel;
@property(nonatomic) __weak UILabel *centerLabel; // @synthesize centerLabel=_centerLabel;
@property(nonatomic) __weak UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) long long listType; // @synthesize listType=_listType;
@property(retain, nonatomic) id <JRJStockModelProtocol> model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)configureLabel:(id)arg1 value:(id)arg2 colorized:(_Bool)arg3 percentile:(_Bool)arg4 signedMark:(_Bool)arg5;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

