//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class JRJStockMarketDetailHeaderView, NSString;
@protocol JRJStockMarketDetailViewDataSource, JRJStockMarketDetailViewDelegate;

@interface JRJStockMarketDetailView : UITableView <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _ascending;
    id <JRJStockMarketDetailViewDataSource> _marketDataSource;
    id <JRJStockMarketDetailViewDelegate> _marketDelegate;
    long long _listType;
    JRJStockMarketDetailHeaderView *_headerView;
}

@property(retain, nonatomic) JRJStockMarketDetailHeaderView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) _Bool ascending; // @synthesize ascending=_ascending;
@property(nonatomic) long long listType; // @synthesize listType=_listType;
@property(nonatomic) __weak id <JRJStockMarketDetailViewDelegate> marketDelegate; // @synthesize marketDelegate=_marketDelegate;
@property(nonatomic) __weak id <JRJStockMarketDetailViewDataSource> marketDataSource; // @synthesize marketDataSource=_marketDataSource;
- (void).cxx_destruct;
- (void)refreshHeader;
- (void)didSort;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)registerCells;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

