//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface JRJTradeDetailContainerModel : NSObject
{
    int _totalNum;
    int _start;
    int _num;
    NSMutableArray *_records;
    long long _startIndex;
    long long _endIndex;
}

+ (id)modelContainerPropertyGenericClass;
@property(nonatomic) long long endIndex; // @synthesize endIndex=_endIndex;
@property(nonatomic) long long startIndex; // @synthesize startIndex=_startIndex;
@property(retain, nonatomic) NSMutableArray *records; // @synthesize records=_records;
@property(nonatomic) int num; // @synthesize num=_num;
@property(nonatomic) int start; // @synthesize start=_start;
@property(nonatomic) int totalNum; // @synthesize totalNum=_totalNum;
- (void).cxx_destruct;

@end

