//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIImageView, UIView;

@interface JRJToutiaoTingMenuButton : UIButton
{
    _Bool _playing;
    UIView *_titleMask;
    UIImageView *_playingImageView;
}

@property(retain, nonatomic) UIImageView *playingImageView; // @synthesize playingImageView=_playingImageView;
@property(retain, nonatomic) UIView *titleMask; // @synthesize titleMask=_titleMask;
@property(nonatomic) _Bool playing; // @synthesize playing=_playing;
- (void).cxx_destruct;
- (void)setBackgroundColor:(id)arg1;
- (void)makeConstraints;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

