//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class JRJTimelineCell, NSString;

@protocol JRJTimelineDelegate <NSObject>

@optional
- (void)timelineCellDidTapMessageLabel:(JRJTimelineCell *)arg1;
- (void)timelineCell:(JRJTimelineCell *)arg1 didTapLinkWithText:(NSString *)arg2 link:(NSString *)arg3;
- (void)timelineCellDidTapAskButton:(JRJTimelineCell *)arg1;
- (void)timelineCellDidTapExpandButton:(JRJTimelineCell *)arg1;
- (void)timelineCellDidTapAvatar:(JRJTimelineCell *)arg1;
- (void)timelineCell:(JRJTimelineCell *)arg1 didTapStockWithCode:(NSString *)arg2 name:(NSString *)arg3;
- (void)timelineCell:(JRJTimelineCell *)arg1 didTapImageWithURLString:(NSString *)arg2;
@end

