//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIColor;

@interface JRJTradeSelectCountView : UIView
{
    CDUnknownBlockType _tapBlock;
    UIColor *_bgColor;
    UIButton *_oneOfFourBtn;
    UIButton *_oneOfThreeBtn;
    UIButton *_oneOfTwoBtn;
    UIButton *_allBtn;
}

@property(nonatomic) __weak UIButton *allBtn; // @synthesize allBtn=_allBtn;
@property(nonatomic) __weak UIButton *oneOfTwoBtn; // @synthesize oneOfTwoBtn=_oneOfTwoBtn;
@property(nonatomic) __weak UIButton *oneOfThreeBtn; // @synthesize oneOfThreeBtn=_oneOfThreeBtn;
@property(nonatomic) __weak UIButton *oneOfFourBtn; // @synthesize oneOfFourBtn=_oneOfFourBtn;
@property(retain, nonatomic) UIColor *bgColor; // @synthesize bgColor=_bgColor;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
- (void).cxx_destruct;
- (void)setCustomButtonBGColor:(id)arg1 color:(id)arg2;
- (void)numberButtonClick:(id)arg1;
- (void)setupStyleForButton:(id)arg1;
- (void)awakeFromNib;

@end

