//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class JRJLaunchpadView, NSArray;

@interface JRJToutiaoLaunchpadCell : JRJTableViewCell
{
    NSArray *_items;
    CDUnknownBlockType _didTapBlock;
    JRJLaunchpadView *_padView;
}

@property(retain, nonatomic) JRJLaunchpadView *padView; // @synthesize padView=_padView;
@property(copy, nonatomic) CDUnknownBlockType didTapBlock; // @synthesize didTapBlock=_didTapBlock;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)commonInit;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

