//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface JRJTooltipManager : NSObject
{
    _Bool _upgradedFromPreviousVersion;
    NSMutableDictionary *_tooltips;
}

+ (id)sharedManager;
@property(nonatomic) _Bool upgradedFromPreviousVersion; // @synthesize upgradedFromPreviousVersion=_upgradedFromPreviousVersion;
@property(retain, nonatomic) NSMutableDictionary *tooltips; // @synthesize tooltips=_tooltips;
- (void).cxx_destruct;
- (_Bool)tooltipDisplayed:(id)arg1;
- (void)markTooltipWithIdentifier:(id)arg1 asDisplayed:(_Bool)arg2;
- (id)keyForIdentifier:(id)arg1;
- (void)removeTooltipWithIdentifier:(id)arg1;
- (void)showTooltipWithIdentifier:(id)arg1 text:(id)arg2 textMaxWidth:(double)arg3 direction:(long long)arg4 linePosition:(long long)arg5 inView:(id)arg6 position:(struct CGPoint)arg7;
- (void)showTooltipWithIdentifier:(id)arg1 text:(id)arg2 direction:(long long)arg3 linePosition:(long long)arg4 inView:(id)arg5 position:(struct CGPoint)arg6;
- (void)showTooltipWithIdentifier:(id)arg1 text:(id)arg2 inView:(id)arg3 position:(struct CGPoint)arg4;
- (id)init;

@end

