//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJToutiaoListViewController.h"

@class JRJToutiaoTingPlayerView, NSMutableArray, NSNumber;

@interface JRJToutiaoKuaiXunViewController : JRJToutiaoListViewController
{
    NSNumber *_timestamp;
    NSMutableArray *_sections;
    NSMutableArray *_tingModels;
    long long _retry;
    JRJToutiaoTingPlayerView *_player;
}

+ (id)sharedViewController;
@property(retain, nonatomic) JRJToutiaoTingPlayerView *player; // @synthesize player=_player;
@property(nonatomic) long long retry; // @synthesize retry=_retry;
@property(retain, nonatomic) NSMutableArray *tingModels; // @synthesize tingModels=_tingModels;
@property(retain, nonatomic) NSMutableArray *sections; // @synthesize sections=_sections;
@property(retain, nonatomic) NSNumber *timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (void)stateDidChange:(id)arg1;
- (void)didFail:(id)arg1;
- (void)didEndPlaying:(id)arg1;
- (void)didStartPlaying:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (id)p_indexPathOfTingModel:(id)arg1;
- (id)p_insertFeedADIntoArray:(id)arg1;
- (void)p_splitToSectionsWithArray:(id)arg1;
- (id)p_modelAtSection:(long long)arg1 row:(long long)arg2;
- (void)turnToTheNextPage;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (_Bool)shouldRetryWithError:(id)arg1;
- (void)responseDidProcess;
- (id)dataArrayWithResponse:(id)arg1;
- (id)dataSource;
- (void)didSelectRowAtIndexPath:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)cellForRowAtIndexPath:(id)arg1;
- (id)APIURLString;
- (void)registerNotifications;
- (void)hidePlayer;
- (void)showPlayer;
- (void)setupPlayer;
- (void)viewDidLoad;
- (id)init;

@end

