//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class UIView;

@interface JRJToutiaoColumnCell : JRJTableViewCell
{
    _Bool _lastRow;
    id _model;
    UIView *_containerView;
    UIView *_bottomSeparator;
    UIView *_shadowView;
    UIView *_backView;
}

@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) UIView *shadowView; // @synthesize shadowView=_shadowView;
@property(nonatomic) _Bool lastRow; // @synthesize lastRow=_lastRow;
@property(retain, nonatomic) UIView *bottomSeparator; // @synthesize bottomSeparator=_bottomSeparator;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) id model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)p_dropShadow;
- (void)cellDidLoad;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)makeConstraints;
- (void)layoutSubviews;
- (void)commonInit;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

