//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JRJTradeStockBuyAndSellModel, UIButton, UILabel;

@interface JRJTradeConfirmPopWindowView : UIView
{
    JRJTradeStockBuyAndSellModel *_buyAndSellModel;
    CDUnknownBlockType _cancelBlock;
    CDUnknownBlockType _confirmBlock;
    UILabel *_title;
    UILabel *_delegateType;
    UILabel *_stockName;
    UILabel *_stockPrice;
    UILabel *_stockAmount;
    UILabel *_totalValue;
    UILabel *_serviceFee;
    UIButton *_cancelButton;
    UIButton *_confirmButton;
}

@property(nonatomic) __weak UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(nonatomic) __weak UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) __weak UILabel *serviceFee; // @synthesize serviceFee=_serviceFee;
@property(nonatomic) __weak UILabel *totalValue; // @synthesize totalValue=_totalValue;
@property(nonatomic) __weak UILabel *stockAmount; // @synthesize stockAmount=_stockAmount;
@property(nonatomic) __weak UILabel *stockPrice; // @synthesize stockPrice=_stockPrice;
@property(nonatomic) __weak UILabel *stockName; // @synthesize stockName=_stockName;
@property(nonatomic) __weak UILabel *delegateType; // @synthesize delegateType=_delegateType;
@property(nonatomic) __weak UILabel *title; // @synthesize title=_title;
@property(copy, nonatomic) CDUnknownBlockType confirmBlock; // @synthesize confirmBlock=_confirmBlock;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(retain, nonatomic) JRJTradeStockBuyAndSellModel *buyAndSellModel; // @synthesize buyAndSellModel=_buyAndSellModel;
- (void).cxx_destruct;
- (void)confirmButtonClick:(id)arg1;
- (void)cancelButtonClick:(id)arg1;
- (void)awakeFromNib;

@end

