//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class JRJToutiaoStock, UILabel;

@interface JRJToutiaoStockView : UIView
{
    JRJToutiaoStock *_stock;
    CDUnknownBlockType _tapBlock;
    double _fontSize;
    UILabel *_zsLabel;
    UILabel *_stockLabel;
}

@property(retain, nonatomic) UILabel *stockLabel; // @synthesize stockLabel=_stockLabel;
@property(retain, nonatomic) UILabel *zsLabel; // @synthesize zsLabel=_zsLabel;
@property(nonatomic) double fontSize; // @synthesize fontSize=_fontSize;
@property(copy, nonatomic) CDUnknownBlockType tapBlock; // @synthesize tapBlock=_tapBlock;
@property(retain, nonatomic) JRJToutiaoStock *stock; // @synthesize stock=_stock;
- (void).cxx_destruct;
- (void)didTap:(id)arg1;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

