//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface JRJUserMyServiceHeader : UIView
{
    UIView *_coverView;
    UIButton *_xfjlUIbtn;
    CDUnknownBlockType _gotoXfjlBlock;
    UILabel *_titleLabel;
    UIImageView *_imageTitle;
}

@property(nonatomic) __weak UIImageView *imageTitle; // @synthesize imageTitle=_imageTitle;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType gotoXfjlBlock; // @synthesize gotoXfjlBlock=_gotoXfjlBlock;
@property(nonatomic) __weak UIButton *xfjlUIbtn; // @synthesize xfjlUIbtn=_xfjlUIbtn;
@property(nonatomic) __weak UIView *coverView; // @synthesize coverView=_coverView;
- (void).cxx_destruct;
- (void)clickXfjlBtn:(id)arg1;
- (void)awakeFromNib;

@end

