//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface JRJVideo : NSObject
{
    NSString *_videoId;
    NSString *_videoName;
    NSString *_videoUrl;
    NSString *_videoLength;
    NSString *_videoCover;
    NSString *_videoTitle;
    NSString *_userId;
    NSString *_userName;
    NSString *_headImage;
}

+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) NSString *headImage; // @synthesize headImage=_headImage;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) NSString *videoTitle; // @synthesize videoTitle=_videoTitle;
@property(retain, nonatomic) NSString *videoCover; // @synthesize videoCover=_videoCover;
@property(retain, nonatomic) NSString *videoLength; // @synthesize videoLength=_videoLength;
@property(retain, nonatomic) NSString *videoUrl; // @synthesize videoUrl=_videoUrl;
@property(retain, nonatomic) NSString *videoName; // @synthesize videoName=_videoName;
@property(retain, nonatomic) NSString *videoId; // @synthesize videoId=_videoId;
- (void).cxx_destruct;

@end

