//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSMutableArray;
@protocol JRJYanBaoPotentialListSectionViewDelegate;

@interface JRJYanBaoPotentialListSectionView : UIView
{
    id <JRJYanBaoPotentialListSectionViewDelegate> _delegate;
    UIView *_filterBgView;
    UIView *_filterView;
    NSMutableArray *_filterItems;
}

@property(retain, nonatomic) NSMutableArray *filterItems; // @synthesize filterItems=_filterItems;
@property(retain, nonatomic) UIView *filterView; // @synthesize filterView=_filterView;
@property(retain, nonatomic) UIView *filterBgView; // @synthesize filterBgView=_filterBgView;
@property(nonatomic) __weak id <JRJYanBaoPotentialListSectionViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutPageSubviews;
- (void)reloadFilterView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

