//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface JRJZSuperDiagnosisinfovoModel : NSObject
{
    NSString *_expireTime;
    NSNumber *_days;
    long long _validType;
    NSArray *_priceDetail;
}

+ (id)modelContainerPropertyGenericClass;
@property(retain, nonatomic) NSArray *priceDetail; // @synthesize priceDetail=_priceDetail;
@property(nonatomic) long long validType; // @synthesize validType=_validType;
@property(copy, nonatomic) NSNumber *days; // @synthesize days=_days;
@property(copy, nonatomic) NSString *expireTime; // @synthesize expireTime=_expireTime;
- (void).cxx_destruct;

@end

