//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseViewController.h"

@class JRJZhuLiDDXRankingListVC, UISegmentedControl, UIViewController;

@interface JRJZhuliRankListMainVC : JRJBaseViewController
{
    JRJZhuLiDDXRankingListVC *_ddxListVC;
    JRJZhuLiDDXRankingListVC *_moneyListVC;
    UIViewController *_fromVC;
    UIViewController *_toVC;
    long long _segmentIndex;
    UISegmentedControl *_segmentedControl;
}

@property(retain, nonatomic) UISegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
@property(nonatomic) long long segmentIndex; // @synthesize segmentIndex=_segmentIndex;
- (void).cxx_destruct;
- (void)segmentAction:(id)arg1;
- (id)getCurrentSubController;
- (id)firstChangeToController;
- (void)createAndAddChildVCs;
- (void)viewDidLoad;

@end

