//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class JRJZhiboMessage, MLLinkLabel;

@interface JRJZhiboFocusCell : JRJTableViewCell
{
    CDUnknownBlockType _tapLinkBlock;
    JRJZhiboMessage *_message;
    MLLinkLabel *_contentLabel;
    MLLinkLabel *_quoteLabel;
}

@property(retain, nonatomic) MLLinkLabel *quoteLabel; // @synthesize quoteLabel=_quoteLabel;
@property(retain, nonatomic) MLLinkLabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) JRJZhiboMessage *message; // @synthesize message=_message;
@property(copy, nonatomic) CDUnknownBlockType tapLinkBlock; // @synthesize tapLinkBlock=_tapLinkBlock;
- (void).cxx_destruct;
- (void)commonInit;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

