//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJTableViewCell.h"

@class NSDictionary, UIButton, UILabel, UIView;

@interface JRJZhiboArchivedVideoCell : JRJTableViewCell
{
    NSDictionary *_model;
    CDUnknownBlockType _toggleBlock;
    UIView *_containerView;
    UILabel *_lengthLabel;
    UILabel *_titleLabel;
    UIButton *_playButton;
    UIView *_separator;
}

+ (double)cellHeight;
@property(retain, nonatomic) UIView *separator; // @synthesize separator=_separator;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *lengthLabel; // @synthesize lengthLabel=_lengthLabel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(copy, nonatomic) CDUnknownBlockType toggleBlock; // @synthesize toggleBlock=_toggleBlock;
@property(retain, nonatomic) NSDictionary *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (void)didTapPlayButton:(id)arg1;
- (void)makeConstraints;
- (void)commonInit;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

