//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface JRJZhiboHistoryDataStore : NSObject
{
    NSMutableArray *_dataArray;
}

+ (id)sharedStore;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
- (void).cxx_destruct;
- (id)p_key;
- (id)rooms;
- (void)clearHistory;
- (void)addHistoryWithID:(id)arg1 name:(id)arg2 avatarURLString:(id)arg3;
- (id)init;

@end

