//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface JRJZiXunRelatedResearchReport : NSObject
{
    NSString *_xreportId;
    NSString *_xreportUrl;
    NSString *_xreportRatio;
}

@property(copy, nonatomic) NSString *xreportRatio; // @synthesize xreportRatio=_xreportRatio;
@property(copy, nonatomic) NSString *xreportUrl; // @synthesize xreportUrl=_xreportUrl;
@property(copy, nonatomic) NSString *xreportId; // @synthesize xreportId=_xreportId;
- (void).cxx_destruct;

@end

