//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JRJZjMinLineModel : NSObject
{
    double _supl;
    double _midCashFlow;
    double _smallCashFlow;
    long long _tradeTime;
}

+ (id)modelCustomPropertyMapper;
@property(nonatomic) long long tradeTime; // @synthesize tradeTime=_tradeTime;
@property(nonatomic) double smallCashFlow; // @synthesize smallCashFlow=_smallCashFlow;
@property(nonatomic) double midCashFlow; // @synthesize midCashFlow=_midCashFlow;
@property(nonatomic) double supl; // @synthesize supl=_supl;
- (_Bool)modelCustomTransformFromDictionary:(id)arg1;

@end

