//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class NSDictionary, UIImageView, UILabel;

@interface JRJZhiboHistoryView : UICollectionViewCell
{
    NSDictionary *_room;
    UIImageView *_bgImageView;
    UIImageView *_avatarImageView;
    UILabel *_nameLabel;
}

+ (double)cellWidthWithName:(id)arg1;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) __weak UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(copy, nonatomic) NSDictionary *room; // @synthesize room=_room;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

