//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface JRJZSuperCoursebannersModel : NSObject
{
    NSString *_ID;
    NSString *_opentype;
    long long _price;
    NSString *_src;
    NSString *_linkurl;
}

+ (id)modelCustomPropertyMapper;
@property(copy, nonatomic) NSString *linkurl; // @synthesize linkurl=_linkurl;
@property(copy, nonatomic) NSString *src; // @synthesize src=_src;
@property(nonatomic) long long price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *opentype; // @synthesize opentype=_opentype;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
- (void).cxx_destruct;

@end

