//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PBGeneratedMessageBuilder.h"

@class Kdj;

@interface KdjBuilder : PBGeneratedMessageBuilder
{
    Kdj *resultKdj;
}

@property(retain) Kdj *resultKdj; // @synthesize resultKdj;
- (void).cxx_destruct;
- (id)clearJ;
- (id)setJ:(float)arg1;
- (float)j;
- (_Bool)hasJ;
- (id)clearD;
- (id)setD:(float)arg1;
- (float)d;
- (_Bool)hasD;
- (id)clearK;
- (id)setK:(float)arg1;
- (float)k;
- (_Bool)hasK;
- (id)clearId;
- (id)setId:(id)arg1;
- (id)id;
- (_Bool)hasId;
- (id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (id)mergeFromCodedInputStream:(id)arg1;
- (id)mergeFrom:(id)arg1;
- (id)buildPartial;
- (id)build;
- (id)defaultInstance;
- (id)clone;
- (id)clear;
- (id)internalGetResult;
- (id)init;

@end

