//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseCell.h"

@class UIActivityIndicatorView, UIButton, UILabel;

@interface LoadMoreCell : JRJBaseCell
{
    _Bool _isLoading;
    long long _cellState;
    UILabel *_loadingLabel;
    UIActivityIndicatorView *_indicatorView;
    UIButton *_loadMoreButton;
    CDUnknownBlockType _buttonClickedBlock;
}

+ (double)cellHeight;
@property(copy, nonatomic) CDUnknownBlockType buttonClickedBlock; // @synthesize buttonClickedBlock=_buttonClickedBlock;
@property(retain, nonatomic) UIButton *loadMoreButton; // @synthesize loadMoreButton=_loadMoreButton;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) UILabel *loadingLabel; // @synthesize loadingLabel=_loadingLabel;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) long long cellState; // @synthesize cellState=_cellState;
- (void).cxx_destruct;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)loadMoreButtonClicked:(id)arg1;
@property(readonly, nonatomic) _Bool isShouldLoading;
- (void)awakeFromNib;

@end

