//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UILabel, UITextField;
@protocol SubmitInfoViewDelegate;

@interface LoginPasswordView : UIView <UITextFieldDelegate>
{
    UILabel *lblMainTitle;
    UILabel *lblPwdCaption;
    UITextField *tfPwd;
    UIView *frameView;
    UITextField *_extPwd;
    UILabel *_extLabel;
    _Bool _showExtPwd;
    id <SubmitInfoViewDelegate> _delegate;
    NSString *_password;
    NSString *_extPassword;
}

@property(copy, nonatomic) NSString *extPassword; // @synthesize extPassword=_extPassword;
@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(nonatomic) _Bool showExtPwd; // @synthesize showExtPwd=_showExtPwd;
@property(nonatomic) __weak id <SubmitInfoViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)showKeyboardEvent;
- (void)showKeyboard;
- (void)setMainTitle:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

