//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MarketIndexModel : NSObject
{
    NSString *_stockName;
    NSString *_stockCode;
    NSString *_stockMarket;
    double _lastPrice;
    double _chgRadio;
    double _change;
}

+ (id)mj_replacedKeyFromPropertyName;
@property(nonatomic) double change; // @synthesize change=_change;
@property(nonatomic) double chgRadio; // @synthesize chgRadio=_chgRadio;
@property(nonatomic) double lastPrice; // @synthesize lastPrice=_lastPrice;
@property(copy, nonatomic) NSString *stockMarket; // @synthesize stockMarket=_stockMarket;
@property(copy, nonatomic) NSString *stockCode; // @synthesize stockCode=_stockCode;
@property(copy, nonatomic) NSString *stockName; // @synthesize stockName=_stockName;
- (void).cxx_destruct;

@end

