//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseViewController.h"

@class AttentionListViewController, JRJWatchlistViewController;

@interface MyConcernVC : JRJBaseViewController
{
    _Bool _hasShowTipView;
    JRJWatchlistViewController *_watchListVC;
    AttentionListViewController *_investorsListVC;
}

@property(nonatomic) _Bool hasShowTipView; // @synthesize hasShowTipView=_hasShowTipView;
@property(retain, nonatomic) AttentionListViewController *investorsListVC; // @synthesize investorsListVC=_investorsListVC;
@property(retain, nonatomic) JRJWatchlistViewController *watchListVC; // @synthesize watchListVC=_watchListVC;
- (void).cxx_destruct;
- (void)itemAction;
- (void)showRightBtnItemWithFlag:(_Bool)arg1;
- (void)segmentAction:(id)arg1;
- (void)addSegmentController;
- (void)viewDidAppear:(_Bool)arg1;
- (void)showTipView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

@end

