//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseHandler.h"

@interface MyCollectionHandler : BaseHandler
{
    int _pageIndex;
    int _totlaPage;
}

@property(nonatomic) int totlaPage; // @synthesize totlaPage=_totlaPage;
@property(nonatomic) int pageIndex; // @synthesize pageIndex=_pageIndex;
- (_Bool)isCacheResponse:(id)arg1;
- (_Bool)isNeedAutoLoadingResponse:(id)arg1;
- (id)mutableDataArray;
- (void)handleList:(id)arg1;
- (id)responseObjectForResponse:(id)arg1 responseObject:(id)arg2 error:(id *)arg3;
- (void)fetchDataFinishBlock:(CDUnknownBlockType)arg1;

@end

