//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, NSDictionary, UIButton, UIImage, UIImageView, UILabel, UIPickerView, UITextView, UIView;

@interface NBSActionEditorVC : UIViewController
{
    UIView *container;
    UILabel *lbl_id;
    UILabel *lbl_name;
    UILabel *lbl_page;
    UIButton *btn_cancel;
    UIButton *btn_post;
    UIPickerView *picker_Actions;
    UITextView *txt_name;
    UITextView *txt_page;
    UIImageView *imageView;
    NSArray *events;
    int selectedRow;
    UIImage *_screenShot;
    CDUnknownBlockType _callBackOnBtnPost;
    NSDictionary *_actions;
    CDUnknownBlockType _cancelCallBack;
}

+ (id)editorWithImage:(id)arg1 actions:(id)arg2 withCallBackOnPost:(CDUnknownBlockType)arg3 withCallBackOnCancel:(CDUnknownBlockType)arg4;
+ (void)load;
@property(copy) CDUnknownBlockType cancelCallBack; // @synthesize cancelCallBack=_cancelCallBack;
@property(retain) NSDictionary *actions; // @synthesize actions=_actions;
@property(copy) CDUnknownBlockType callBackOnBtnPost; // @synthesize callBackOnBtnPost=_callBackOnBtnPost;
@property(retain) UIImage *screenShot; // @synthesize screenShot=_screenShot;
- (void).cxx_destruct;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2;
- (double)pickerView:(id)arg1 widthForComponent:(long long)arg2;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)click_cancel:(id)arg1;
- (void)click_post:(id)arg1;
- (void)handleDeviceOrientationChange:(id)arg1;
- (void)fingerTapped:(id)arg1;
- (void)packUpKeyBoard;
- (void)viewDidLoad;
- (void)fillData;
- (void)autoFitSize;
- (void)constructInterface;

@end

