//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseCell.h"

@class NSDictionary, UIImageView, UILabel;

@interface OptionalStockInfoListCell : JRJBaseCell
{
    NSDictionary *_clsnames;
    UILabel *_nameLabel;
    UILabel *_titleLabel;
    UILabel *_timeLabel;
    UILabel *_subTimeLbl;
    UIImageView *_searchImv;
    UILabel *_rightBottomLbl;
    UIImageView *_isbearImg;
}

@property(nonatomic) __weak UIImageView *isbearImg; // @synthesize isbearImg=_isbearImg;
@property(nonatomic) __weak UILabel *rightBottomLbl; // @synthesize rightBottomLbl=_rightBottomLbl;
@property(nonatomic) __weak UIImageView *searchImv; // @synthesize searchImv=_searchImv;
@property(nonatomic) __weak UILabel *subTimeLbl; // @synthesize subTimeLbl=_subTimeLbl;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
- (void).cxx_destruct;
- (void)updateCustomResearchCellWithDic:(id)arg1;
- (void)addSubview:(id)arg1;
- (void)bindDataWithDic:(id)arg1 type:(unsigned long long)arg2 isTouTiao:(_Bool)arg3;
- (void)awakeFromNib;

@end

