//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIAlertViewDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class NSString, PAZQOPStockWebView, UIView;

@interface PAZQOPMainViewController : UIViewController <UIAlertViewDelegate, UIWebViewDelegate>
{
    UIView *_backView;
    _Bool _h5_debug_mode;
    _Bool _isMainModule;
    _Bool _isCloseApp;
    _Bool _shouldSetStatusBarBack;
    _Bool _isBeenClicked;
    NSString *_h5_debug_url;
    PAZQOPStockWebView *_mainWebView;
    CDUnknownBlockType _returnBlock;
}

+ (id)shareInstance;
@property(nonatomic) _Bool isBeenClicked; // @synthesize isBeenClicked=_isBeenClicked;
@property(nonatomic) _Bool shouldSetStatusBarBack; // @synthesize shouldSetStatusBarBack=_shouldSetStatusBarBack;
@property(nonatomic) _Bool isCloseApp; // @synthesize isCloseApp=_isCloseApp;
@property(nonatomic) _Bool isMainModule; // @synthesize isMainModule=_isMainModule;
@property(copy, nonatomic) CDUnknownBlockType returnBlock; // @synthesize returnBlock=_returnBlock;
@property(retain, nonatomic) PAZQOPStockWebView *mainWebView; // @synthesize mainWebView=_mainWebView;
@property(copy, nonatomic) NSString *h5_debug_url; // @synthesize h5_debug_url=_h5_debug_url;
@property(nonatomic) _Bool h5_debug_mode; // @synthesize h5_debug_mode=_h5_debug_mode;
- (void).cxx_destruct;
- (void)updateStatusBarAppearance;
- (void)setTheStatusBarTitleColorBlack;
- (void)setTheStatusBarTitleColorWhite;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)loadingImageView;
- (void)startVidoe;
- (id)colorWithHexString:(id)arg1 alpha:(double)arg2;
- (id)translateAddonParams:(id)arg1;
- (id)webviewURLRequest;
- (void)setMainViewBackgroundColor;
- (void)initWithPAFWebView;
- (void)setHideBackgroundImageView:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (void)releasePAPhone:(id)arg1;
- (void)back;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

