//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableAttributedString, NSString;

@interface PAZQOPSpeakModel : NSObject
{
    NSString *_modelType;
    NSString *_channelID;
    NSString *_content;
    NSMutableAttributedString *_attributedString;
}

+ (id)attributedStringWithString:(id)arg1;
+ (id)modelWithContent:(id)arg1;
@property(retain, nonatomic) NSMutableAttributedString *attributedString; // @synthesize attributedString=_attributedString;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *channelID; // @synthesize channelID=_channelID;
@property(copy, nonatomic) NSString *modelType; // @synthesize modelType=_modelType;
- (void).cxx_destruct;

@end

