//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface PAZQOPGetServiceModel : NSObject
{
    NSString *_serviceUrlType;
    NSString *_abandonedQueueUrl;
    NSString *_getExtensionUrl;
    NSString *_pollingExtensionUrl;
    NSString *_refreshUrl;
    NSString *_releaseExtensionUrl;
    NSString *_ticketNo;
    NSString *_queueNo;
    NSString *_tokenDate;
    NSString *_tokenKey;
    NSString *_videoCalled;
    NSString *_setCustomType;
    NSString *_systemId;
    NSString *_registerInterval;
    NSString *_registerTryNum;
    NSString *_occupiedInterval;
    NSString *_addLogUrl;
    NSString *_printLogUrl;
    NSString *_mcpCallUrl;
    NSString *_mcpQueueInfoUrl;
    NSString *_mcpQueuePeople;
    NSString *_mcpQueuePeopleRequestType;
    NSString *_serviceMcpUrlType;
    NSString *_mcpQueueHearBeatInterval;
    NSString *_mcpCallDoUrl;
    NSString *_mcpQueuePeopleUrl;
    NSString *_delayedRequestTimes;
    NSString *_picompressionMin;
    NSString *_carmeraType;
    NSString *_getCarmeraURL;
    NSString *_getH5webURL;
    NSString *_screenshotsType;
    NSString *_saveVideoflowSNURL;
    NSString *_sipHearBeatMax;
    NSString *_sipHearBeatMin;
    NSString *_reportLogUrl;
    NSString *_sysAdvMsgUrl;
    NSString *_branchTime;
    NSString *_videoState;
    NSString *_openAccAccessUrl;
    NSString *_openAccAccessTimeOut;
    NSString *_CK_Key;
    NSString *_skinColor;
    NSString *_tokenKeyStr;
    NSString *_userCodeStr;
    NSString *_sourceKeyStr;
    NSString *_cybCfgCont;
}

+ (id)shareServiceModel;
@property(copy, nonatomic) NSString *cybCfgCont; // @synthesize cybCfgCont=_cybCfgCont;
@property(copy, nonatomic) NSString *sourceKeyStr; // @synthesize sourceKeyStr=_sourceKeyStr;
@property(copy, nonatomic) NSString *userCodeStr; // @synthesize userCodeStr=_userCodeStr;
@property(copy, nonatomic) NSString *tokenKeyStr; // @synthesize tokenKeyStr=_tokenKeyStr;
@property(copy, nonatomic) NSString *skinColor; // @synthesize skinColor=_skinColor;
@property(copy, nonatomic) NSString *CK_Key; // @synthesize CK_Key=_CK_Key;
@property(copy, nonatomic) NSString *openAccAccessTimeOut; // @synthesize openAccAccessTimeOut=_openAccAccessTimeOut;
@property(copy, nonatomic) NSString *openAccAccessUrl; // @synthesize openAccAccessUrl=_openAccAccessUrl;
@property(copy, nonatomic) NSString *videoState; // @synthesize videoState=_videoState;
@property(copy, nonatomic) NSString *branchTime; // @synthesize branchTime=_branchTime;
@property(copy, nonatomic) NSString *sysAdvMsgUrl; // @synthesize sysAdvMsgUrl=_sysAdvMsgUrl;
@property(copy, nonatomic) NSString *reportLogUrl; // @synthesize reportLogUrl=_reportLogUrl;
@property(copy, nonatomic) NSString *sipHearBeatMin; // @synthesize sipHearBeatMin=_sipHearBeatMin;
@property(copy, nonatomic) NSString *sipHearBeatMax; // @synthesize sipHearBeatMax=_sipHearBeatMax;
@property(copy, nonatomic) NSString *saveVideoflowSNURL; // @synthesize saveVideoflowSNURL=_saveVideoflowSNURL;
@property(copy, nonatomic) NSString *screenshotsType; // @synthesize screenshotsType=_screenshotsType;
@property(copy, nonatomic) NSString *getH5webURL; // @synthesize getH5webURL=_getH5webURL;
@property(copy, nonatomic) NSString *getCarmeraURL; // @synthesize getCarmeraURL=_getCarmeraURL;
@property(copy, nonatomic) NSString *carmeraType; // @synthesize carmeraType=_carmeraType;
@property(copy, nonatomic) NSString *picompressionMin; // @synthesize picompressionMin=_picompressionMin;
@property(copy, nonatomic) NSString *delayedRequestTimes; // @synthesize delayedRequestTimes=_delayedRequestTimes;
@property(copy, nonatomic) NSString *mcpQueuePeopleUrl; // @synthesize mcpQueuePeopleUrl=_mcpQueuePeopleUrl;
@property(copy, nonatomic) NSString *mcpCallDoUrl; // @synthesize mcpCallDoUrl=_mcpCallDoUrl;
@property(copy, nonatomic) NSString *mcpQueueHearBeatInterval; // @synthesize mcpQueueHearBeatInterval=_mcpQueueHearBeatInterval;
@property(copy, nonatomic) NSString *serviceMcpUrlType; // @synthesize serviceMcpUrlType=_serviceMcpUrlType;
@property(copy, nonatomic) NSString *mcpQueuePeopleRequestType; // @synthesize mcpQueuePeopleRequestType=_mcpQueuePeopleRequestType;
@property(copy, nonatomic) NSString *mcpQueuePeople; // @synthesize mcpQueuePeople=_mcpQueuePeople;
@property(copy, nonatomic) NSString *mcpQueueInfoUrl; // @synthesize mcpQueueInfoUrl=_mcpQueueInfoUrl;
@property(copy, nonatomic) NSString *mcpCallUrl; // @synthesize mcpCallUrl=_mcpCallUrl;
@property(copy, nonatomic) NSString *printLogUrl; // @synthesize printLogUrl=_printLogUrl;
@property(copy, nonatomic) NSString *addLogUrl; // @synthesize addLogUrl=_addLogUrl;
@property(copy, nonatomic) NSString *occupiedInterval; // @synthesize occupiedInterval=_occupiedInterval;
@property(copy, nonatomic) NSString *registerTryNum; // @synthesize registerTryNum=_registerTryNum;
@property(copy, nonatomic) NSString *registerInterval; // @synthesize registerInterval=_registerInterval;
@property(copy, nonatomic) NSString *systemId; // @synthesize systemId=_systemId;
@property(copy, nonatomic) NSString *setCustomType; // @synthesize setCustomType=_setCustomType;
@property(copy, nonatomic) NSString *videoCalled; // @synthesize videoCalled=_videoCalled;
@property(copy, nonatomic) NSString *tokenKey; // @synthesize tokenKey=_tokenKey;
@property(copy, nonatomic) NSString *tokenDate; // @synthesize tokenDate=_tokenDate;
@property(copy, nonatomic) NSString *queueNo; // @synthesize queueNo=_queueNo;
@property(copy, nonatomic) NSString *ticketNo; // @synthesize ticketNo=_ticketNo;
@property(copy, nonatomic) NSString *releaseExtensionUrl; // @synthesize releaseExtensionUrl=_releaseExtensionUrl;
@property(copy, nonatomic) NSString *refreshUrl; // @synthesize refreshUrl=_refreshUrl;
@property(copy, nonatomic) NSString *pollingExtensionUrl; // @synthesize pollingExtensionUrl=_pollingExtensionUrl;
@property(copy, nonatomic) NSString *getExtensionUrl; // @synthesize getExtensionUrl=_getExtensionUrl;
@property(copy, nonatomic) NSString *abandonedQueueUrl; // @synthesize abandonedQueueUrl=_abandonedQueueUrl;
@property(copy, nonatomic) NSString *serviceUrlType; // @synthesize serviceUrlType=_serviceUrlType;
- (void).cxx_destruct;
- (void)dealloc;
- (void)fillWithContent:(id)arg1 channel:(id)arg2;
- (void)cleanup;
- (id)init;

@end

