//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface redGreenModel : NSObject
{
    NSString *_stkid;
    long long _end;
    long long _show;
    long long _start;
    NSString *_type;
}

@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(nonatomic) long long start; // @synthesize start=_start;
@property(nonatomic) long long show; // @synthesize show=_show;
@property(nonatomic) long long end; // @synthesize end=_end;
@property(copy, nonatomic) NSString *stkid; // @synthesize stkid=_stkid;
- (void).cxx_destruct;

@end

