//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface SectionModel : NSObject
{
    _Bool _isWhiteBackgroundColor;
    NSString *_leftLabelString;
    NSString *_rightLabelString;
    NSNumber *_type;
    NSString *_highlightedString;
}

@property(nonatomic) _Bool isWhiteBackgroundColor; // @synthesize isWhiteBackgroundColor=_isWhiteBackgroundColor;
@property(retain, nonatomic) NSString *highlightedString; // @synthesize highlightedString=_highlightedString;
@property(retain, nonatomic) NSNumber *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *rightLabelString; // @synthesize rightLabelString=_rightLabelString;
@property(retain, nonatomic) NSString *leftLabelString; // @synthesize leftLabelString=_leftLabelString;
- (void).cxx_destruct;

@end

