//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJResponseModel.h"

@class NSString;

@interface ShortTermModel : JRJResponseModel
{
    NSString *_groupId;
    NSString *_selected;
    NSString *_groupType;
    NSString *_groupName;
}

@property(retain, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(retain, nonatomic) NSString *groupType; // @synthesize groupType=_groupType;
@property(retain, nonatomic) NSString *selected; // @synthesize selected=_selected;
@property(retain, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
- (void).cxx_destruct;

@end

