//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KKTableViewBaseCell.h"

@class UIButton, UILabel;

@interface StockSearchAndCancelModelCell : KKTableViewBaseCell
{
    UILabel *_buyLabel;
    UILabel *_priceDesLabel;
    UILabel *_priceValueLabel;
    UILabel *_amountDesLabel;
    UILabel *_amountValueLabel;
    UILabel *_nameCodeLabel;
    UILabel *_timeDesLabel;
    UILabel *_timeValueLabel;
    UILabel *_costFrozenDesLabel;
    UILabel *_costFrozenValueLabel;
    UILabel *_commissionStatusLabel;
    UIButton *_cancelBtn;
}

@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UILabel *commissionStatusLabel; // @synthesize commissionStatusLabel=_commissionStatusLabel;
@property(retain, nonatomic) UILabel *costFrozenValueLabel; // @synthesize costFrozenValueLabel=_costFrozenValueLabel;
@property(retain, nonatomic) UILabel *costFrozenDesLabel; // @synthesize costFrozenDesLabel=_costFrozenDesLabel;
@property(retain, nonatomic) UILabel *timeValueLabel; // @synthesize timeValueLabel=_timeValueLabel;
@property(retain, nonatomic) UILabel *timeDesLabel; // @synthesize timeDesLabel=_timeDesLabel;
@property(retain, nonatomic) UILabel *nameCodeLabel; // @synthesize nameCodeLabel=_nameCodeLabel;
@property(retain, nonatomic) UILabel *amountValueLabel; // @synthesize amountValueLabel=_amountValueLabel;
@property(retain, nonatomic) UILabel *amountDesLabel; // @synthesize amountDesLabel=_amountDesLabel;
@property(retain, nonatomic) UILabel *priceValueLabel; // @synthesize priceValueLabel=_priceValueLabel;
@property(retain, nonatomic) UILabel *priceDesLabel; // @synthesize priceDesLabel=_priceDesLabel;
@property(retain, nonatomic) UILabel *buyLabel; // @synthesize buyLabel=_buyLabel;
- (void).cxx_destruct;
- (void)updateCellWithSource:(id)arg1;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

