//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FTPOSTRequest.h"

@class NSString;

@interface StockIndexRankRequest : FTPOSTRequest
{
    long long _type;
    NSString *_indexCode;
}

@property(copy, nonatomic) NSString *indexCode; // @synthesize indexCode=_indexCode;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)typeString;
- (id)baseRequestPaths;

@end

