//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseViewController.h"

#import "UIAlertViewDelegate-Protocol.h"

@class BuyWebViewController, NSString;

@interface StockTransferViewController : JRJBaseViewController <UIAlertViewDelegate>
{
    BuyWebViewController *bwc;
    int _funTypeIndex;
}

@property(nonatomic) int funTypeIndex; // @synthesize funTypeIndex=_funTypeIndex;
- (void).cxx_destruct;
- (id)title;
- (void)handleTranserRecord:(id)arg1;
- (void)showWebController:(id)arg1 andTitle:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)transferOperation:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

