//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber;

@interface StockPositionModel : NSObject
{
    long long _total;
    NSNumber *_positionStr;
    NSArray *_items;
}

+ (id)mj_objectClassInArray;
@property(copy, nonatomic) NSArray *items; // @synthesize items=_items;
@property(retain, nonatomic) NSNumber *positionStr; // @synthesize positionStr=_positionStr;
@property(nonatomic) long long total; // @synthesize total=_total;
- (void).cxx_destruct;

@end

