//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseViewController.h"

@class JRJOrdinaryUserController, NSString, UILabel;

@interface TouGuAuthStateController : JRJBaseViewController
{
    long long _touGuAuthState;
    NSString *_errorStr;
    JRJOrdinaryUserController *_userHomeViewController;
    UILabel *_messageLabel;
}

@property(copy, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(nonatomic) JRJOrdinaryUserController *userHomeViewController; // @synthesize userHomeViewController=_userHomeViewController;
@property(copy, nonatomic) NSString *errorStr; // @synthesize errorStr=_errorStr;
@property(nonatomic) long long touGuAuthState; // @synthesize touGuAuthState=_touGuAuthState;
- (void).cxx_destruct;
- (id)title;
- (void)nextClick;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)setNextButton;
- (void)telAction:(id)arg1;
- (void)addTelView;
- (id)setStyleMessage;
- (void)addImageStyle;
- (void)closeBarButtonitemClick;
- (id)closeBarButtonItem;
- (void)setLeftNavigationItemBarButton;
- (void)viewDidLoad;

@end

