//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSNumber, NSString;

@interface TouTiaoYaoWenModel : NSObject
{
    NSNumber *_iiid;
    NSString *_title;
    NSString *_author;
    NSString *_infourl;
    NSString *_detail;
    NSNumber *_apptop;
    NSString *_listdate;
    NSString *_timestamp;
    NSString *_channum;
    NSString *_infocls;
    NSString *_plid;
    long long _click;
    long long _comment;
    NSNumber *_isImportant;
    NSArray *_infostocks;
    long long _isBear;
    NSArray *_conceptList;
}

+ (id)mj_objectClassInArray;
@property(retain, nonatomic) NSArray *conceptList; // @synthesize conceptList=_conceptList;
@property(nonatomic) long long isBear; // @synthesize isBear=_isBear;
@property(retain, nonatomic) NSArray *infostocks; // @synthesize infostocks=_infostocks;
@property(retain, nonatomic) NSNumber *isImportant; // @synthesize isImportant=_isImportant;
@property(nonatomic) long long comment; // @synthesize comment=_comment;
@property(nonatomic) long long click; // @synthesize click=_click;
@property(copy, nonatomic) NSString *plid; // @synthesize plid=_plid;
@property(copy, nonatomic) NSString *infocls; // @synthesize infocls=_infocls;
@property(copy, nonatomic) NSString *channum; // @synthesize channum=_channum;
@property(copy, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
@property(copy, nonatomic) NSString *listdate; // @synthesize listdate=_listdate;
@property(retain, nonatomic) NSNumber *apptop; // @synthesize apptop=_apptop;
@property(copy, nonatomic) NSString *detail; // @synthesize detail=_detail;
@property(copy, nonatomic) NSString *infourl; // @synthesize infourl=_infourl;
@property(copy, nonatomic) NSString *author; // @synthesize author=_author;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSNumber *iiid; // @synthesize iiid=_iiid;
- (void).cxx_destruct;

@end

