//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseCell.h"

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSString, TouTiaoInfoCrossFlowModel, UIButton, UICollectionView, UILabel;

@interface TouTiaoCrossFlowCell : JRJBaseCell <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    CDUnknownBlockType _userIconClickBlock;
    UILabel *_titleLbl;
    UIButton *_moreBtn;
    UICollectionView *_collectionView;
    TouTiaoInfoCrossFlowModel *_flowModel;
    CDUnknownBlockType _didSelectItemBlock;
    CDUnknownBlockType _moreBtnClickBlock;
}

@property(copy, nonatomic) CDUnknownBlockType moreBtnClickBlock; // @synthesize moreBtnClickBlock=_moreBtnClickBlock;
@property(copy, nonatomic) CDUnknownBlockType didSelectItemBlock; // @synthesize didSelectItemBlock=_didSelectItemBlock;
@property(retain, nonatomic) TouTiaoInfoCrossFlowModel *flowModel; // @synthesize flowModel=_flowModel;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak UIButton *moreBtn; // @synthesize moreBtn=_moreBtn;
@property(nonatomic) __weak UILabel *titleLbl; // @synthesize titleLbl=_titleLbl;
@property(copy, nonatomic) CDUnknownBlockType userIconClickBlock; // @synthesize userIconClickBlock=_userIconClickBlock;
- (void).cxx_destruct;
- (void)setMoreBtnBlock:(CDUnknownBlockType)arg1;
- (void)setDidSelectBlock:(CDUnknownBlockType)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)moreBtnClick:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)p_getTypeStrWithType:(long long)arg1;
- (void)updateCellWithCrossFlowModel:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

