//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseHeaderFooterView.h"

@class JRJInvestCalendarHandler, JRJInvestCalendarMainModel, NSArray, NSDictionary, UIButton, UIImageView;

@interface ToutiaoMustReadHeaderView : JRJBaseHeaderFooterView
{
    NSArray *_images;
    NSDictionary *_bgImagesDic;
    UIImageView *backgroundIV;
    UIButton *checkBtn;
    _Bool _isBigShotEmpty;
    CDUnknownBlockType _pushToZQCXBlock;
    NSArray *_imageViews;
    NSArray *_titleLabels;
    NSArray *_timeLabels;
    JRJInvestCalendarHandler *_handler;
    JRJInvestCalendarMainModel *_calendarModel;
}

@property(retain, nonatomic) JRJInvestCalendarMainModel *calendarModel; // @synthesize calendarModel=_calendarModel;
@property(retain, nonatomic) JRJInvestCalendarHandler *handler; // @synthesize handler=_handler;
@property(retain, nonatomic) NSArray *timeLabels; // @synthesize timeLabels=_timeLabels;
@property(retain, nonatomic) NSArray *titleLabels; // @synthesize titleLabels=_titleLabels;
@property(retain, nonatomic) NSArray *imageViews; // @synthesize imageViews=_imageViews;
@property(copy, nonatomic) CDUnknownBlockType pushToZQCXBlock; // @synthesize pushToZQCXBlock=_pushToZQCXBlock;
- (void).cxx_destruct;
- (void)btnClick:(id)arg1;
- (void)p_updateCalendarWithModel:(id)arg1;
- (void)bindDataWithArray:(id)arg1;
- (void)requestCalendarInfo;
- (void)requestWholeNetWorkTopNum;
- (void)requestStockInfoData;
- (void)refreshData;
- (void)awakeFromNib;

@end

