//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJBaseCell.h"

@class TextFloatUpView, UIView;

@interface ToutiaoAdLeftRightCell : JRJBaseCell
{
    _Bool _isDataBinded;
    UIView *_leftView;
    UIView *_rightView;
    TextFloatUpView *_textFloatUpView;
}

@property(nonatomic) __weak TextFloatUpView *textFloatUpView; // @synthesize textFloatUpView=_textFloatUpView;
@property(nonatomic) __weak UIView *rightView; // @synthesize rightView=_rightView;
@property(nonatomic) __weak UIView *leftView; // @synthesize leftView=_leftView;
- (void).cxx_destruct;
- (void)clearAllData;
- (void)shouldStartRefresh:(_Bool)arg1;
- (void)bindDataWithDic:(id)arg1;

@end

