//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TradeEFTableAlertCell.h"

@class JRJTradeBuyAndSellRiskListModel, UIButton, UILabel;

@interface TradeBuyOrSellVentureAlertCell : TradeEFTableAlertCell
{
    CDUnknownBlockType _selectedBlock;
    UIButton *_selectBtn;
    UILabel *_contentLbl;
    long long _index;
    JRJTradeBuyAndSellRiskListModel *_riskListModel;
}

@property(retain, nonatomic) JRJTradeBuyAndSellRiskListModel *riskListModel; // @synthesize riskListModel=_riskListModel;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(nonatomic) __weak UILabel *contentLbl; // @synthesize contentLbl=_contentLbl;
@property(nonatomic) __weak UIButton *selectBtn; // @synthesize selectBtn=_selectBtn;
@property(copy, nonatomic) CDUnknownBlockType selectedBlock; // @synthesize selectedBlock=_selectedBlock;
- (void).cxx_destruct;
- (void)setBtnSelectStyleWithIselect:(_Bool)arg1;
- (void)selectBtnClick:(id)arg1;
- (void)configCellWithModel:(id)arg1 index:(long long)arg2;

@end

