//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

@interface TradeFundInfoModel : NSObject
{
    NSNumber *_currentBalance;
    NSNumber *_enableBalance;
    NSNumber *_fetchBalance;
    NSNumber *_frozenBalance;
    NSNumber *_unfrozenBalance;
    NSNumber *_fundBalance;
    NSNumber *_incomeBalance;
    NSNumber *_assetPrice;
    NSNumber *_profitAmount;
    NSNumber *_deficitAmount;
    NSNumber *_fairAmount;
    NSString *_percent;
    NSString *_clearPeriodTip;
    NSString *_notCommissionPeriodTip;
}

@property(copy, nonatomic) NSString *notCommissionPeriodTip; // @synthesize notCommissionPeriodTip=_notCommissionPeriodTip;
@property(copy, nonatomic) NSString *clearPeriodTip; // @synthesize clearPeriodTip=_clearPeriodTip;
@property(copy, nonatomic) NSString *percent; // @synthesize percent=_percent;
@property(retain, nonatomic) NSNumber *fairAmount; // @synthesize fairAmount=_fairAmount;
@property(retain, nonatomic) NSNumber *deficitAmount; // @synthesize deficitAmount=_deficitAmount;
@property(retain, nonatomic) NSNumber *profitAmount; // @synthesize profitAmount=_profitAmount;
@property(retain, nonatomic) NSNumber *assetPrice; // @synthesize assetPrice=_assetPrice;
@property(retain, nonatomic) NSNumber *incomeBalance; // @synthesize incomeBalance=_incomeBalance;
@property(retain, nonatomic) NSNumber *fundBalance; // @synthesize fundBalance=_fundBalance;
@property(retain, nonatomic) NSNumber *unfrozenBalance; // @synthesize unfrozenBalance=_unfrozenBalance;
@property(retain, nonatomic) NSNumber *frozenBalance; // @synthesize frozenBalance=_frozenBalance;
@property(retain, nonatomic) NSNumber *fetchBalance; // @synthesize fetchBalance=_fetchBalance;
@property(retain, nonatomic) NSNumber *enableBalance; // @synthesize enableBalance=_enableBalance;
@property(retain, nonatomic) NSNumber *currentBalance; // @synthesize currentBalance=_currentBalance;
- (void).cxx_destruct;

@end

