//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KKTableViewController.h"

@class KKTitleSource, TradeXJBAccountInfoModel, TradeXJBHandler, TradeXJBHeaderView, TradeXJBSource, UIButton;

@interface TradeXJBViewController : KKTableViewController
{
    float _maskHeight;
    float _maskTop;
    float _retainBalance;
    TradeXJBHeaderView *_tradeXJBHeaderView;
    TradeXJBHandler *_tradeXJBHandler;
    UIButton *_cashBtn;
    TradeXJBAccountInfoModel *_model;
    KKTitleSource *_source1;
    TradeXJBSource *_source2;
    TradeXJBSource *_source3;
    KKTitleSource *_source5;
}

@property(nonatomic) float retainBalance; // @synthesize retainBalance=_retainBalance;
@property(retain, nonatomic) KKTitleSource *source5; // @synthesize source5=_source5;
@property(retain, nonatomic) TradeXJBSource *source3; // @synthesize source3=_source3;
@property(retain, nonatomic) TradeXJBSource *source2; // @synthesize source2=_source2;
@property(retain, nonatomic) KKTitleSource *source1; // @synthesize source1=_source1;
@property(retain, nonatomic) TradeXJBAccountInfoModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIButton *cashBtn; // @synthesize cashBtn=_cashBtn;
@property(retain, nonatomic) TradeXJBHandler *tradeXJBHandler; // @synthesize tradeXJBHandler=_tradeXJBHandler;
@property(retain, nonatomic) TradeXJBHeaderView *tradeXJBHeaderView; // @synthesize tradeXJBHeaderView=_tradeXJBHeaderView;
- (void).cxx_destruct;
- (id)title;
- (void)addFootView;
- (void)showOpenAlertWithTitle:(id)arg1;
- (void)showOpenAlertErrorWithTitle:(id)arg1;
- (void)openXJBWithStatus:(long long)arg1;
- (void)changeXJBStatus:(long long)arg1;
- (void)sendRequest;
- (void)rightBarButtonitemClick;
- (void)addCellClickEvent;
- (void)loadDataSourceWithModel:(id)arg1;
- (void)sendObtainXJBStatusRequest;
- (void)viewDidLoad;

@end

