//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton;

@interface TradeBottomToolBarView : UIView
{
    CDUnknownBlockType _leftBlock;
    CDUnknownBlockType _rightBlock;
    UIButton *_leftBtn;
    UIButton *_rightBtn;
}

@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) UIButton *leftBtn; // @synthesize leftBtn=_leftBtn;
@property(copy, nonatomic) CDUnknownBlockType rightBlock; // @synthesize rightBlock=_rightBlock;
@property(copy, nonatomic) CDUnknownBlockType leftBlock; // @synthesize leftBlock=_leftBlock;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1 titleAry:(id)arg2;

@end

