//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TradeEFinanceMainHeaderModel : NSObject
{
    double _dayYield;
    double _yearYield;
    double _pledgeTerms;
    double _totalPledgeBalance;
    NSString *_deadline;
    long long _isPledged;
    long long _showCanPledgeList;
}

@property(nonatomic) long long showCanPledgeList; // @synthesize showCanPledgeList=_showCanPledgeList;
@property(nonatomic) long long isPledged; // @synthesize isPledged=_isPledged;
@property(copy, nonatomic) NSString *deadline; // @synthesize deadline=_deadline;
@property(nonatomic) double totalPledgeBalance; // @synthesize totalPledgeBalance=_totalPledgeBalance;
@property(nonatomic) double pledgeTerms; // @synthesize pledgeTerms=_pledgeTerms;
@property(nonatomic) double yearYield; // @synthesize yearYield=_yearYield;
@property(nonatomic) double dayYield; // @synthesize dayYield=_dayYield;
- (void).cxx_destruct;

@end

