//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KKTableViewController.h"

@class NSArray, NSString, TradeBankAccountInfoModel, TradeBankPasswordConfigModel, TradeBankToSecurityHandler, TradeBottomToolBarView, TradeFundInfoModel, TradePublicHandler;

@interface TradeBankSecurityMainVC : KKTableViewController
{
    NSArray *_modelAry;
    NSString *_bankPassword;
    NSString *_fundPassword;
    NSString *_password;
    TradeBankAccountInfoModel *_bankInfoModel;
    TradeFundInfoModel *_tradeFundInfoModel;
    TradeBankPasswordConfigModel *_passwordModel;
    TradeBankToSecurityHandler *_tradeBankToSecurityHandler;
    TradePublicHandler *_tradePublicHandler;
    TradeBottomToolBarView *_tradeBottomToolBarView;
}

@property(retain, nonatomic) TradeBottomToolBarView *tradeBottomToolBarView; // @synthesize tradeBottomToolBarView=_tradeBottomToolBarView;
@property(retain, nonatomic) TradePublicHandler *tradePublicHandler; // @synthesize tradePublicHandler=_tradePublicHandler;
@property(retain, nonatomic) TradeBankToSecurityHandler *tradeBankToSecurityHandler; // @synthesize tradeBankToSecurityHandler=_tradeBankToSecurityHandler;
@property(retain, nonatomic) TradeBankPasswordConfigModel *passwordModel; // @synthesize passwordModel=_passwordModel;
@property(retain, nonatomic) TradeFundInfoModel *tradeFundInfoModel; // @synthesize tradeFundInfoModel=_tradeFundInfoModel;
@property(retain, nonatomic) TradeBankAccountInfoModel *bankInfoModel; // @synthesize bankInfoModel=_bankInfoModel;
- (void).cxx_destruct;
- (void)getCurrentModelWithType:(int)arg1;
- (void)refreshViewBeginRefresh:(id)arg1;
- (id)title;
- (void)handleBankSecurityTransferActionWithType:(int)arg1;
- (id)genPwdShowInfo;
- (void)handleQueryBanlance;
- (void)handleQueryBanlanceHT;
- (void)addClickCellEvent;
- (void)handleResponse;
- (_Bool)validParaIsNotEmpty;
- (void)requestBankBalanceRequest;
- (void)requestDepositClientFund;
- (void)requestDepositBank;
- (void)requestBankTransAccount;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

