//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSMutableArray, NSString, UIButton, UILabel, UIView;

@interface TradeConfirmOrderVC : UITableViewController
{
    NSMutableArray *_modelArr;
    UIView *_footerView;
    UILabel *_footerLbl;
    UIButton *_footerBtn;
    NSString *_footerPageMsg;
    long long _fromVCType;
}

@property(nonatomic) long long fromVCType; // @synthesize fromVCType=_fromVCType;
@property(copy, nonatomic) NSString *footerPageMsg; // @synthesize footerPageMsg=_footerPageMsg;
@property(retain, nonatomic) UIButton *footerBtn; // @synthesize footerBtn=_footerBtn;
@property(retain, nonatomic) UILabel *footerLbl; // @synthesize footerLbl=_footerLbl;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) NSMutableArray *modelArr; // @synthesize modelArr=_modelArr;
- (void).cxx_destruct;
- (id)title;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)popToEFMainVC;
- (void)addAutoLayout;
- (void)viewDidLoad;
- (id)initWithPledgeOperationModel:(id)arg1 fromVCType:(long long)arg2;

@end

