//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface TradeMYPledgeMiddleView : UIView
{
    UILabel *_leftZeroValue;
    UILabel *_leftOneValue;
    UILabel *_leftTwoValue;
    UILabel *_leftThreeValue;
    UILabel *_leftFourValue;
    UILabel *_rightZeroValue;
    UILabel *_rightOneValue;
    UILabel *_rightTwoValue;
    UILabel *_rightThreeValue;
    UILabel *_rightFourValue;
}

+ (id)viewFromNib;
@property(nonatomic) __weak UILabel *rightFourValue; // @synthesize rightFourValue=_rightFourValue;
@property(nonatomic) __weak UILabel *rightThreeValue; // @synthesize rightThreeValue=_rightThreeValue;
@property(nonatomic) __weak UILabel *rightTwoValue; // @synthesize rightTwoValue=_rightTwoValue;
@property(nonatomic) __weak UILabel *rightOneValue; // @synthesize rightOneValue=_rightOneValue;
@property(nonatomic) __weak UILabel *rightZeroValue; // @synthesize rightZeroValue=_rightZeroValue;
@property(nonatomic) __weak UILabel *leftFourValue; // @synthesize leftFourValue=_leftFourValue;
@property(nonatomic) __weak UILabel *leftThreeValue; // @synthesize leftThreeValue=_leftThreeValue;
@property(nonatomic) __weak UILabel *leftTwoValue; // @synthesize leftTwoValue=_leftTwoValue;
@property(nonatomic) __weak UILabel *leftOneValue; // @synthesize leftOneValue=_leftOneValue;
@property(nonatomic) __weak UILabel *leftZeroValue; // @synthesize leftZeroValue=_leftZeroValue;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

