//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TreemapBlockPlatInfoModel : NSObject
{
    NSString *_platName;
    NSString *_securityId;
    NSString *_timeString;
    NSString *_quotationTime;
    NSString *_lastPx;
    NSString *_pxChgRatio;
    NSString *_upCount;
    NSString *_downCount;
    NSString *_equalCount;
    NSString *_netInflow;
}

@property(copy, nonatomic) NSString *netInflow; // @synthesize netInflow=_netInflow;
@property(copy, nonatomic) NSString *equalCount; // @synthesize equalCount=_equalCount;
@property(copy, nonatomic) NSString *downCount; // @synthesize downCount=_downCount;
@property(copy, nonatomic) NSString *upCount; // @synthesize upCount=_upCount;
@property(copy, nonatomic) NSString *pxChgRatio; // @synthesize pxChgRatio=_pxChgRatio;
@property(copy, nonatomic) NSString *lastPx; // @synthesize lastPx=_lastPx;
@property(copy, nonatomic) NSString *quotationTime; // @synthesize quotationTime=_quotationTime;
@property(copy, nonatomic) NSString *timeString; // @synthesize timeString=_timeString;
@property(copy, nonatomic) NSString *securityId; // @synthesize securityId=_securityId;
@property(copy, nonatomic) NSString *platName; // @synthesize platName=_platName;
- (void).cxx_destruct;

@end

