//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, TreemapBlockPlatInfoModel, TreemapBlockStockInfoModel;

@interface TreemapBlockListModel : NSObject
{
    NSString *_platName;
    NSString *_platCode;
    NSString *_stockCode;
    NSString *_stockName;
    NSString *_cmv;
    NSString *_netInflow;
    NSString *_advanceDeclineRatio;
    TreemapBlockPlatInfoModel *_platModel;
    TreemapBlockStockInfoModel *_stockModel;
}

+ (id)modelCustomPropertyMapper;
@property(retain, nonatomic) TreemapBlockStockInfoModel *stockModel; // @synthesize stockModel=_stockModel;
@property(retain, nonatomic) TreemapBlockPlatInfoModel *platModel; // @synthesize platModel=_platModel;
@property(copy, nonatomic) NSString *advanceDeclineRatio; // @synthesize advanceDeclineRatio=_advanceDeclineRatio;
@property(copy, nonatomic) NSString *netInflow; // @synthesize netInflow=_netInflow;
@property(copy, nonatomic) NSString *cmv; // @synthesize cmv=_cmv;
@property(copy, nonatomic) NSString *stockName; // @synthesize stockName=_stockName;
@property(copy, nonatomic) NSString *stockCode; // @synthesize stockCode=_stockCode;
@property(copy, nonatomic) NSString *platCode; // @synthesize platCode=_platCode;
@property(copy, nonatomic) NSString *platName; // @synthesize platName=_platName;
- (void).cxx_destruct;

@end

