//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (BadgeView)
- (id)delImageViewWithDelegate:(id)arg1;
- (id)badgeLabel;
- (id)redPoint;
- (id)delPoint;
- (void)removeDelView;
- (void)showDelPointWithDelegate:(id)arg1;
- (void)showRedpoint;
- (void)removeRedPointView;
- (id)addRedPointView;
- (void)removeBadgeView;
- (id)addBadgeView;
- (void)showBadgeView:(long long)arg1;
@end

