//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AdviserModel, JRJModelFrame, NSArray, NSAttributedString, NSNumber, NSString;

@interface ViewPointModel : NSObject
{
    _Bool _expandable;
    _Bool _expanded;
    _Bool _hasBuy;
    _Bool _hidesBottomBorder;
    long long _ctime;
    NSString *_title;
    NSString *_summary;
    NSString *_pubTime;
    NSNumber *_riseDrop;
    NSString *_pubDate;
    NSString *_subContent;
    NSString *_mainContent;
    NSString *_answerContent;
    NSString *_userId;
    NSString *_userName;
    NSString *_pic;
    NSString *_contentType;
    NSString *_contentImage;
    NSArray *_imgs;
    long long _ID;
    long long _subId;
    NSString *_sourceId;
    long long _praise;
    long long _reads;
    long long _subType;
    NSArray *_stocks;
    NSString *_linkUrl;
    NSString *_stockCode;
    NSString *_stockName;
    NSString *_stockMk;
    NSNumber *_stockPl;
    long long _stockStp;
    AdviserModel *_user;
    CDUnknownBlockType _block;
    CDUnknownBlockType _imgTapBlock;
    CDUnknownBlockType _anyTypeBlock;
    long long _tag;
    NSString *_replyUserId;
    NSString *_replyUserName;
    NSString *_replyContent;
    long long _type;
    JRJModelFrame *_frame;
    long long _price;
    NSAttributedString *_contentAttrText;
    NSAttributedString *_quoteAttrText;
    AdviserModel *_userInfo;
}

+ (id)mj_replacedKeyFromPropertyName;
@property(retain, nonatomic) AdviserModel *userInfo; // @synthesize userInfo=_userInfo;
@property(retain, nonatomic) NSAttributedString *quoteAttrText; // @synthesize quoteAttrText=_quoteAttrText;
@property(retain, nonatomic) NSAttributedString *contentAttrText; // @synthesize contentAttrText=_contentAttrText;
@property(nonatomic) long long price; // @synthesize price=_price;
@property(nonatomic) _Bool hidesBottomBorder; // @synthesize hidesBottomBorder=_hidesBottomBorder;
@property(nonatomic) _Bool hasBuy; // @synthesize hasBuy=_hasBuy;
@property(nonatomic) _Bool expanded; // @synthesize expanded=_expanded;
@property(nonatomic) _Bool expandable; // @synthesize expandable=_expandable;
@property(retain, nonatomic) JRJModelFrame *frame; // @synthesize frame=_frame;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *replyContent; // @synthesize replyContent=_replyContent;
@property(retain, nonatomic) NSString *replyUserName; // @synthesize replyUserName=_replyUserName;
@property(retain, nonatomic) NSString *replyUserId; // @synthesize replyUserId=_replyUserId;
@property(nonatomic) long long tag; // @synthesize tag=_tag;
@property(copy, nonatomic) CDUnknownBlockType anyTypeBlock; // @synthesize anyTypeBlock=_anyTypeBlock;
@property(copy, nonatomic) CDUnknownBlockType imgTapBlock; // @synthesize imgTapBlock=_imgTapBlock;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(retain, nonatomic) AdviserModel *user; // @synthesize user=_user;
@property(nonatomic) long long stockStp; // @synthesize stockStp=_stockStp;
@property(copy, nonatomic) NSNumber *stockPl; // @synthesize stockPl=_stockPl;
@property(copy, nonatomic) NSString *stockMk; // @synthesize stockMk=_stockMk;
@property(copy, nonatomic) NSString *stockName; // @synthesize stockName=_stockName;
@property(copy, nonatomic) NSString *stockCode; // @synthesize stockCode=_stockCode;
@property(copy, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(copy, nonatomic) NSArray *stocks; // @synthesize stocks=_stocks;
@property(nonatomic) long long subType; // @synthesize subType=_subType;
@property(nonatomic) long long reads; // @synthesize reads=_reads;
@property(nonatomic) long long praise; // @synthesize praise=_praise;
@property(nonatomic) NSString *sourceId; // @synthesize sourceId=_sourceId;
@property(nonatomic) long long subId; // @synthesize subId=_subId;
@property(nonatomic) long long ID; // @synthesize ID=_ID;
@property(retain, nonatomic) NSArray *imgs; // @synthesize imgs=_imgs;
@property(retain, nonatomic) NSString *contentImage; // @synthesize contentImage=_contentImage;
@property(copy, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(copy, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(copy, nonatomic) NSString *answerContent; // @synthesize answerContent=_answerContent;
@property(copy, nonatomic) NSString *mainContent; // @synthesize mainContent=_mainContent;
@property(copy, nonatomic) NSString *subContent; // @synthesize subContent=_subContent;
@property(nonatomic) NSString *pubDate; // @synthesize pubDate=_pubDate;
@property(copy, nonatomic) NSNumber *riseDrop; // @synthesize riseDrop=_riseDrop;
@property(nonatomic) NSString *pubTime; // @synthesize pubTime=_pubTime;
@property(copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long ctime; // @synthesize ctime=_ctime;
- (void).cxx_destruct;
- (void)stripHTMLTags;
- (void)convertIndexModelToViewpoint;
- (id)quoteText;

@end

