//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIViewController, WMPageController;

@protocol WMPageControllerDelegate <NSObject>
- (long long)numberOfPages:(WMPageController *)arg1;

@optional
- (void)willSlidePageController:(WMPageController *)arg1 index:(long long)arg2;
- (void)didSelectedPageController:(WMPageController *)arg1 index:(long long)arg2;
- (double)heightForPageController:(long long)arg1;
- (UIViewController *)pageControllerForIndex:(long long)arg1;
- (NSString *)pageController:(WMPageController *)arg1 titleForPageIndex:(long long)arg2;
@end

