//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIColor, UIFont, UIImage;

@interface WyhChannelStyle : NSObject
{
    _Bool _isShowBorder;
    _Bool _isShowCover;
    _Bool _isShowHot;
    _Bool _isShowPlaceHolderView;
    _Bool _isShowBackCover;
    double _padding;
    double _closeBtnW;
    UIImage *_closeImage;
    UIFont *_font;
    UIColor *_normalTextColor;
    UIColor *_selectedTextColor;
    UIImage *_hotImage;
    double _hotImageW;
    UIImage *_coverTopImage;
    UIImage *_coverBottomImage;
    NSString *_bottomTitle;
}

@property(nonatomic) _Bool isShowBackCover; // @synthesize isShowBackCover=_isShowBackCover;
@property(nonatomic) _Bool isShowPlaceHolderView; // @synthesize isShowPlaceHolderView=_isShowPlaceHolderView;
@property(copy, nonatomic) NSString *bottomTitle; // @synthesize bottomTitle=_bottomTitle;
@property(nonatomic) _Bool isShowHot; // @synthesize isShowHot=_isShowHot;
@property(nonatomic) _Bool isShowCover; // @synthesize isShowCover=_isShowCover;
@property(nonatomic) _Bool isShowBorder; // @synthesize isShowBorder=_isShowBorder;
@property(retain, nonatomic) UIImage *coverBottomImage; // @synthesize coverBottomImage=_coverBottomImage;
@property(retain, nonatomic) UIImage *coverTopImage; // @synthesize coverTopImage=_coverTopImage;
@property(nonatomic) double hotImageW; // @synthesize hotImageW=_hotImageW;
@property(retain, nonatomic) UIImage *hotImage; // @synthesize hotImage=_hotImage;
@property(retain, nonatomic) UIColor *selectedTextColor; // @synthesize selectedTextColor=_selectedTextColor;
@property(retain, nonatomic) UIColor *normalTextColor; // @synthesize normalTextColor=_normalTextColor;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) UIImage *closeImage; // @synthesize closeImage=_closeImage;
@property(nonatomic) double closeBtnW; // @synthesize closeBtnW=_closeBtnW;
@property(nonatomic) double padding; // @synthesize padding=_padding;
- (void).cxx_destruct;
- (id)init;

@end

