//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JRJInputAccessoryView.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, XinGuQiuZhongQianTextView;

@interface XinGuZQAccessoryView : JRJInputAccessoryView <UITextFieldDelegate>
{
    _Bool _isShowText;
    XinGuQiuZhongQianTextView *_XGZQTextView;
}

@property(retain, nonatomic) XinGuQiuZhongQianTextView *XGZQTextView; // @synthesize XGZQTextView=_XGZQTextView;
@property(nonatomic) _Bool isShowText; // @synthesize isShowText=_isShowText;
- (void).cxx_destruct;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)emotionButtonPressed:(id)arg1;
- (void)stockButtonPressed:(id)arg1;
- (void)beginEditing;
- (void)showEmotionView;
- (void)setStockBtnSelectedUI:(_Bool)arg1;
- (void)insertQiuZhongQianTextWithStr:(id)arg1;
- (void)hideXGZQTextView;
- (void)showXGZQTextView;
- (void)drawRect:(struct CGRect)arg1;
- (void)addQiuZhongQianView;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

