//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface ZdtKLineModel : NSObject
{
    NSString *_date;
    NSMutableArray *_items;
    long long _numMax;
    long long _numMin;
    double _todayPlMax;
    double _todayPlMin;
    unsigned long long _zqStatus;
}

+ (id)mj_replacedKeyFromPropertyName;
@property(nonatomic) unsigned long long zqStatus; // @synthesize zqStatus=_zqStatus;
@property(nonatomic) double todayPlMin; // @synthesize todayPlMin=_todayPlMin;
@property(nonatomic) double todayPlMax; // @synthesize todayPlMax=_todayPlMax;
@property(nonatomic) long long numMin; // @synthesize numMin=_numMin;
@property(nonatomic) long long numMax; // @synthesize numMax=_numMax;
@property(retain, nonatomic) NSMutableArray *items; // @synthesize items=_items;
@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
- (void).cxx_destruct;
- (long long)getLastTime;
- (void)p_removeItemsGreaterThanOrEqualTo:(long long)arg1;
- (void)clearItems;
- (void)calMaxAndMinValue;
- (void)calZqStatus;
- (void)addItems:(id)arg1 withDate:(id)arg2;
- (id)init;

@end

