//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RichUserInfoXibView.h"

@class UIImageView, UILabel, ZhiboAdviseModel;

@interface ZhiboAdviseCell : RichUserInfoXibView
{
    CDUnknownBlockType _imageTouchedBlock;
    UILabel *_titleLabel;
    UIImageView *_zhiboImageView;
    UIImageView *_hotImageView;
    ZhiboAdviseModel *_zhiboModel;
}

+ (double)heightWithModel:(id)arg1;
@property(retain, nonatomic) ZhiboAdviseModel *zhiboModel; // @synthesize zhiboModel=_zhiboModel;
@property(retain, nonatomic) UIImageView *hotImageView; // @synthesize hotImageView=_hotImageView;
@property(retain, nonatomic) UIImageView *zhiboImageView; // @synthesize zhiboImageView=_zhiboImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(copy, nonatomic) CDUnknownBlockType imageTouchedBlock; // @synthesize imageTouchedBlock=_imageTouchedBlock;
- (void).cxx_destruct;
- (void)imageViewTaped:(id)arg1;
- (void)layoutSubviews;
- (void)configCellWithModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

