//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>
#import <UIKit/UIKit.h>

@interface UiUtil : NSObject
{
}

+ (void)showCameraAlertForSplitViewIfNeed:(id)arg1 currentWidth:(double)arg2;
+ (_Bool)isiPadSplitViewModeNow;
+ (_Bool)isiPadSplitViewMinimizeModeNow;
+ (void)setStatusBarStyle:(long long)arg1 viewController:(id)arg2;
+ (void)setStatusBarStyle:(long long)arg1;
+ (void)setStatusBarFontBlack;
+ (void)setStatusBarFontWhite;
+ (_Bool)hasRoundCorner;
+ (double)bottomInset;
+ (double)tabBarContentHeight;
+ (double)tabBarHeight;
+ (double)topBarNormalOffset;
+ (_Bool)isTopBarInNormalState;
+ (double)keyboardHeightByNotification:(id)arg1;
+ (void)setTopBarHidden:(_Bool)arg1 withAnimation:(long long)arg2;
+ (void)setTopBarHidden:(_Bool)arg1;
+ (_Bool)isTopBarHidden;
+ (long long)getRotatedOrientation;
+ (void)setStatusBarHidden:(_Bool)arg1 withAnimation:(long long)arg2;
+ (void)setStatusBarHidden:(_Bool)arg1;
+ (_Bool)isStatusBarLandscape;
+ (_Bool)isStatusBarHidden;
+ (void)OnSystemStatusBarFrameChange;
+ (void)OnSystemStatusBarOrientationChange:(long long)arg1;
+ (id)mainWindow;
+ (double)visibleHeight:(id)arg1;
+ (struct CGRect)windowBoundsOri:(long long)arg1;
+ (struct CGRect)screenBoundsOri:(long long)arg1;
+ (struct CGRect)screenBounds;
+ (struct CGSize)screenSizeOri:(long long)arg1;
+ (struct CGSize)screenSize;
+ (double)mainScreenWidth;
+ (double)deviceScreenWidth:(long long)arg1;
+ (double)screenWidth:(long long)arg1;
+ (double)deviceScreenWidth;
+ (double)windowWidth;
+ (double)screenWidthCurOri;
+ (double)screenHeight:(long long)arg1;
+ (double)screenHeightCurOri;
+ (double)navigationBarHeight:(long long)arg1;
+ (double)navigationBarHeightCurOri;
+ (double)navigationBarHeight;
+ (double)statusBarHeight:(long long)arg1;
+ (double)statusBarHeight;
+ (double)normalStatusBarHeight;

@end



@interface WCPayQRCodeRewardControlData : NSObject
@property(nonatomic) long long payerSelectedAmount; // @synthesize payerSelectedAmount=_payerSelectedAmount;
@property(nonatomic) long long setupViewControllerScene; // @synthesize setupViewControllerScene=_setupViewControllerScene;
@property(nonatomic) int payChannel; // @synthesize payChannel=_payChannel;
@property(retain, nonatomic) NSString *sourceWebViewUrl; // @synthesize sourceWebViewUrl=_sourceWebViewUrl;
@property(retain, nonatomic) NSString *scanUrl; // @synthesize scanUrl=_scanUrl;
@end

@interface WCPayControlData : NSObject
@property(retain, nonatomic) WCPayQRCodeRewardControlData *qrcodeRewardData; // @synthesize scanUrl=_scanUrl;
@end

@interface WCBaseControlLogic : NSObject
- (id)gotoViewController:(Class)arg1 withData:(id)arg2;
@end


@interface WCPayQRCodeRewardPayerConfirmViewController : UIViewController
{
    WCPayControlData *m_data;
}
@property(nonatomic)id delegate; // @synthesize delegate=_delegate;
- (void)refreshViewWithData:(id)arg1;
- (void)setupWithData:(id)arg1;

@end

@interface WCPayQRCodeRewardPayControlLogic : NSObject
- (id)initWithScanUrl:(id)arg1 sourceWebViewUrl:(id)arg2 payChannel:(int)arg3;
@end


@interface ScanQRCodeLogicController: NSObject

@property(nonatomic) unsigned int fromScene;
- (id)initWithViewController:(id)arg1 CodeType:(int)arg2 needCameraScan:(_Bool)arg3;
- (id)initWithViewController:(id)arg1 CodeType:(int)arg2;
- (void)tryScanOnePicture:(id)arg1;
- (void)doScanQRCode:(id)arg1;
- (void)showScanResult;

@end
@interface WCPayBizF2FPaidSuccViewController : NSObject
@property(retain, nonatomic) WCPayControlData *m_data; // @synthesize m_data=_m_data;

@end

@interface WCPayTransferMoneyPaidSuccessViewV2 : NSObject

@property(retain, nonatomic) WCPayTransferMoneyPaidSuccessViewV2 *m_layoutV2; // @synthesize m_layoutV2=_m_layoutV2;
@end
