platform :ios, '8.0'
target 'email' do
#pod 'MJRefresh'
#pod 'AFNetworking'
#pod 'MBProgressHUD'
#pod 'Masonry'
#pod 'SAMKeychain'
#pod 'SDWebImage'
#pod 'MJExtension'
#pod 'FMDB'
#pod 'mailcore2-ios'
#pod 'MRProgress'

end
